// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_sms.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const adminCampaignBilling = `-- name: AdminCampaignBilling :one
SELECT
    COALESCE(SUM(unit_sell_price * billed_segments) FILTER (WHERE billing_action = 'capture'), 0)::text AS captured,
    COALESCE(SUM(unit_sell_price * billed_segments) FILTER (WHERE billing_action IS NULL AND unit_sell_price IS NOT NULL), 0)::text AS held,
    COALESCE(SUM(unit_sell_price * billed_segments) FILTER (WHERE billing_action = 'release'), 0)::text AS released,
    COALESCE(MAX(currency)::text, '') AS currency
FROM sms_messages
WHERE campaign_id = $1
  AND direction = 'outbound'
`

type AdminCampaignBillingRow struct {
	Captured string      `json:"captured"`
	Held     string      `json:"held"`
	Released string      `json:"released"`
	Currency interface{} `json:"currency"`
}

func (q *Queries) AdminCampaignBilling(ctx context.Context, campaignID *uuid.UUID) (AdminCampaignBillingRow, error) {
	row := q.db.QueryRow(ctx, adminCampaignBilling, campaignID)
	var i AdminCampaignBillingRow
	err := row.Scan(
		&i.Captured,
		&i.Held,
		&i.Released,
		&i.Currency,
	)
	return i, err
}

const adminGetCampaign = `-- name: AdminGetCampaign :one
SELECT
    c.id,
    c.client_id,
    cl.name AS client_name,
    c.from_msisdn,
    c.text,
    c.status,
    c.total_count,
    c.accepted_count,
    c.delivered_count,
    c.failed_count,
    c.created_by,
    cu.email AS created_by_email,
    c.created_at,
    c.updated_at
FROM sms_campaigns c
LEFT JOIN clients cl ON cl.id = c.client_id
LEFT JOIN client_users cu ON cu.id = c.created_by
WHERE c.id = $1
`

type AdminGetCampaignRow struct {
	ID             uuid.UUID      `json:"id"`
	ClientID       uuid.UUID      `json:"client_id"`
	ClientName     *string        `json:"client_name"`
	FromMsisdn     string         `json:"from_msisdn"`
	Text           string         `json:"text"`
	Status         CampaignStatus `json:"status"`
	TotalCount     int32          `json:"total_count"`
	AcceptedCount  int32          `json:"accepted_count"`
	DeliveredCount int32          `json:"delivered_count"`
	FailedCount    int32          `json:"failed_count"`
	CreatedBy      *uuid.UUID     `json:"created_by"`
	CreatedByEmail *string        `json:"created_by_email"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) AdminGetCampaign(ctx context.Context, id uuid.UUID) (AdminGetCampaignRow, error) {
	row := q.db.QueryRow(ctx, adminGetCampaign, id)
	var i AdminGetCampaignRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.FromMsisdn,
		&i.Text,
		&i.Status,
		&i.TotalCount,
		&i.AcceptedCount,
		&i.DeliveredCount,
		&i.FailedCount,
		&i.CreatedBy,
		&i.CreatedByEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetSendJobByMessage = `-- name: AdminGetSendJobByMessage :one
SELECT
    id,
    sms_message_id,
    status,
    attempt,
    available_at,
    locked_at,
    locked_by,
    last_error,
    created_at,
    updated_at
FROM send_jobs
WHERE sms_message_id = $1
`

type AdminGetSendJobByMessageRow struct {
	ID           uuid.UUID     `json:"id"`
	SmsMessageID uuid.UUID     `json:"sms_message_id"`
	Status       SendJobStatus `json:"status"`
	Attempt      int32         `json:"attempt"`
	AvailableAt  time.Time     `json:"available_at"`
	LockedAt     *time.Time    `json:"locked_at"`
	LockedBy     *string       `json:"locked_by"`
	LastError    *string       `json:"last_error"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
}

func (q *Queries) AdminGetSendJobByMessage(ctx context.Context, smsMessageID uuid.UUID) (AdminGetSendJobByMessageRow, error) {
	row := q.db.QueryRow(ctx, adminGetSendJobByMessage, smsMessageID)
	var i AdminGetSendJobByMessageRow
	err := row.Scan(
		&i.ID,
		&i.SmsMessageID,
		&i.Status,
		&i.Attempt,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetSmsMessage = `-- name: AdminGetSmsMessage :one
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    m.text,
    m.provider,
    m.provider_sms_id,
    m.provider_status,
    m.pdu_count,
    m.campaign_id,
    m.status,
    m.idempotency_key,
    m.created_at,
    m.accepted_at,
    m.sent_at,
    m.delivered_at,
    m.failed_at,
    m.unit_sell_price,
    m.billed_segments,
    m.tariff_plan_id,
    m.tariff_plan_code,
    m.currency,
    m.billing_action
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE m.id = $1
`

type AdminGetSmsMessageRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	Text           string            `json:"text"`
	Provider       string            `json:"provider"`
	ProviderSmsID  *string           `json:"provider_sms_id"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	Status         SmsStatus         `json:"status"`
	IdempotencyKey *string           `json:"idempotency_key"`
	CreatedAt      time.Time         `json:"created_at"`
	AcceptedAt     *time.Time        `json:"accepted_at"`
	SentAt         *time.Time        `json:"sent_at"`
	DeliveredAt    *time.Time        `json:"delivered_at"`
	FailedAt       *time.Time        `json:"failed_at"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	BilledSegments *int32            `json:"billed_segments"`
	TariffPlanID   *uuid.UUID        `json:"tariff_plan_id"`
	TariffPlanCode *string           `json:"tariff_plan_code"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
}

func (q *Queries) AdminGetSmsMessage(ctx context.Context, id uuid.UUID) (AdminGetSmsMessageRow, error) {
	row := q.db.QueryRow(ctx, adminGetSmsMessage, id)
	var i AdminGetSmsMessageRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.Direction,
		&i.FromMsisdn,
		&i.ToMsisdn,
		&i.Text,
		&i.Provider,
		&i.ProviderSmsID,
		&i.ProviderStatus,
		&i.PduCount,
		&i.CampaignID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UnitSellPrice,
		&i.BilledSegments,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.BillingAction,
	)
	return i, err
}

const adminGetSmsMessageByProviderID = `-- name: AdminGetSmsMessageByProviderID :one
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE m.provider_sms_id = $1
  AND cl.status IS DISTINCT FROM 'deleted'
`

type AdminGetSmsMessageByProviderIDRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminGetSmsMessageByProviderID(ctx context.Context, providerSmsID *string) (AdminGetSmsMessageByProviderIDRow, error) {
	row := q.db.QueryRow(ctx, adminGetSmsMessageByProviderID, providerSmsID)
	var i AdminGetSmsMessageByProviderIDRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.Direction,
		&i.FromMsisdn,
		&i.ToMsisdn,
		&i.TextPreview,
		&i.Status,
		&i.ProviderStatus,
		&i.PduCount,
		&i.BilledSegments,
		&i.UnitSellPrice,
		&i.Currency,
		&i.BillingAction,
		&i.CampaignID,
		&i.CreatedAt,
	)
	return i, err
}

const adminListCampaignOutbound = `-- name: AdminListCampaignOutbound :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.direction = 'outbound'
  AND m.campaign_id IS NOT NULL
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2 OFFSET $1
`

type AdminListCampaignOutboundParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type AdminListCampaignOutboundRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListCampaignOutbound(ctx context.Context, arg AdminListCampaignOutboundParams) ([]AdminListCampaignOutboundRow, error) {
	rows, err := q.db.Query(ctx, adminListCampaignOutbound, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListCampaignOutboundRow
	for rows.Next() {
		var i AdminListCampaignOutboundRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListCampaignOutboundByStatus = `-- name: AdminListCampaignOutboundByStatus :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.direction = 'outbound'
  AND m.campaign_id IS NOT NULL
  AND m.status = $1::sms_status
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3 OFFSET $2
`

type AdminListCampaignOutboundByStatusParams struct {
	Status     SmsStatus `json:"status"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type AdminListCampaignOutboundByStatusRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListCampaignOutboundByStatus(ctx context.Context, arg AdminListCampaignOutboundByStatusParams) ([]AdminListCampaignOutboundByStatusRow, error) {
	rows, err := q.db.Query(ctx, adminListCampaignOutboundByStatus, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListCampaignOutboundByStatusRow
	for rows.Next() {
		var i AdminListCampaignOutboundByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListCampaignOutboundFailed = `-- name: AdminListCampaignOutboundFailed :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.direction = 'outbound'
  AND m.campaign_id IS NOT NULL
  AND m.status = 'failed'
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2 OFFSET $1
`

type AdminListCampaignOutboundFailedParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type AdminListCampaignOutboundFailedRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListCampaignOutboundFailed(ctx context.Context, arg AdminListCampaignOutboundFailedParams) ([]AdminListCampaignOutboundFailedRow, error) {
	rows, err := q.db.Query(ctx, adminListCampaignOutboundFailed, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListCampaignOutboundFailedRow
	for rows.Next() {
		var i AdminListCampaignOutboundFailedRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListCampaignOutboundInflight = `-- name: AdminListCampaignOutboundInflight :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.direction = 'outbound'
  AND m.campaign_id IS NOT NULL
  AND m.status IN ('queued', 'accepted', 'sent')
  AND m.status = $1::sms_status
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3 OFFSET $2
`

type AdminListCampaignOutboundInflightParams struct {
	Status     SmsStatus `json:"status"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type AdminListCampaignOutboundInflightRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListCampaignOutboundInflight(ctx context.Context, arg AdminListCampaignOutboundInflightParams) ([]AdminListCampaignOutboundInflightRow, error) {
	rows, err := q.db.Query(ctx, adminListCampaignOutboundInflight, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListCampaignOutboundInflightRow
	for rows.Next() {
		var i AdminListCampaignOutboundInflightRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListCampaignRecipients = `-- name: AdminListCampaignRecipients :many
SELECT
    r.id,
    r.to_msisdn,
    r.status,
    r.sms_message_id,
    r.created_at,
    m.status AS message_status,
    m.provider_sms_id,
    m.provider_status,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    j.last_error
FROM campaign_recipients r
LEFT JOIN sms_messages m ON m.id = r.sms_message_id
LEFT JOIN send_jobs j ON j.sms_message_id = m.id
WHERE r.campaign_id = $1
ORDER BY r.created_at, r.id
LIMIT $2
`

type AdminListCampaignRecipientsParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	PageLimit  int32     `json:"page_limit"`
}

type AdminListCampaignRecipientsRow struct {
	ID             uuid.UUID               `json:"id"`
	ToMsisdn       string                  `json:"to_msisdn"`
	Status         CampaignRecipientStatus `json:"status"`
	SmsMessageID   *uuid.UUID              `json:"sms_message_id"`
	CreatedAt      time.Time               `json:"created_at"`
	MessageStatus  NullSmsStatus           `json:"message_status"`
	ProviderSmsID  *string                 `json:"provider_sms_id"`
	ProviderStatus *string                 `json:"provider_status"`
	BilledSegments *int32                  `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal        `json:"unit_sell_price"`
	Currency       *string                 `json:"currency"`
	BillingAction  NullBillingAction       `json:"billing_action"`
	LastError      *string                 `json:"last_error"`
}

func (q *Queries) AdminListCampaignRecipients(ctx context.Context, arg AdminListCampaignRecipientsParams) ([]AdminListCampaignRecipientsRow, error) {
	rows, err := q.db.Query(ctx, adminListCampaignRecipients, arg.CampaignID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListCampaignRecipientsRow
	for rows.Next() {
		var i AdminListCampaignRecipientsRow
		if err := rows.Scan(
			&i.ID,
			&i.ToMsisdn,
			&i.Status,
			&i.SmsMessageID,
			&i.CreatedAt,
			&i.MessageStatus,
			&i.ProviderSmsID,
			&i.ProviderStatus,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListCampaignRecipientsAfter = `-- name: AdminListCampaignRecipientsAfter :many
SELECT
    r.id,
    r.to_msisdn,
    r.status,
    r.sms_message_id,
    r.created_at,
    m.status AS message_status,
    m.provider_sms_id,
    m.provider_status,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    j.last_error
FROM campaign_recipients r
LEFT JOIN sms_messages m ON m.id = r.sms_message_id
LEFT JOIN send_jobs j ON j.sms_message_id = m.id
WHERE r.campaign_id = $1
  AND (r.created_at, r.id) > ($2::timestamptz, $3::uuid)
ORDER BY r.created_at, r.id
LIMIT $4
`

type AdminListCampaignRecipientsAfterParams struct {
	CampaignID      uuid.UUID `json:"campaign_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

type AdminListCampaignRecipientsAfterRow struct {
	ID             uuid.UUID               `json:"id"`
	ToMsisdn       string                  `json:"to_msisdn"`
	Status         CampaignRecipientStatus `json:"status"`
	SmsMessageID   *uuid.UUID              `json:"sms_message_id"`
	CreatedAt      time.Time               `json:"created_at"`
	MessageStatus  NullSmsStatus           `json:"message_status"`
	ProviderSmsID  *string                 `json:"provider_sms_id"`
	ProviderStatus *string                 `json:"provider_status"`
	BilledSegments *int32                  `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal        `json:"unit_sell_price"`
	Currency       *string                 `json:"currency"`
	BillingAction  NullBillingAction       `json:"billing_action"`
	LastError      *string                 `json:"last_error"`
}

func (q *Queries) AdminListCampaignRecipientsAfter(ctx context.Context, arg AdminListCampaignRecipientsAfterParams) ([]AdminListCampaignRecipientsAfterRow, error) {
	rows, err := q.db.Query(ctx, adminListCampaignRecipientsAfter,
		arg.CampaignID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListCampaignRecipientsAfterRow
	for rows.Next() {
		var i AdminListCampaignRecipientsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.ToMsisdn,
			&i.Status,
			&i.SmsMessageID,
			&i.CreatedAt,
			&i.MessageStatus,
			&i.ProviderSmsID,
			&i.ProviderStatus,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListCampaigns = `-- name: AdminListCampaigns :many
SELECT
    c.id,
    c.client_id,
    cl.name AS client_name,
    c.from_msisdn,
    (CASE WHEN char_length(c.text) > 80 THEN left(c.text, 80) || '…' ELSE c.text END)::text AS text_preview,
    c.status,
    c.total_count,
    c.accepted_count,
    c.delivered_count,
    c.failed_count,
    c.created_at
FROM sms_campaigns c
JOIN clients cl ON cl.id = c.client_id AND cl.status <> 'deleted'
WHERE ($1::uuid IS NULL OR c.client_id = $1)
  AND ($2::campaign_status IS NULL OR c.status = $2)
  AND ($3::text IS NULL OR c.from_msisdn = $3)
ORDER BY c.created_at DESC, c.id DESC
LIMIT $5 OFFSET $4
`

type AdminListCampaignsParams struct {
	ClientID   *uuid.UUID         `json:"client_id"`
	Status     NullCampaignStatus `json:"status"`
	FromMsisdn *string            `json:"from_msisdn"`
	PageOffset int32              `json:"page_offset"`
	PageLimit  int32              `json:"page_limit"`
}

type AdminListCampaignsRow struct {
	ID             uuid.UUID      `json:"id"`
	ClientID       uuid.UUID      `json:"client_id"`
	ClientName     string         `json:"client_name"`
	FromMsisdn     string         `json:"from_msisdn"`
	TextPreview    string         `json:"text_preview"`
	Status         CampaignStatus `json:"status"`
	TotalCount     int32          `json:"total_count"`
	AcceptedCount  int32          `json:"accepted_count"`
	DeliveredCount int32          `json:"delivered_count"`
	FailedCount    int32          `json:"failed_count"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (q *Queries) AdminListCampaigns(ctx context.Context, arg AdminListCampaignsParams) ([]AdminListCampaignsRow, error) {
	rows, err := q.db.Query(ctx, adminListCampaigns,
		arg.ClientID,
		arg.Status,
		arg.FromMsisdn,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListCampaignsRow
	for rows.Next() {
		var i AdminListCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.FromMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.TotalCount,
			&i.AcceptedCount,
			&i.DeliveredCount,
			&i.FailedCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListClientCampaign = `-- name: AdminListClientCampaign :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.client_id = $1
  AND m.direction = 'outbound'
  AND m.campaign_id IS NOT NULL
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3 OFFSET $2
`

type AdminListClientCampaignParams struct {
	ClientID   *uuid.UUID `json:"client_id"`
	PageOffset int32      `json:"page_offset"`
	PageLimit  int32      `json:"page_limit"`
}

type AdminListClientCampaignRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListClientCampaign(ctx context.Context, arg AdminListClientCampaignParams) ([]AdminListClientCampaignRow, error) {
	rows, err := q.db.Query(ctx, adminListClientCampaign, arg.ClientID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListClientCampaignRow
	for rows.Next() {
		var i AdminListClientCampaignRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListClientCampaignByStatus = `-- name: AdminListClientCampaignByStatus :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.client_id = $1
  AND m.direction = 'outbound'
  AND m.campaign_id IS NOT NULL
  AND m.status = $2::sms_status
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4 OFFSET $3
`

type AdminListClientCampaignByStatusParams struct {
	ClientID   *uuid.UUID `json:"client_id"`
	Status     SmsStatus  `json:"status"`
	PageOffset int32      `json:"page_offset"`
	PageLimit  int32      `json:"page_limit"`
}

type AdminListClientCampaignByStatusRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListClientCampaignByStatus(ctx context.Context, arg AdminListClientCampaignByStatusParams) ([]AdminListClientCampaignByStatusRow, error) {
	rows, err := q.db.Query(ctx, adminListClientCampaignByStatus,
		arg.ClientID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListClientCampaignByStatusRow
	for rows.Next() {
		var i AdminListClientCampaignByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListClientDirect = `-- name: AdminListClientDirect :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.client_id = $1
  AND m.direction = 'outbound'
  AND m.campaign_id IS NULL
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3 OFFSET $2
`

type AdminListClientDirectParams struct {
	ClientID   *uuid.UUID `json:"client_id"`
	PageOffset int32      `json:"page_offset"`
	PageLimit  int32      `json:"page_limit"`
}

type AdminListClientDirectRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListClientDirect(ctx context.Context, arg AdminListClientDirectParams) ([]AdminListClientDirectRow, error) {
	rows, err := q.db.Query(ctx, adminListClientDirect, arg.ClientID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListClientDirectRow
	for rows.Next() {
		var i AdminListClientDirectRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListClientDirectByStatus = `-- name: AdminListClientDirectByStatus :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.client_id = $1
  AND m.direction = 'outbound'
  AND m.campaign_id IS NULL
  AND m.status = $2::sms_status
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4 OFFSET $3
`

type AdminListClientDirectByStatusParams struct {
	ClientID   *uuid.UUID `json:"client_id"`
	Status     SmsStatus  `json:"status"`
	PageOffset int32      `json:"page_offset"`
	PageLimit  int32      `json:"page_limit"`
}

type AdminListClientDirectByStatusRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListClientDirectByStatus(ctx context.Context, arg AdminListClientDirectByStatusParams) ([]AdminListClientDirectByStatusRow, error) {
	rows, err := q.db.Query(ctx, adminListClientDirectByStatus,
		arg.ClientID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListClientDirectByStatusRow
	for rows.Next() {
		var i AdminListClientDirectByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListClientMessages = `-- name: AdminListClientMessages :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.client_id = $1
  AND m.direction = $2::sms_direction
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4 OFFSET $3
`

type AdminListClientMessagesParams struct {
	ClientID   *uuid.UUID   `json:"client_id"`
	Direction  SmsDirection `json:"direction"`
	PageOffset int32        `json:"page_offset"`
	PageLimit  int32        `json:"page_limit"`
}

type AdminListClientMessagesRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListClientMessages(ctx context.Context, arg AdminListClientMessagesParams) ([]AdminListClientMessagesRow, error) {
	rows, err := q.db.Query(ctx, adminListClientMessages,
		arg.ClientID,
		arg.Direction,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListClientMessagesRow
	for rows.Next() {
		var i AdminListClientMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListClientMessagesByStatus = `-- name: AdminListClientMessagesByStatus :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.client_id = $1
  AND m.direction = $2::sms_direction
  AND m.status = $3::sms_status
ORDER BY m.created_at DESC, m.id DESC
LIMIT $5 OFFSET $4
`

type AdminListClientMessagesByStatusParams struct {
	ClientID   *uuid.UUID   `json:"client_id"`
	Direction  SmsDirection `json:"direction"`
	Status     SmsStatus    `json:"status"`
	PageOffset int32        `json:"page_offset"`
	PageLimit  int32        `json:"page_limit"`
}

type AdminListClientMessagesByStatusRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListClientMessagesByStatus(ctx context.Context, arg AdminListClientMessagesByStatusParams) ([]AdminListClientMessagesByStatusRow, error) {
	rows, err := q.db.Query(ctx, adminListClientMessagesByStatus,
		arg.ClientID,
		arg.Direction,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListClientMessagesByStatusRow
	for rows.Next() {
		var i AdminListClientMessagesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListDeliveredMessages = `-- name: AdminListDeliveredMessages :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.status = 'delivered'
  AND m.direction = $1::sms_direction
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3 OFFSET $2
`

type AdminListDeliveredMessagesParams struct {
	Direction  SmsDirection `json:"direction"`
	PageOffset int32        `json:"page_offset"`
	PageLimit  int32        `json:"page_limit"`
}

type AdminListDeliveredMessagesRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListDeliveredMessages(ctx context.Context, arg AdminListDeliveredMessagesParams) ([]AdminListDeliveredMessagesRow, error) {
	rows, err := q.db.Query(ctx, adminListDeliveredMessages, arg.Direction, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListDeliveredMessagesRow
	for rows.Next() {
		var i AdminListDeliveredMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListDirectOutbound = `-- name: AdminListDirectOutbound :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.direction = 'outbound'
  AND m.campaign_id IS NULL
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2 OFFSET $1
`

type AdminListDirectOutboundParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type AdminListDirectOutboundRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListDirectOutbound(ctx context.Context, arg AdminListDirectOutboundParams) ([]AdminListDirectOutboundRow, error) {
	rows, err := q.db.Query(ctx, adminListDirectOutbound, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListDirectOutboundRow
	for rows.Next() {
		var i AdminListDirectOutboundRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListDirectOutboundByStatus = `-- name: AdminListDirectOutboundByStatus :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.direction = 'outbound'
  AND m.campaign_id IS NULL
  AND m.status = $1::sms_status
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3 OFFSET $2
`

type AdminListDirectOutboundByStatusParams struct {
	Status     SmsStatus `json:"status"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type AdminListDirectOutboundByStatusRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListDirectOutboundByStatus(ctx context.Context, arg AdminListDirectOutboundByStatusParams) ([]AdminListDirectOutboundByStatusRow, error) {
	rows, err := q.db.Query(ctx, adminListDirectOutboundByStatus, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListDirectOutboundByStatusRow
	for rows.Next() {
		var i AdminListDirectOutboundByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListFailedMessages = `-- name: AdminListFailedMessages :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.status = 'failed'
  AND m.direction = $1::sms_direction
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3 OFFSET $2
`

type AdminListFailedMessagesParams struct {
	Direction  SmsDirection `json:"direction"`
	PageOffset int32        `json:"page_offset"`
	PageLimit  int32        `json:"page_limit"`
}

type AdminListFailedMessagesRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListFailedMessages(ctx context.Context, arg AdminListFailedMessagesParams) ([]AdminListFailedMessagesRow, error) {
	rows, err := q.db.Query(ctx, adminListFailedMessages, arg.Direction, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListFailedMessagesRow
	for rows.Next() {
		var i AdminListFailedMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListInboundMessages = `-- name: AdminListInboundMessages :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.direction = 'inbound'
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2 OFFSET $1
`

type AdminListInboundMessagesParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type AdminListInboundMessagesRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListInboundMessages(ctx context.Context, arg AdminListInboundMessagesParams) ([]AdminListInboundMessagesRow, error) {
	rows, err := q.db.Query(ctx, adminListInboundMessages, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListInboundMessagesRow
	for rows.Next() {
		var i AdminListInboundMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListInboundMessagesByStatus = `-- name: AdminListInboundMessagesByStatus :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.direction = 'inbound'
  AND m.status = $1::sms_status
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3 OFFSET $2
`

type AdminListInboundMessagesByStatusParams struct {
	Status     SmsStatus `json:"status"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type AdminListInboundMessagesByStatusRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListInboundMessagesByStatus(ctx context.Context, arg AdminListInboundMessagesByStatusParams) ([]AdminListInboundMessagesByStatusRow, error) {
	rows, err := q.db.Query(ctx, adminListInboundMessagesByStatus, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListInboundMessagesByStatusRow
	for rows.Next() {
		var i AdminListInboundMessagesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListMessageCallbacks = `-- name: AdminListMessageCallbacks :many
SELECT
    id,
    kind,
    created_at,
    processed_at,
    parsed
FROM provider_callback_events
WHERE sms_message_id = $1
ORDER BY created_at DESC
LIMIT 20
`

type AdminListMessageCallbacksRow struct {
	ID          uuid.UUID    `json:"id"`
	Kind        CallbackKind `json:"kind"`
	CreatedAt   time.Time    `json:"created_at"`
	ProcessedAt *time.Time   `json:"processed_at"`
	Parsed      []byte       `json:"parsed"`
}

func (q *Queries) AdminListMessageCallbacks(ctx context.Context, smsMessageID *uuid.UUID) ([]AdminListMessageCallbacksRow, error) {
	rows, err := q.db.Query(ctx, adminListMessageCallbacks, smsMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListMessageCallbacksRow
	for rows.Next() {
		var i AdminListMessageCallbacksRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.Parsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListMessagesByMSISDN = `-- name: AdminListMessagesByMSISDN :many
SELECT
    id,
    client_id,
    client_name,
    direction,
    from_msisdn,
    to_msisdn,
    text_preview,
    status,
    provider_status,
    pdu_count,
    billed_segments,
    unit_sell_price,
    currency,
    billing_action,
    campaign_id,
    created_at
FROM (
    SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
    WHERE m.from_msisdn = $1
      AND m.direction = $2::sms_direction
      AND cl.status IS DISTINCT FROM 'deleted'
      AND ($3::uuid IS NULL OR m.client_id = $3)
      AND ($4::sms_status IS NULL OR m.status = $4)
      AND (
        $5::text IS NULL
        OR ($5::text = 'direct' AND m.campaign_id IS NULL)
        OR ($5::text = 'campaign' AND m.campaign_id IS NOT NULL)
      )
    UNION ALL
    SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
    WHERE m.to_msisdn = $1
      AND m.direction = $2::sms_direction
      AND cl.status IS DISTINCT FROM 'deleted'
      AND ($3::uuid IS NULL OR m.client_id = $3)
      AND ($4::sms_status IS NULL OR m.status = $4)
      AND (
        $5::text IS NULL
        OR ($5::text = 'direct' AND m.campaign_id IS NULL)
        OR ($5::text = 'campaign' AND m.campaign_id IS NOT NULL)
      )
      AND m.from_msisdn <> $1
) AS matched
ORDER BY created_at DESC, id DESC
LIMIT $7 OFFSET $6
`

type AdminListMessagesByMSISDNParams struct {
	Msisdn     string        `json:"msisdn"`
	Direction  SmsDirection  `json:"direction"`
	ClientID   *uuid.UUID    `json:"client_id"`
	Status     NullSmsStatus `json:"status"`
	Source     *string       `json:"source"`
	PageOffset int32         `json:"page_offset"`
	PageLimit  int32         `json:"page_limit"`
}

type AdminListMessagesByMSISDNRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListMessagesByMSISDN(ctx context.Context, arg AdminListMessagesByMSISDNParams) ([]AdminListMessagesByMSISDNRow, error) {
	rows, err := q.db.Query(ctx, adminListMessagesByMSISDN,
		arg.Msisdn,
		arg.Direction,
		arg.ClientID,
		arg.Status,
		arg.Source,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListMessagesByMSISDNRow
	for rows.Next() {
		var i AdminListMessagesByMSISDNRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOutboundInflight = `-- name: AdminListOutboundInflight :many
SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.direction = 'outbound'
  AND m.status IN ('queued', 'accepted', 'sent')
  AND m.status = $1::sms_status
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3 OFFSET $2
`

type AdminListOutboundInflightParams struct {
	Status     SmsStatus `json:"status"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type AdminListOutboundInflightRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

func (q *Queries) AdminListOutboundInflight(ctx context.Context, arg AdminListOutboundInflightParams) ([]AdminListOutboundInflightRow, error) {
	rows, err := q.db.Query(ctx, adminListOutboundInflight, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOutboundInflightRow
	for rows.Next() {
		var i AdminListOutboundInflightRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOutboundMessages = `-- name: AdminListOutboundMessages :many

SELECT
    m.id,
    m.client_id,
    cl.name AS client_name,
    m.direction,
    m.from_msisdn,
    m.to_msisdn,
    (CASE WHEN char_length(m.text) > 80 THEN left(m.text, 80) || '…' ELSE m.text END)::text AS text_preview,
    m.status,
    m.provider_status,
    m.pdu_count,
    m.billed_segments,
    m.unit_sell_price,
    m.currency,
    m.billing_action,
    m.campaign_id,
    m.created_at
FROM sms_messages m
LEFT JOIN clients cl ON cl.id = m.client_id
WHERE cl.status IS DISTINCT FROM 'deleted'
  AND m.direction = 'outbound'
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2 OFFSET $1
`

type AdminListOutboundMessagesParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type AdminListOutboundMessagesRow struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	ClientName     *string           `json:"client_name"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	TextPreview    string            `json:"text_preview"`
	Status         SmsStatus         `json:"status"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	BilledSegments *int32            `json:"billed_segments"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	CreatedAt      time.Time         `json:"created_at"`
}

// Admin read models. Each list query keeps the index-driving predicate as a
// plain equality or a literal partial-index predicate. Do not fold these into
// one statement with OR-null filters on those columns.
func (q *Queries) AdminListOutboundMessages(ctx context.Context, arg AdminListOutboundMessagesParams) ([]AdminListOutboundMessagesRow, error) {
	rows, err := q.db.Query(ctx, adminListOutboundMessages, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOutboundMessagesRow
	for rows.Next() {
		var i AdminListOutboundMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.TextPreview,
			&i.Status,
			&i.ProviderStatus,
			&i.PduCount,
			&i.BilledSegments,
			&i.UnitSellPrice,
			&i.Currency,
			&i.BillingAction,
			&i.CampaignID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListSendAttempts = `-- name: AdminListSendAttempts :many
SELECT
    id,
    attempt,
    request_meta,
    http_status,
    response_body,
    latency_ms,
    error_kind,
    created_at
FROM provider_send_attempts
WHERE send_job_id = $1
ORDER BY attempt DESC, created_at DESC
LIMIT 20
`

type AdminListSendAttemptsRow struct {
	ID           uuid.UUID           `json:"id"`
	Attempt      int32               `json:"attempt"`
	RequestMeta  []byte              `json:"request_meta"`
	HttpStatus   *int32              `json:"http_status"`
	ResponseBody *string             `json:"response_body"`
	LatencyMs    *int32              `json:"latency_ms"`
	ErrorKind    NullSendAttemptKind `json:"error_kind"`
	CreatedAt    time.Time           `json:"created_at"`
}

func (q *Queries) AdminListSendAttempts(ctx context.Context, sendJobID uuid.UUID) ([]AdminListSendAttemptsRow, error) {
	rows, err := q.db.Query(ctx, adminListSendAttempts, sendJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListSendAttemptsRow
	for rows.Next() {
		var i AdminListSendAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.Attempt,
			&i.RequestMeta,
			&i.HttpStatus,
			&i.ResponseBody,
			&i.LatencyMs,
			&i.ErrorKind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
