// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT count(*)::bigint AS count FROM admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdminUserByEmail = `-- name: GetAdminUserByEmail :one
SELECT id, email, password_hash, name, status, created_at, updated_at FROM admin_users WHERE LOWER(email) = LOWER($1) LIMIT 1
`

func (q *Queries) GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminUserByID = `-- name: GetAdminUserByID :one
SELECT id, email, password_hash, name, status, created_at, updated_at FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminUserByID(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAdminUser = `-- name: InsertAdminUser :one
INSERT INTO admin_users (email, password_hash, name, status)
VALUES ($1, $2, $3, 'active')
RETURNING id, email, password_hash, name, status, created_at, updated_at
`

type InsertAdminUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
}

func (q *Queries) InsertAdminUser(ctx context.Context, arg InsertAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, insertAdminUser, arg.Email, arg.PasswordHash, arg.Name)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
