// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apikeys.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAPICredentialByIDForClient = `-- name: GetAPICredentialByIDForClient :one
SELECT
    id, client_id, name, key_prefix, secret_hash, scopes, status,
    allowed_cidrs::text[] AS allowed_cidrs,
    last_used_at, created_by, created_at
FROM api_credentials
WHERE id = $1 AND client_id = $2
`

type GetAPICredentialByIDForClientParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

type GetAPICredentialByIDForClientRow struct {
	ID           uuid.UUID        `json:"id"`
	ClientID     uuid.UUID        `json:"client_id"`
	Name         string           `json:"name"`
	KeyPrefix    string           `json:"key_prefix"`
	SecretHash   string           `json:"secret_hash"`
	Scopes       []string         `json:"scopes"`
	Status       CredentialStatus `json:"status"`
	AllowedCidrs []string         `json:"allowed_cidrs"`
	LastUsedAt   *time.Time       `json:"last_used_at"`
	CreatedBy    *uuid.UUID       `json:"created_by"`
	CreatedAt    time.Time        `json:"created_at"`
}

func (q *Queries) GetAPICredentialByIDForClient(ctx context.Context, arg GetAPICredentialByIDForClientParams) (GetAPICredentialByIDForClientRow, error) {
	row := q.db.QueryRow(ctx, getAPICredentialByIDForClient, arg.ID, arg.ClientID)
	var i GetAPICredentialByIDForClientRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.KeyPrefix,
		&i.SecretHash,
		&i.Scopes,
		&i.Status,
		&i.AllowedCidrs,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAPICredentialByPrefix = `-- name: GetAPICredentialByPrefix :one
SELECT
    id, client_id, name, key_prefix, secret_hash, scopes, status,
    allowed_cidrs::text[] AS allowed_cidrs,
    last_used_at, created_by, created_at
FROM api_credentials
WHERE key_prefix = $1
`

type GetAPICredentialByPrefixRow struct {
	ID           uuid.UUID        `json:"id"`
	ClientID     uuid.UUID        `json:"client_id"`
	Name         string           `json:"name"`
	KeyPrefix    string           `json:"key_prefix"`
	SecretHash   string           `json:"secret_hash"`
	Scopes       []string         `json:"scopes"`
	Status       CredentialStatus `json:"status"`
	AllowedCidrs []string         `json:"allowed_cidrs"`
	LastUsedAt   *time.Time       `json:"last_used_at"`
	CreatedBy    *uuid.UUID       `json:"created_by"`
	CreatedAt    time.Time        `json:"created_at"`
}

func (q *Queries) GetAPICredentialByPrefix(ctx context.Context, keyPrefix string) (GetAPICredentialByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getAPICredentialByPrefix, keyPrefix)
	var i GetAPICredentialByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.KeyPrefix,
		&i.SecretHash,
		&i.Scopes,
		&i.Status,
		&i.AllowedCidrs,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertAPICredential = `-- name: InsertAPICredential :one
INSERT INTO api_credentials (
    client_id, name, key_prefix, secret_hash, scopes, allowed_cidrs, created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    COALESCE($6::text[]::inet[], ARRAY[]::inet[]),
    $7
)
RETURNING
    id, client_id, name, key_prefix, secret_hash, scopes, status,
    allowed_cidrs::text[] AS allowed_cidrs,
    last_used_at, created_by, created_at
`

type InsertAPICredentialParams struct {
	ClientID     uuid.UUID  `json:"client_id"`
	Name         string     `json:"name"`
	KeyPrefix    string     `json:"key_prefix"`
	SecretHash   string     `json:"secret_hash"`
	Scopes       []string   `json:"scopes"`
	AllowedCidrs []string   `json:"allowed_cidrs"`
	CreatedBy    *uuid.UUID `json:"created_by"`
}

type InsertAPICredentialRow struct {
	ID           uuid.UUID        `json:"id"`
	ClientID     uuid.UUID        `json:"client_id"`
	Name         string           `json:"name"`
	KeyPrefix    string           `json:"key_prefix"`
	SecretHash   string           `json:"secret_hash"`
	Scopes       []string         `json:"scopes"`
	Status       CredentialStatus `json:"status"`
	AllowedCidrs []string         `json:"allowed_cidrs"`
	LastUsedAt   *time.Time       `json:"last_used_at"`
	CreatedBy    *uuid.UUID       `json:"created_by"`
	CreatedAt    time.Time        `json:"created_at"`
}

func (q *Queries) InsertAPICredential(ctx context.Context, arg InsertAPICredentialParams) (InsertAPICredentialRow, error) {
	row := q.db.QueryRow(ctx, insertAPICredential,
		arg.ClientID,
		arg.Name,
		arg.KeyPrefix,
		arg.SecretHash,
		arg.Scopes,
		arg.AllowedCidrs,
		arg.CreatedBy,
	)
	var i InsertAPICredentialRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.KeyPrefix,
		&i.SecretHash,
		&i.Scopes,
		&i.Status,
		&i.AllowedCidrs,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAPICredentialsForClient = `-- name: ListAPICredentialsForClient :many
SELECT
    id, client_id, name, key_prefix, secret_hash, scopes, status,
    allowed_cidrs::text[] AS allowed_cidrs,
    last_used_at, created_by, created_at
FROM api_credentials
WHERE client_id = $1
ORDER BY created_at DESC
`

type ListAPICredentialsForClientRow struct {
	ID           uuid.UUID        `json:"id"`
	ClientID     uuid.UUID        `json:"client_id"`
	Name         string           `json:"name"`
	KeyPrefix    string           `json:"key_prefix"`
	SecretHash   string           `json:"secret_hash"`
	Scopes       []string         `json:"scopes"`
	Status       CredentialStatus `json:"status"`
	AllowedCidrs []string         `json:"allowed_cidrs"`
	LastUsedAt   *time.Time       `json:"last_used_at"`
	CreatedBy    *uuid.UUID       `json:"created_by"`
	CreatedAt    time.Time        `json:"created_at"`
}

func (q *Queries) ListAPICredentialsForClient(ctx context.Context, clientID uuid.UUID) ([]ListAPICredentialsForClientRow, error) {
	rows, err := q.db.Query(ctx, listAPICredentialsForClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPICredentialsForClientRow
	for rows.Next() {
		var i ListAPICredentialsForClientRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.KeyPrefix,
			&i.SecretHash,
			&i.Scopes,
			&i.Status,
			&i.AllowedCidrs,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPICredential = `-- name: RevokeAPICredential :one
UPDATE api_credentials
SET status = 'revoked'
WHERE id = $1
  AND client_id = $2
  AND status = 'active'
RETURNING
    id, client_id, name, key_prefix, secret_hash, scopes, status,
    allowed_cidrs::text[] AS allowed_cidrs,
    last_used_at, created_by, created_at
`

type RevokeAPICredentialParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

type RevokeAPICredentialRow struct {
	ID           uuid.UUID        `json:"id"`
	ClientID     uuid.UUID        `json:"client_id"`
	Name         string           `json:"name"`
	KeyPrefix    string           `json:"key_prefix"`
	SecretHash   string           `json:"secret_hash"`
	Scopes       []string         `json:"scopes"`
	Status       CredentialStatus `json:"status"`
	AllowedCidrs []string         `json:"allowed_cidrs"`
	LastUsedAt   *time.Time       `json:"last_used_at"`
	CreatedBy    *uuid.UUID       `json:"created_by"`
	CreatedAt    time.Time        `json:"created_at"`
}

func (q *Queries) RevokeAPICredential(ctx context.Context, arg RevokeAPICredentialParams) (RevokeAPICredentialRow, error) {
	row := q.db.QueryRow(ctx, revokeAPICredential, arg.ID, arg.ClientID)
	var i RevokeAPICredentialRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.KeyPrefix,
		&i.SecretHash,
		&i.Scopes,
		&i.Status,
		&i.AllowedCidrs,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAPICredentialsForClient = `-- name: RevokeAPICredentialsForClient :exec
UPDATE api_credentials
SET status = 'revoked'
WHERE client_id = $1 AND status = 'active'
`

func (q *Queries) RevokeAPICredentialsForClient(ctx context.Context, clientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPICredentialsForClient, clientID)
	return err
}

const touchAPICredential = `-- name: TouchAPICredential :exec
UPDATE api_credentials
SET last_used_at = now()
WHERE id = $1
  AND status = 'active'
  AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

func (q *Queries) TouchAPICredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPICredential, id)
	return err
}
