// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlcdb

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (
    actor_type, actor_id, client_id, action, resource_type, resource_id, ip, user_agent, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertAuditLogParams struct {
	ActorType    ActorType   `json:"actor_type"`
	ActorID      *uuid.UUID  `json:"actor_id"`
	ClientID     *uuid.UUID  `json:"client_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   *uuid.UUID  `json:"resource_id"`
	Ip           *netip.Addr `json:"ip"`
	UserAgent    *string     `json:"user_agent"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorType,
		arg.ActorID,
		arg.ClientID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	return err
}
