// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countLowBalanceClients = `-- name: CountLowBalanceClients :one
SELECT count(*)::bigint AS n
FROM wallets w
JOIN clients c ON c.id = w.client_id
WHERE c.status = 'active'
  AND w.available_balance < $1
`

func (q *Queries) CountLowBalanceClients(ctx context.Context, threshold decimal.Decimal) (int64, error) {
	row := q.db.QueryRow(ctx, countLowBalanceClients, threshold)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countOpenHolds = `-- name: CountOpenHolds :one
SELECT count(*)::bigint AS n
FROM wallet_transactions h
WHERE h.type = 'HOLD'
  AND h.sms_message_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM wallet_transactions s
      WHERE s.related_hold_id = h.id
        AND s.type IN ('DEBIT', 'RELEASE')
  )
`

// SMS metric only. Lookup job HOLDs have sms_message_id IS NULL and a
// separate CountOpenLookupHolds (remaining = hold − SUM(children)).
func (q *Queries) CountOpenHolds(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenHolds)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countOutboundSmsSinceByProduct = `-- name: CountOutboundSmsSinceByProduct :many
SELECT
    CASE
        WHEN p.product IS NOT NULL THEN p.product::text
        WHEN m.to_msisdn ~ '^7[0-9]{10}$' THEN 'sms_domestic'
        ELSE 'sms_international'
    END AS product,
    count(*)::bigint AS n
FROM sms_messages m
LEFT JOIN tariff_plans p ON p.id = m.tariff_plan_id
WHERE m.direction = 'outbound'
  AND m.created_at >= $1
GROUP BY 1
`

type CountOutboundSmsSinceByProductRow struct {
	Product string `json:"product"`
	N       int64  `json:"n"`
}

func (q *Queries) CountOutboundSmsSinceByProduct(ctx context.Context, since time.Time) ([]CountOutboundSmsSinceByProductRow, error) {
	rows, err := q.db.Query(ctx, countOutboundSmsSinceByProduct, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOutboundSmsSinceByProductRow
	for rows.Next() {
		var i CountOutboundSmsSinceByProductRow
		if err := rows.Scan(&i.Product, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOutboundSmsSinceByStatus = `-- name: CountOutboundSmsSinceByStatus :many
SELECT status, count(*)::bigint AS n
FROM sms_messages
WHERE direction = 'outbound'
  AND created_at >= $1
GROUP BY status
`

type CountOutboundSmsSinceByStatusRow struct {
	Status SmsStatus `json:"status"`
	N      int64     `json:"n"`
}

func (q *Queries) CountOutboundSmsSinceByStatus(ctx context.Context, since time.Time) ([]CountOutboundSmsSinceByStatusRow, error) {
	rows, err := q.db.Query(ctx, countOutboundSmsSinceByStatus, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOutboundSmsSinceByStatusRow
	for rows.Next() {
		var i CountOutboundSmsSinceByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOutboundSmsSinceByStatusForClient = `-- name: CountOutboundSmsSinceByStatusForClient :many
SELECT status, count(*)::bigint AS n
FROM sms_messages
WHERE direction = 'outbound'
  AND client_id = $1
  AND created_at >= $2
GROUP BY status
`

type CountOutboundSmsSinceByStatusForClientParams struct {
	ClientID *uuid.UUID `json:"client_id"`
	Since    time.Time  `json:"since"`
}

type CountOutboundSmsSinceByStatusForClientRow struct {
	Status SmsStatus `json:"status"`
	N      int64     `json:"n"`
}

func (q *Queries) CountOutboundSmsSinceByStatusForClient(ctx context.Context, arg CountOutboundSmsSinceByStatusForClientParams) ([]CountOutboundSmsSinceByStatusForClientRow, error) {
	rows, err := q.db.Query(ctx, countOutboundSmsSinceByStatusForClient, arg.ClientID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOutboundSmsSinceByStatusForClientRow
	for rows.Next() {
		var i CountOutboundSmsSinceByStatusForClientRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteClientTariff = `-- name: DeleteClientTariff :execrows
DELETE FROM client_tariffs
WHERE client_id = $1 AND product = $2
`

type DeleteClientTariffParams struct {
	ClientID uuid.UUID      `json:"client_id"`
	Product  BillingProduct `json:"product"`
}

func (q *Queries) DeleteClientTariff(ctx context.Context, arg DeleteClientTariffParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClientTariff, arg.ClientID, arg.Product)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClientTariff = `-- name: GetClientTariff :one
SELECT
    a.id,
    a.client_id,
    a.product,
    a.tariff_plan_id,
    a.price_override,
    a.effective_from,
    a.effective_to,
    p.code AS plan_code,
    p.name AS plan_name,
    p.sell_price AS plan_sell_price,
    p.currency,
    p.is_active AS plan_is_active
FROM client_tariffs a
JOIN tariff_plans p ON p.id = a.tariff_plan_id
WHERE a.client_id = $1
  AND a.product = $2
`

type GetClientTariffParams struct {
	ClientID uuid.UUID      `json:"client_id"`
	Product  BillingProduct `json:"product"`
}

type GetClientTariffRow struct {
	ID            uuid.UUID        `json:"id"`
	ClientID      uuid.UUID        `json:"client_id"`
	Product       BillingProduct   `json:"product"`
	TariffPlanID  uuid.UUID        `json:"tariff_plan_id"`
	PriceOverride *decimal.Decimal `json:"price_override"`
	EffectiveFrom time.Time        `json:"effective_from"`
	EffectiveTo   *time.Time       `json:"effective_to"`
	PlanCode      string           `json:"plan_code"`
	PlanName      string           `json:"plan_name"`
	PlanSellPrice decimal.Decimal  `json:"plan_sell_price"`
	Currency      string           `json:"currency"`
	PlanIsActive  bool             `json:"plan_is_active"`
}

func (q *Queries) GetClientTariff(ctx context.Context, arg GetClientTariffParams) (GetClientTariffRow, error) {
	row := q.db.QueryRow(ctx, getClientTariff, arg.ClientID, arg.Product)
	var i GetClientTariffRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Product,
		&i.TariffPlanID,
		&i.PriceOverride,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.PlanCode,
		&i.PlanName,
		&i.PlanSellPrice,
		&i.Currency,
		&i.PlanIsActive,
	)
	return i, err
}

const getOpenHoldForMessage = `-- name: GetOpenHoldForMessage :one
SELECT h.id, h.wallet_id, h.client_id, h.type, h.amount, h.currency, h.balance_after_available, h.balance_after_held, h.related_hold_id, h.sms_message_id, h.idempotency_key, h.description, h.metadata, h.created_by, h.created_at, h.lookup_job_id, h.lookup_item_id
FROM wallet_transactions h
WHERE h.sms_message_id = $1
  AND h.type = 'HOLD'
  AND NOT EXISTS (
      SELECT 1 FROM wallet_transactions s
      WHERE s.related_hold_id = h.id
        AND s.type IN ('DEBIT', 'RELEASE')
  )
ORDER BY h.created_at
LIMIT 1
`

func (q *Queries) GetOpenHoldForMessage(ctx context.Context, smsMessageID *uuid.UUID) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, getOpenHoldForMessage, smsMessageID)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.ClientID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.BalanceAfterAvailable,
		&i.BalanceAfterHeld,
		&i.RelatedHoldID,
		&i.SmsMessageID,
		&i.IdempotencyKey,
		&i.Description,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LookupJobID,
		&i.LookupItemID,
	)
	return i, err
}

const getTariffPlanByID = `-- name: GetTariffPlanByID :one
SELECT id, code, name, product, sell_price, currency, is_default, is_active, description, created_at, updated_at FROM tariff_plans WHERE id = $1
`

func (q *Queries) GetTariffPlanByID(ctx context.Context, id uuid.UUID) (TariffPlan, error) {
	row := q.db.QueryRow(ctx, getTariffPlanByID, id)
	var i TariffPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Product,
		&i.SellPrice,
		&i.Currency,
		&i.IsDefault,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByClientID = `-- name: GetWalletByClientID :one
SELECT id, client_id, currency, available_balance, held_balance, version, created_at, updated_at FROM wallets WHERE client_id = $1
`

func (q *Queries) GetWalletByClientID(ctx context.Context, clientID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByClientID, clientID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Currency,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletTxByIdempotency = `-- name: GetWalletTxByIdempotency :one
SELECT id, wallet_id, client_id, type, amount, currency, balance_after_available, balance_after_held, related_hold_id, sms_message_id, idempotency_key, description, metadata, created_by, created_at, lookup_job_id, lookup_item_id FROM wallet_transactions
WHERE client_id = $1
  AND idempotency_key = $2
`

type GetWalletTxByIdempotencyParams struct {
	ClientID       uuid.UUID `json:"client_id"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

func (q *Queries) GetWalletTxByIdempotency(ctx context.Context, arg GetWalletTxByIdempotencyParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, getWalletTxByIdempotency, arg.ClientID, arg.IdempotencyKey)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.ClientID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.BalanceAfterAvailable,
		&i.BalanceAfterHeld,
		&i.RelatedHoldID,
		&i.SmsMessageID,
		&i.IdempotencyKey,
		&i.Description,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LookupJobID,
		&i.LookupItemID,
	)
	return i, err
}

const insertTariffPlan = `-- name: InsertTariffPlan :one
INSERT INTO tariff_plans (code, name, product, sell_price, currency, is_default, is_active, description)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, code, name, product, sell_price, currency, is_default, is_active, description, created_at, updated_at
`

type InsertTariffPlanParams struct {
	Code        string          `json:"code"`
	Name        string          `json:"name"`
	Product     BillingProduct  `json:"product"`
	SellPrice   decimal.Decimal `json:"sell_price"`
	Currency    string          `json:"currency"`
	IsDefault   bool            `json:"is_default"`
	IsActive    bool            `json:"is_active"`
	Description *string         `json:"description"`
}

func (q *Queries) InsertTariffPlan(ctx context.Context, arg InsertTariffPlanParams) (TariffPlan, error) {
	row := q.db.QueryRow(ctx, insertTariffPlan,
		arg.Code,
		arg.Name,
		arg.Product,
		arg.SellPrice,
		arg.Currency,
		arg.IsDefault,
		arg.IsActive,
		arg.Description,
	)
	var i TariffPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Product,
		&i.SellPrice,
		&i.Currency,
		&i.IsDefault,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWallet = `-- name: InsertWallet :one
INSERT INTO wallets (client_id, currency)
VALUES ($1, $2)
ON CONFLICT (client_id) DO UPDATE SET client_id = wallets.client_id
RETURNING id, client_id, currency, available_balance, held_balance, version, created_at, updated_at
`

type InsertWalletParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Currency string    `json:"currency"`
}

func (q *Queries) InsertWallet(ctx context.Context, arg InsertWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, insertWallet, arg.ClientID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Currency,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWalletTransaction = `-- name: InsertWalletTransaction :one
INSERT INTO wallet_transactions (
    wallet_id, client_id, type, amount, currency,
    balance_after_available, balance_after_held,
    related_hold_id, sms_message_id, lookup_job_id, lookup_item_id, idempotency_key,
    description, metadata, created_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7,
    $8, $9, $10, $11,
    $12,
    $13, $14, $15
)
RETURNING id, wallet_id, client_id, type, amount, currency, balance_after_available, balance_after_held, related_hold_id, sms_message_id, idempotency_key, description, metadata, created_by, created_at, lookup_job_id, lookup_item_id
`

type InsertWalletTransactionParams struct {
	WalletID              uuid.UUID        `json:"wallet_id"`
	ClientID              uuid.UUID        `json:"client_id"`
	Type                  WalletTxType     `json:"type"`
	Amount                decimal.Decimal  `json:"amount"`
	Currency              string           `json:"currency"`
	BalanceAfterAvailable *decimal.Decimal `json:"balance_after_available"`
	BalanceAfterHeld      *decimal.Decimal `json:"balance_after_held"`
	RelatedHoldID         *uuid.UUID       `json:"related_hold_id"`
	SmsMessageID          *uuid.UUID       `json:"sms_message_id"`
	LookupJobID           *uuid.UUID       `json:"lookup_job_id"`
	LookupItemID          *uuid.UUID       `json:"lookup_item_id"`
	IdempotencyKey        *string          `json:"idempotency_key"`
	Description           *string          `json:"description"`
	Metadata              []byte           `json:"metadata"`
	CreatedBy             *uuid.UUID       `json:"created_by"`
}

func (q *Queries) InsertWalletTransaction(ctx context.Context, arg InsertWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, insertWalletTransaction,
		arg.WalletID,
		arg.ClientID,
		arg.Type,
		arg.Amount,
		arg.Currency,
		arg.BalanceAfterAvailable,
		arg.BalanceAfterHeld,
		arg.RelatedHoldID,
		arg.SmsMessageID,
		arg.LookupJobID,
		arg.LookupItemID,
		arg.IdempotencyKey,
		arg.Description,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.ClientID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.BalanceAfterAvailable,
		&i.BalanceAfterHeld,
		&i.RelatedHoldID,
		&i.SmsMessageID,
		&i.IdempotencyKey,
		&i.Description,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LookupJobID,
		&i.LookupItemID,
	)
	return i, err
}

const listClientTariffs = `-- name: ListClientTariffs :many
SELECT
    a.id,
    a.client_id,
    a.product,
    a.tariff_plan_id,
    a.price_override,
    a.effective_from,
    a.effective_to,
    p.code AS plan_code,
    p.name AS plan_name,
    p.sell_price AS plan_sell_price,
    p.currency,
    p.is_active AS plan_is_active
FROM client_tariffs a
JOIN tariff_plans p ON p.id = a.tariff_plan_id
WHERE a.client_id = $1
ORDER BY a.product
`

type ListClientTariffsRow struct {
	ID            uuid.UUID        `json:"id"`
	ClientID      uuid.UUID        `json:"client_id"`
	Product       BillingProduct   `json:"product"`
	TariffPlanID  uuid.UUID        `json:"tariff_plan_id"`
	PriceOverride *decimal.Decimal `json:"price_override"`
	EffectiveFrom time.Time        `json:"effective_from"`
	EffectiveTo   *time.Time       `json:"effective_to"`
	PlanCode      string           `json:"plan_code"`
	PlanName      string           `json:"plan_name"`
	PlanSellPrice decimal.Decimal  `json:"plan_sell_price"`
	Currency      string           `json:"currency"`
	PlanIsActive  bool             `json:"plan_is_active"`
}

func (q *Queries) ListClientTariffs(ctx context.Context, clientID uuid.UUID) ([]ListClientTariffsRow, error) {
	rows, err := q.db.Query(ctx, listClientTariffs, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientTariffsRow
	for rows.Next() {
		var i ListClientTariffsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Product,
			&i.TariffPlanID,
			&i.PriceOverride,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.PlanCode,
			&i.PlanName,
			&i.PlanSellPrice,
			&i.Currency,
			&i.PlanIsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenHoldMessages = `-- name: ListOpenHoldMessages :many
SELECT
    h.id AS hold_id,
    h.client_id,
    h.sms_message_id,
    h.amount,
    m.status AS message_status,
    m.accepted_at,
    m.billing_action,
    j.status AS job_status
FROM wallet_transactions h
JOIN sms_messages m ON m.id = h.sms_message_id
LEFT JOIN send_jobs j ON j.sms_message_id = m.id
WHERE h.type = 'HOLD'
  AND NOT EXISTS (
      SELECT 1 FROM wallet_transactions s
      WHERE s.related_hold_id = h.id
        AND s.type IN ('DEBIT', 'RELEASE')
  )
ORDER BY h.created_at
LIMIT $1
`

type ListOpenHoldMessagesRow struct {
	HoldID        uuid.UUID         `json:"hold_id"`
	ClientID      uuid.UUID         `json:"client_id"`
	SmsMessageID  *uuid.UUID        `json:"sms_message_id"`
	Amount        decimal.Decimal   `json:"amount"`
	MessageStatus SmsStatus         `json:"message_status"`
	AcceptedAt    *time.Time        `json:"accepted_at"`
	BillingAction NullBillingAction `json:"billing_action"`
	JobStatus     NullSendJobStatus `json:"job_status"`
}

func (q *Queries) ListOpenHoldMessages(ctx context.Context, pageLimit int32) ([]ListOpenHoldMessagesRow, error) {
	rows, err := q.db.Query(ctx, listOpenHoldMessages, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenHoldMessagesRow
	for rows.Next() {
		var i ListOpenHoldMessagesRow
		if err := rows.Scan(
			&i.HoldID,
			&i.ClientID,
			&i.SmsMessageID,
			&i.Amount,
			&i.MessageStatus,
			&i.AcceptedAt,
			&i.BillingAction,
			&i.JobStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformLedger = `-- name: ListPlatformLedger :many
SELECT
    t.id, t.wallet_id, t.client_id, t.type, t.amount, t.currency, t.balance_after_available, t.balance_after_held, t.related_hold_id, t.sms_message_id, t.idempotency_key, t.description, t.metadata, t.created_by, t.created_at, t.lookup_job_id, t.lookup_item_id,
    c.name AS client_name
FROM wallet_transactions t
JOIN clients c ON c.id = t.client_id AND c.status <> 'deleted'
WHERE ($1::uuid IS NULL OR t.client_id = $1)
  AND ($2::wallet_tx_type IS NULL OR t.type = $2)
ORDER BY t.created_at DESC, t.id DESC
LIMIT $4 OFFSET $3
`

type ListPlatformLedgerParams struct {
	ClientID   *uuid.UUID       `json:"client_id"`
	TxType     NullWalletTxType `json:"tx_type"`
	PageOffset int32            `json:"page_offset"`
	PageLimit  int32            `json:"page_limit"`
}

type ListPlatformLedgerRow struct {
	ID                    uuid.UUID        `json:"id"`
	WalletID              uuid.UUID        `json:"wallet_id"`
	ClientID              uuid.UUID        `json:"client_id"`
	Type                  WalletTxType     `json:"type"`
	Amount                decimal.Decimal  `json:"amount"`
	Currency              string           `json:"currency"`
	BalanceAfterAvailable *decimal.Decimal `json:"balance_after_available"`
	BalanceAfterHeld      *decimal.Decimal `json:"balance_after_held"`
	RelatedHoldID         *uuid.UUID       `json:"related_hold_id"`
	SmsMessageID          *uuid.UUID       `json:"sms_message_id"`
	IdempotencyKey        *string          `json:"idempotency_key"`
	Description           *string          `json:"description"`
	Metadata              []byte           `json:"metadata"`
	CreatedBy             *uuid.UUID       `json:"created_by"`
	CreatedAt             time.Time        `json:"created_at"`
	LookupJobID           *uuid.UUID       `json:"lookup_job_id"`
	LookupItemID          *uuid.UUID       `json:"lookup_item_id"`
	ClientName            string           `json:"client_name"`
}

func (q *Queries) ListPlatformLedger(ctx context.Context, arg ListPlatformLedgerParams) ([]ListPlatformLedgerRow, error) {
	rows, err := q.db.Query(ctx, listPlatformLedger,
		arg.ClientID,
		arg.TxType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlatformLedgerRow
	for rows.Next() {
		var i ListPlatformLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.ClientID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.BalanceAfterAvailable,
			&i.BalanceAfterHeld,
			&i.RelatedHoldID,
			&i.SmsMessageID,
			&i.IdempotencyKey,
			&i.Description,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LookupJobID,
			&i.LookupItemID,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTariffPlans = `-- name: ListTariffPlans :many
SELECT id, code, name, product, sell_price, currency, is_default, is_active, description, created_at, updated_at FROM tariff_plans
ORDER BY product, code
LIMIT $2 OFFSET $1
`

type ListTariffPlansParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

func (q *Queries) ListTariffPlans(ctx context.Context, arg ListTariffPlansParams) ([]TariffPlan, error) {
	rows, err := q.db.Query(ctx, listTariffPlans, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TariffPlan
	for rows.Next() {
		var i TariffPlan
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Product,
			&i.SellPrice,
			&i.Currency,
			&i.IsDefault,
			&i.IsActive,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactionsForClient = `-- name: ListWalletTransactionsForClient :many
SELECT id, wallet_id, client_id, type, amount, currency, balance_after_available, balance_after_held, related_hold_id, sms_message_id, idempotency_key, description, metadata, created_by, created_at, lookup_job_id, lookup_item_id FROM wallet_transactions
WHERE client_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListWalletTransactionsForClientParams struct {
	ClientID   uuid.UUID `json:"client_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListWalletTransactionsForClient(ctx context.Context, arg ListWalletTransactionsForClientParams) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactionsForClient, arg.ClientID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletTransaction
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.ClientID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.BalanceAfterAvailable,
			&i.BalanceAfterHeld,
			&i.RelatedHoldID,
			&i.SmsMessageID,
			&i.IdempotencyKey,
			&i.Description,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LookupJobID,
			&i.LookupItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWalletByClientID = `-- name: LockWalletByClientID :one
SELECT id, client_id, currency, available_balance, held_balance, version, created_at, updated_at FROM wallets WHERE client_id = $1 FOR UPDATE
`

func (q *Queries) LockWalletByClientID(ctx context.Context, clientID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, lockWalletByClientID, clientID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Currency,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSmsMessageBillingAction = `-- name: SetSmsMessageBillingAction :one
UPDATE sms_messages
SET billing_action = $1
WHERE id = $2
RETURNING id, client_id, direction, from_msisdn, to_msisdn, text, provider, provider_sms_id, provider_status, pdu_count, campaign_id, status, idempotency_key, created_at, accepted_at, sent_at, delivered_at, failed_at, unit_sell_price, billed_segments, tariff_plan_id, tariff_plan_code, currency, billing_action
`

type SetSmsMessageBillingActionParams struct {
	BillingAction NullBillingAction `json:"billing_action"`
	ID            uuid.UUID         `json:"id"`
}

func (q *Queries) SetSmsMessageBillingAction(ctx context.Context, arg SetSmsMessageBillingActionParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, setSmsMessageBillingAction, arg.BillingAction, arg.ID)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Direction,
		&i.FromMsisdn,
		&i.ToMsisdn,
		&i.Text,
		&i.Provider,
		&i.ProviderSmsID,
		&i.ProviderStatus,
		&i.PduCount,
		&i.CampaignID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UnitSellPrice,
		&i.BilledSegments,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.BillingAction,
	)
	return i, err
}

const sumBilledSegmentsSince = `-- name: SumBilledSegmentsSince :one
SELECT COALESCE(sum(billed_segments), 0)::bigint AS n
FROM sms_messages
WHERE direction = 'outbound'
  AND billed_segments IS NOT NULL
  AND created_at >= $1
`

func (q *Queries) SumBilledSegmentsSince(ctx context.Context, since time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, sumBilledSegmentsSince, since)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const sumDebitsSince = `-- name: SumDebitsSince :one
SELECT COALESCE(sum(amount), 0)::billing_money AS spent
FROM wallet_transactions
WHERE type = 'DEBIT'
  AND created_at >= $1
`

func (q *Queries) SumDebitsSince(ctx context.Context, since time.Time) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, sumDebitsSince, since)
	var spent decimal.Decimal
	err := row.Scan(&spent)
	return spent, err
}

const sumDebitsSinceForClient = `-- name: SumDebitsSinceForClient :one
SELECT COALESCE(sum(amount), 0)::billing_money AS spent
FROM wallet_transactions
WHERE type = 'DEBIT'
  AND client_id = $1
  AND created_at >= $2
`

type SumDebitsSinceForClientParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Since    time.Time `json:"since"`
}

func (q *Queries) SumDebitsSinceForClient(ctx context.Context, arg SumDebitsSinceForClientParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, sumDebitsSinceForClient, arg.ClientID, arg.Since)
	var spent decimal.Decimal
	err := row.Scan(&spent)
	return spent, err
}

const sumWalletBalances = `-- name: SumWalletBalances :one
SELECT
    COALESCE(sum(available_balance), 0)::billing_money AS available_total,
    COALESCE(sum(held_balance), 0)::billing_money AS held_total
FROM wallets w
JOIN clients c ON c.id = w.client_id AND c.status = 'active'
`

type SumWalletBalancesRow struct {
	AvailableTotal decimal.Decimal `json:"available_total"`
	HeldTotal      decimal.Decimal `json:"held_total"`
}

func (q *Queries) SumWalletBalances(ctx context.Context) (SumWalletBalancesRow, error) {
	row := q.db.QueryRow(ctx, sumWalletBalances)
	var i SumWalletBalancesRow
	err := row.Scan(&i.AvailableTotal, &i.HeldTotal)
	return i, err
}

const updateTariffPlan = `-- name: UpdateTariffPlan :one
UPDATE tariff_plans
SET
    name = $1,
    sell_price = $2,
    is_default = $3,
    is_active = $4,
    description = $5,
    updated_at = now()
WHERE id = $6
RETURNING id, code, name, product, sell_price, currency, is_default, is_active, description, created_at, updated_at
`

type UpdateTariffPlanParams struct {
	Name        string          `json:"name"`
	SellPrice   decimal.Decimal `json:"sell_price"`
	IsDefault   bool            `json:"is_default"`
	IsActive    bool            `json:"is_active"`
	Description *string         `json:"description"`
	ID          uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateTariffPlan(ctx context.Context, arg UpdateTariffPlanParams) (TariffPlan, error) {
	row := q.db.QueryRow(ctx, updateTariffPlan,
		arg.Name,
		arg.SellPrice,
		arg.IsDefault,
		arg.IsActive,
		arg.Description,
		arg.ID,
	)
	var i TariffPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Product,
		&i.SellPrice,
		&i.Currency,
		&i.IsDefault,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWalletBalances = `-- name: UpdateWalletBalances :one
UPDATE wallets
SET
    available_balance = $1,
    held_balance = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $3 AND version = $4
RETURNING id, client_id, currency, available_balance, held_balance, version, created_at, updated_at
`

type UpdateWalletBalancesParams struct {
	AvailableBalance decimal.Decimal `json:"available_balance"`
	HeldBalance      decimal.Decimal `json:"held_balance"`
	ID               uuid.UUID       `json:"id"`
	Version          int32           `json:"version"`
}

func (q *Queries) UpdateWalletBalances(ctx context.Context, arg UpdateWalletBalancesParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWalletBalances,
		arg.AvailableBalance,
		arg.HeldBalance,
		arg.ID,
		arg.Version,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Currency,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertClientTariff = `-- name: UpsertClientTariff :one
INSERT INTO client_tariffs (client_id, product, tariff_plan_id, price_override, effective_from, effective_to)
VALUES (
    $1, $2, $3,
    $4, now(), $5
)
ON CONFLICT (client_id, product) DO UPDATE SET
    tariff_plan_id = EXCLUDED.tariff_plan_id,
    price_override = EXCLUDED.price_override,
    effective_from = now(),
    effective_to = EXCLUDED.effective_to,
    updated_at = now()
RETURNING id, client_id, product, tariff_plan_id, price_override, effective_from, effective_to, created_at, updated_at
`

type UpsertClientTariffParams struct {
	ClientID      uuid.UUID        `json:"client_id"`
	Product       BillingProduct   `json:"product"`
	TariffPlanID  uuid.UUID        `json:"tariff_plan_id"`
	PriceOverride *decimal.Decimal `json:"price_override"`
	EffectiveTo   *time.Time       `json:"effective_to"`
}

func (q *Queries) UpsertClientTariff(ctx context.Context, arg UpsertClientTariffParams) (ClientTariff, error) {
	row := q.db.QueryRow(ctx, upsertClientTariff,
		arg.ClientID,
		arg.Product,
		arg.TariffPlanID,
		arg.PriceOverride,
		arg.EffectiveTo,
	)
	var i ClientTariff
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Product,
		&i.TariffPlanID,
		&i.PriceOverride,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
