// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const campaignRecipientStats = `-- name: CampaignRecipientStats :one
SELECT
    COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE status = 'pending')::int AS pending,
    COUNT(*) FILTER (WHERE status = 'enqueued')::int AS enqueued,
    COUNT(*) FILTER (WHERE status = 'skipped')::int AS skipped,
    COUNT(*) FILTER (WHERE status = 'failed')::int AS failed
FROM campaign_recipients
WHERE campaign_id = $1
`

type CampaignRecipientStatsRow struct {
	Total    int32 `json:"total"`
	Pending  int32 `json:"pending"`
	Enqueued int32 `json:"enqueued"`
	Skipped  int32 `json:"skipped"`
	Failed   int32 `json:"failed"`
}

func (q *Queries) CampaignRecipientStats(ctx context.Context, campaignID uuid.UUID) (CampaignRecipientStatsRow, error) {
	row := q.db.QueryRow(ctx, campaignRecipientStats, campaignID)
	var i CampaignRecipientStatsRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Enqueued,
		&i.Skipped,
		&i.Failed,
	)
	return i, err
}

const campaignRunnableForFanout = `-- name: CampaignRunnableForFanout :one
SELECT
    (c.status = 'running')::bool AS running,
    EXISTS (
        SELECT 1
        FROM def_numbers n
        JOIN number_assignments a ON a.def_number_id = n.id AND a.unassigned_at IS NULL
        WHERE n.msisdn = c.from_msisdn
          AND a.client_id = c.client_id
          AND n.status = 'assigned'
    )::bool AS assigned
FROM sms_campaigns c
WHERE c.id = $1
`

type CampaignRunnableForFanoutRow struct {
	Running  bool `json:"running"`
	Assigned bool `json:"assigned"`
}

func (q *Queries) CampaignRunnableForFanout(ctx context.Context, id uuid.UUID) (CampaignRunnableForFanoutRow, error) {
	row := q.db.QueryRow(ctx, campaignRunnableForFanout, id)
	var i CampaignRunnableForFanoutRow
	err := row.Scan(&i.Running, &i.Assigned)
	return i, err
}

const cancelCampaign = `-- name: CancelCampaign :one
UPDATE sms_campaigns
SET status = 'cancelled', updated_at = now()
WHERE id = $1
  AND client_id = $2::uuid
  AND status IN ('queued', 'running')
RETURNING id, client_id, from_msisdn, text, status, total_count, accepted_count, delivered_count, failed_count, created_by, created_at, updated_at
`

type CancelCampaignParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) CancelCampaign(ctx context.Context, arg CancelCampaignParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, cancelCampaign, arg.ID, arg.ClientID)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.FromMsisdn,
		&i.Text,
		&i.Status,
		&i.TotalCount,
		&i.AcceptedCount,
		&i.DeliveredCount,
		&i.FailedCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimQueuedCampaigns = `-- name: ClaimQueuedCampaigns :many
UPDATE sms_campaigns
SET status = 'running', updated_at = now()
WHERE id IN (
    SELECT id
    FROM sms_campaigns
    WHERE status = 'queued'
    ORDER BY created_at, id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, client_id, from_msisdn, text, status, total_count, accepted_count, delivered_count, failed_count, created_by, created_at, updated_at
`

func (q *Queries) ClaimQueuedCampaigns(ctx context.Context, batchLimit int32) ([]SmsCampaign, error) {
	rows, err := q.db.Query(ctx, claimQueuedCampaigns, batchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmsCampaign
	for rows.Next() {
		var i SmsCampaign
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.FromMsisdn,
			&i.Text,
			&i.Status,
			&i.TotalCount,
			&i.AcceptedCount,
			&i.DeliveredCount,
			&i.FailedCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeIdleCampaigns = `-- name: CompleteIdleCampaigns :execrows
UPDATE sms_campaigns c
SET status = 'completed', updated_at = now()
WHERE c.status = 'running'
  AND NOT EXISTS (
      SELECT 1 FROM campaign_recipients r
      WHERE r.campaign_id = c.id AND r.status = 'pending'
  )
  AND NOT EXISTS (
      SELECT 1
      FROM sms_messages m
      JOIN send_jobs j ON j.sms_message_id = m.id
      WHERE m.campaign_id = c.id
        AND j.status IN ('pending', 'processing', 'retry', 'uncertain')
  )
`

func (q *Queries) CompleteIdleCampaigns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, completeIdleCampaigns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCampaignRecipients = `-- name: CountCampaignRecipients :one
SELECT COUNT(*)::int AS n FROM campaign_recipients WHERE campaign_id = $1
`

func (q *Queries) CountCampaignRecipients(ctx context.Context, campaignID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCampaignRecipients, campaignID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const deleteCampaignDraft = `-- name: DeleteCampaignDraft :execrows
DELETE FROM sms_campaigns
WHERE id = $1
  AND client_id = $2::uuid
  AND status = 'draft'
`

type DeleteCampaignDraftParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) DeleteCampaignDraft(ctx context.Context, arg DeleteCampaignDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCampaignDraft, arg.ID, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, client_id, from_msisdn, text, status, total_count, accepted_count, delivered_count, failed_count, created_by, created_at, updated_at FROM sms_campaigns WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id uuid.UUID) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.FromMsisdn,
		&i.Text,
		&i.Status,
		&i.TotalCount,
		&i.AcceptedCount,
		&i.DeliveredCount,
		&i.FailedCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignForClient = `-- name: GetCampaignForClient :one
SELECT id, client_id, from_msisdn, text, status, total_count, accepted_count, delivered_count, failed_count, created_by, created_at, updated_at FROM sms_campaigns
WHERE id = $1 AND client_id = $2::uuid
`

type GetCampaignForClientParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) GetCampaignForClient(ctx context.Context, arg GetCampaignForClientParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, getCampaignForClient, arg.ID, arg.ClientID)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.FromMsisdn,
		&i.Text,
		&i.Status,
		&i.TotalCount,
		&i.AcceptedCount,
		&i.DeliveredCount,
		&i.FailedCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignForClientForUpdate = `-- name: GetCampaignForClientForUpdate :one
SELECT id, client_id, from_msisdn, text, status, total_count, accepted_count, delivered_count, failed_count, created_by, created_at, updated_at FROM sms_campaigns
WHERE id = $1 AND client_id = $2::uuid
FOR UPDATE
`

type GetCampaignForClientForUpdateParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) GetCampaignForClientForUpdate(ctx context.Context, arg GetCampaignForClientForUpdateParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, getCampaignForClientForUpdate, arg.ID, arg.ClientID)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.FromMsisdn,
		&i.Text,
		&i.Status,
		&i.TotalCount,
		&i.AcceptedCount,
		&i.DeliveredCount,
		&i.FailedCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCampaign = `-- name: InsertCampaign :one
INSERT INTO sms_campaigns (client_id, from_msisdn, text, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, client_id, from_msisdn, text, status, total_count, accepted_count, delivered_count, failed_count, created_by, created_at, updated_at
`

type InsertCampaignParams struct {
	ClientID   uuid.UUID  `json:"client_id"`
	FromMsisdn string     `json:"from_msisdn"`
	Text       string     `json:"text"`
	CreatedBy  *uuid.UUID `json:"created_by"`
}

func (q *Queries) InsertCampaign(ctx context.Context, arg InsertCampaignParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, insertCampaign,
		arg.ClientID,
		arg.FromMsisdn,
		arg.Text,
		arg.CreatedBy,
	)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.FromMsisdn,
		&i.Text,
		&i.Status,
		&i.TotalCount,
		&i.AcceptedCount,
		&i.DeliveredCount,
		&i.FailedCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCampaignRecipients = `-- name: InsertCampaignRecipients :execrows
INSERT INTO campaign_recipients (campaign_id, to_msisdn)
SELECT $1, x
FROM unnest($2::text[]) AS x
ON CONFLICT (campaign_id, to_msisdn) DO NOTHING
`

type InsertCampaignRecipientsParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	Msisdns    []string  `json:"msisdns"`
}

func (q *Queries) InsertCampaignRecipients(ctx context.Context, arg InsertCampaignRecipientsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCampaignRecipients, arg.CampaignID, arg.Msisdns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCampaignRecipientMSISDNs = `-- name: ListCampaignRecipientMSISDNs :many
SELECT to_msisdn FROM campaign_recipients WHERE campaign_id = $1
`

func (q *Queries) ListCampaignRecipientMSISDNs(ctx context.Context, campaignID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listCampaignRecipientMSISDNs, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var to_msisdn string
		if err := rows.Scan(&to_msisdn); err != nil {
			return nil, err
		}
		items = append(items, to_msisdn)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignRecipientRows = `-- name: ListCampaignRecipientRows :many
SELECT
    r.id,
    r.campaign_id,
    r.to_msisdn,
    r.status,
    r.sms_message_id,
    r.created_at,
    m.status AS message_status
FROM campaign_recipients r
LEFT JOIN sms_messages m ON m.id = r.sms_message_id
WHERE r.campaign_id = $1
ORDER BY r.created_at, r.id
LIMIT $3 OFFSET $2
`

type ListCampaignRecipientRowsParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type ListCampaignRecipientRowsRow struct {
	ID            uuid.UUID               `json:"id"`
	CampaignID    uuid.UUID               `json:"campaign_id"`
	ToMsisdn      string                  `json:"to_msisdn"`
	Status        CampaignRecipientStatus `json:"status"`
	SmsMessageID  *uuid.UUID              `json:"sms_message_id"`
	CreatedAt     time.Time               `json:"created_at"`
	MessageStatus NullSmsStatus           `json:"message_status"`
}

func (q *Queries) ListCampaignRecipientRows(ctx context.Context, arg ListCampaignRecipientRowsParams) ([]ListCampaignRecipientRowsRow, error) {
	rows, err := q.db.Query(ctx, listCampaignRecipientRows, arg.CampaignID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignRecipientRowsRow
	for rows.Next() {
		var i ListCampaignRecipientRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ToMsisdn,
			&i.Status,
			&i.SmsMessageID,
			&i.CreatedAt,
			&i.MessageStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignRecipients = `-- name: ListCampaignRecipients :many
SELECT id, campaign_id, to_msisdn, status, sms_message_id, created_at FROM campaign_recipients
WHERE campaign_id = $1
ORDER BY created_at, id
LIMIT $3 OFFSET $2
`

type ListCampaignRecipientsParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListCampaignRecipients(ctx context.Context, arg ListCampaignRecipientsParams) ([]CampaignRecipient, error) {
	rows, err := q.db.Query(ctx, listCampaignRecipients, arg.CampaignID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignRecipient
	for rows.Next() {
		var i CampaignRecipient
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ToMsisdn,
			&i.Status,
			&i.SmsMessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsForClient = `-- name: ListCampaignsForClient :many
SELECT id, client_id, from_msisdn, text, status, total_count, accepted_count, delivered_count, failed_count, created_by, created_at, updated_at FROM sms_campaigns
WHERE client_id = $1::uuid
  AND ($2::campaign_status IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListCampaignsForClientParams struct {
	ClientID   uuid.UUID          `json:"client_id"`
	Status     NullCampaignStatus `json:"status"`
	PageOffset int32              `json:"page_offset"`
	PageLimit  int32              `json:"page_limit"`
}

func (q *Queries) ListCampaignsForClient(ctx context.Context, arg ListCampaignsForClientParams) ([]SmsCampaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsForClient,
		arg.ClientID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmsCampaign
	for rows.Next() {
		var i SmsCampaign
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.FromMsisdn,
			&i.Text,
			&i.Status,
			&i.TotalCount,
			&i.AcceptedCount,
			&i.DeliveredCount,
			&i.FailedCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFanoutClientIDs = `-- name: ListFanoutClientIDs :many
SELECT c.client_id
FROM campaign_recipients r
JOIN sms_campaigns c ON c.id = r.campaign_id
WHERE r.status = 'pending' AND c.status = 'running'
GROUP BY c.client_id
ORDER BY MIN(r.created_at)
LIMIT $1
`

func (q *Queries) ListFanoutClientIDs(ctx context.Context, clientLimit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFanoutClientIDs, clientLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var client_id uuid.UUID
		if err := rows.Scan(&client_id); err != nil {
			return nil, err
		}
		items = append(items, client_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPendingRecipientsForClient = `-- name: LockPendingRecipientsForClient :many
SELECT
    r.id,
    r.campaign_id,
    r.to_msisdn,
    r.status,
    r.sms_message_id,
    r.created_at,
    c.client_id,
    c.from_msisdn,
    c.text,
    c.status AS campaign_status
FROM campaign_recipients r
INNER JOIN sms_campaigns c ON c.id = r.campaign_id
WHERE c.client_id = $1
  AND r.status = 'pending'
  AND c.status = 'running'
ORDER BY r.created_at, r.id
LIMIT $2
FOR UPDATE OF r SKIP LOCKED
`

type LockPendingRecipientsForClientParams struct {
	ClientID  uuid.UUID `json:"client_id"`
	PerClient int32     `json:"per_client"`
}

type LockPendingRecipientsForClientRow struct {
	ID             uuid.UUID               `json:"id"`
	CampaignID     uuid.UUID               `json:"campaign_id"`
	ToMsisdn       string                  `json:"to_msisdn"`
	Status         CampaignRecipientStatus `json:"status"`
	SmsMessageID   *uuid.UUID              `json:"sms_message_id"`
	CreatedAt      time.Time               `json:"created_at"`
	ClientID       uuid.UUID               `json:"client_id"`
	FromMsisdn     string                  `json:"from_msisdn"`
	Text           string                  `json:"text"`
	CampaignStatus CampaignStatus          `json:"campaign_status"`
}

func (q *Queries) LockPendingRecipientsForClient(ctx context.Context, arg LockPendingRecipientsForClientParams) ([]LockPendingRecipientsForClientRow, error) {
	rows, err := q.db.Query(ctx, lockPendingRecipientsForClient, arg.ClientID, arg.PerClient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockPendingRecipientsForClientRow
	for rows.Next() {
		var i LockPendingRecipientsForClientRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ToMsisdn,
			&i.Status,
			&i.SmsMessageID,
			&i.CreatedAt,
			&i.ClientID,
			&i.FromMsisdn,
			&i.Text,
			&i.CampaignStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecipientEnqueued = `-- name: MarkRecipientEnqueued :exec
UPDATE campaign_recipients
SET status = 'enqueued', sms_message_id = $1
WHERE id = $2 AND status = 'pending'
`

type MarkRecipientEnqueuedParams struct {
	SmsMessageID *uuid.UUID `json:"sms_message_id"`
	ID           uuid.UUID  `json:"id"`
}

func (q *Queries) MarkRecipientEnqueued(ctx context.Context, arg MarkRecipientEnqueuedParams) error {
	_, err := q.db.Exec(ctx, markRecipientEnqueued, arg.SmsMessageID, arg.ID)
	return err
}

const markRecipientFailed = `-- name: MarkRecipientFailed :exec
UPDATE campaign_recipients
SET status = 'failed'
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkRecipientFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRecipientFailed, id)
	return err
}

const markRecipientSkipped = `-- name: MarkRecipientSkipped :exec
UPDATE campaign_recipients
SET status = 'skipped'
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkRecipientSkipped(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRecipientSkipped, id)
	return err
}

const queueCampaign = `-- name: QueueCampaign :one
UPDATE sms_campaigns
SET status = 'queued', updated_at = now()
WHERE id = $1
  AND client_id = $2::uuid
  AND status = 'draft'
  AND total_count > 0
RETURNING id, client_id, from_msisdn, text, status, total_count, accepted_count, delivered_count, failed_count, created_by, created_at, updated_at
`

type QueueCampaignParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) QueueCampaign(ctx context.Context, arg QueueCampaignParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, queueCampaign, arg.ID, arg.ClientID)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.FromMsisdn,
		&i.Text,
		&i.Status,
		&i.TotalCount,
		&i.AcceptedCount,
		&i.DeliveredCount,
		&i.FailedCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const refreshCampaignCounters = `-- name: RefreshCampaignCounters :exec
UPDATE sms_campaigns c
SET
    accepted_count = COALESCE(s.accepted, 0),
    delivered_count = COALESCE(s.delivered, 0),
    failed_count = COALESCE(s.failed, 0),
    updated_at = now()
FROM (
    SELECT
        m.campaign_id,
        COUNT(*) FILTER (WHERE m.status IN ('accepted', 'sent', 'delivered'))::int AS accepted,
        COUNT(*) FILTER (WHERE m.status = 'delivered')::int AS delivered,
        COUNT(*) FILTER (WHERE m.status = 'failed')::int AS failed
    FROM sms_messages m
    WHERE m.campaign_id IS NOT NULL
    GROUP BY m.campaign_id
) s
WHERE c.id = s.campaign_id
  AND (
      c.status IN ('running', 'cancelled')
      OR (c.status = 'completed' AND c.updated_at > $1)
  )
`

func (q *Queries) RefreshCampaignCounters(ctx context.Context, since time.Time) error {
	_, err := q.db.Exec(ctx, refreshCampaignCounters, since)
	return err
}

const setCampaignTotal = `-- name: SetCampaignTotal :exec
UPDATE sms_campaigns
SET total_count = $1, updated_at = now()
WHERE id = $2
`

type SetCampaignTotalParams struct {
	TotalCount int32     `json:"total_count"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) SetCampaignTotal(ctx context.Context, arg SetCampaignTotalParams) error {
	_, err := q.db.Exec(ctx, setCampaignTotal, arg.TotalCount, arg.ID)
	return err
}

const skipPendingForCampaign = `-- name: SkipPendingForCampaign :execrows
UPDATE campaign_recipients AS r
SET status = 'skipped'
FROM (
    SELECT cr.id
    FROM campaign_recipients cr
    WHERE cr.campaign_id = $1 AND cr.status = 'pending'
    FOR UPDATE SKIP LOCKED
) AS s
WHERE r.id = s.id AND r.status = 'pending'
`

func (q *Queries) SkipPendingForCampaign(ctx context.Context, campaignID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, skipPendingForCampaign, campaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const skipPendingForCancelledCampaigns = `-- name: SkipPendingForCancelledCampaigns :execrows
UPDATE campaign_recipients AS r
SET status = 'skipped'
FROM (
    SELECT r2.id
    FROM campaign_recipients r2
    JOIN sms_campaigns c ON c.id = r2.campaign_id
    WHERE r2.status = 'pending' AND c.status = 'cancelled'
    FOR UPDATE OF r2 SKIP LOCKED
) AS s
WHERE r.id = s.id AND r.status = 'pending'
`

func (q *Queries) SkipPendingForCancelledCampaigns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, skipPendingForCancelledCampaigns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCampaignDraft = `-- name: UpdateCampaignDraft :one
UPDATE sms_campaigns
SET
    from_msisdn = COALESCE($1, from_msisdn),
    text = COALESCE($2, text),
    updated_at = now()
WHERE id = $3
  AND client_id = $4::uuid
  AND status = 'draft'
RETURNING id, client_id, from_msisdn, text, status, total_count, accepted_count, delivered_count, failed_count, created_by, created_at, updated_at
`

type UpdateCampaignDraftParams struct {
	FromMsisdn *string   `json:"from_msisdn"`
	Text       *string   `json:"text"`
	ID         uuid.UUID `json:"id"`
	ClientID   uuid.UUID `json:"client_id"`
}

func (q *Queries) UpdateCampaignDraft(ctx context.Context, arg UpdateCampaignDraftParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignDraft,
		arg.FromMsisdn,
		arg.Text,
		arg.ID,
		arg.ClientID,
	)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.FromMsisdn,
		&i.Text,
		&i.Status,
		&i.TotalCount,
		&i.AcceptedCount,
		&i.DeliveredCount,
		&i.FailedCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
