// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_purge.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const advisoryUnlockClientPurge = `-- name: AdvisoryUnlockClientPurge :one
SELECT pg_advisory_unlock($1::integer, $2::integer) AS unlocked
`

type AdvisoryUnlockClientPurgeParams struct {
	Key1 int32 `json:"key1"`
	Key2 int32 `json:"key2"`
}

func (q *Queries) AdvisoryUnlockClientPurge(ctx context.Context, arg AdvisoryUnlockClientPurgeParams) (bool, error) {
	row := q.db.QueryRow(ctx, advisoryUnlockClientPurge, arg.Key1, arg.Key2)
	var unlocked bool
	err := row.Scan(&unlocked)
	return unlocked, err
}

const cancelOpenCampaignsForClient = `-- name: CancelOpenCampaignsForClient :execrows
UPDATE sms_campaigns
SET status = 'cancelled', updated_at = now()
WHERE client_id = $1
  AND status IN ('queued', 'running')
`

func (q *Queries) CancelOpenCampaignsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelOpenCampaignsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearClientPurgedAt = `-- name: ClearClientPurgedAt :exec
UPDATE clients
SET purged_at = NULL, updated_at = now()
WHERE id = $1 AND status = 'deleted' AND purged_at IS NOT NULL
`

func (q *Queries) ClearClientPurgedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearClientPurgedAt, id)
	return err
}

const clientHasPurgeLeftover = `-- name: ClientHasPurgeLeftover :one
SELECT (
    EXISTS (SELECT 1 FROM webhook_deliveries d WHERE d.client_id = $1)
    OR EXISTS (SELECT 1 FROM webhook_endpoints e WHERE e.client_id = $1)
    OR EXISTS (SELECT 1 FROM provider_lookup_callbacks c WHERE c.client_id = $1)
    OR EXISTS (
        SELECT 1 FROM provider_lookup_callbacks c
        JOIN lookup_items i ON i.id = c.job_item_id
        WHERE i.client_id = $1
    )
    OR EXISTS (SELECT 1 FROM provider_lookup_requests r WHERE r.client_id = $1)
    OR EXISTS (
        SELECT 1 FROM provider_lookup_requests r
        JOIN lookup_items i ON i.id = r.job_item_id
        WHERE i.client_id = $1
    )
    OR EXISTS (SELECT 1 FROM lookup_csv_previews p WHERE p.client_id = $1)
    OR EXISTS (SELECT 1 FROM wallet_transactions t WHERE t.client_id = $1)
    OR EXISTS (SELECT 1 FROM lookup_items i WHERE i.client_id = $1)
    OR EXISTS (SELECT 1 FROM lookup_jobs j WHERE j.client_id = $1)
    OR EXISTS (SELECT 1 FROM send_jobs j WHERE j.client_id = $1)
    OR EXISTS (
        SELECT 1 FROM send_jobs j
        JOIN sms_messages m ON m.id = j.sms_message_id
        WHERE m.client_id = $1
    )
    OR EXISTS (
        SELECT 1 FROM provider_callback_events e
        JOIN sms_messages m ON m.id = e.sms_message_id
        WHERE m.client_id = $1
    )
    OR EXISTS (SELECT 1 FROM sms_messages m WHERE m.client_id = $1)
    OR EXISTS (SELECT 1 FROM sms_campaigns c WHERE c.client_id = $1)
    OR EXISTS (SELECT 1 FROM client_tariffs t WHERE t.client_id = $1)
    OR EXISTS (SELECT 1 FROM wallets w WHERE w.client_id = $1)
    OR EXISTS (SELECT 1 FROM number_assignments a WHERE a.client_id = $1)
    OR EXISTS (SELECT 1 FROM api_credentials k WHERE k.client_id = $1)
    OR EXISTS (SELECT 1 FROM client_users u WHERE u.client_id = $1)
    OR EXISTS (
        SELECT 1 FROM audit_log a
        WHERE (
                a.client_id = $1
                OR a.actor_id IN (SELECT u.id FROM client_users u WHERE u.client_id = $1)
            )
          AND NOT (a.action = 'client.delete' AND a.client_id = $1)
    )
    OR EXISTS (
        SELECT 1 FROM ops_events e
        WHERE e.client_id = $1
           OR e.actor_id IN (SELECT u.id FROM client_users u WHERE u.client_id = $1)
    )
    OR EXISTS (
        SELECT 1 FROM sessions s
        JOIN client_users u ON u.id = s.client_user_id
        WHERE u.client_id = $1
    )
    OR EXISTS (
        SELECT 1 FROM idempotency_keys k
        WHERE k.principal_id IN (
            SELECT u.id FROM client_users u WHERE u.client_id = $1
            UNION ALL
            SELECT cr.id FROM api_credentials cr WHERE cr.client_id = $1
        )
    )
)::bool AS leftover
`

func (q *Queries) ClientHasPurgeLeftover(ctx context.Context, cid uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, clientHasPurgeLeftover, cid)
	var leftover bool
	err := row.Scan(&leftover)
	return leftover, err
}

const disableWebhookEndpointsForClient = `-- name: DisableWebhookEndpointsForClient :execrows
UPDATE webhook_endpoints
SET enabled = false, updated_at = now()
WHERE client_id = $1 AND enabled
`

func (q *Queries) DisableWebhookEndpointsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, disableWebhookEndpointsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listClientsPendingPurge = `-- name: ListClientsPendingPurge :many
SELECT id
FROM clients
WHERE status = 'deleted' AND purged_at IS NULL
ORDER BY updated_at
LIMIT $1
`

func (q *Queries) ListClientsPendingPurge(ctx context.Context, pageLimit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listClientsPendingPurge, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurgedDeletedClientIDs = `-- name: ListPurgedDeletedClientIDs :many
SELECT id
FROM clients
WHERE status = 'deleted' AND purged_at IS NOT NULL
ORDER BY updated_at
LIMIT $1
`

func (q *Queries) ListPurgedDeletedClientIDs(ctx context.Context, pageLimit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPurgedDeletedClientIDs, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markClientDeleted = `-- name: MarkClientDeleted :one
UPDATE clients
SET status = 'deleted',
    name = 'deleted',
    purged_at = NULL,
    updated_at = now()
WHERE id = $1 AND status <> 'deleted'
RETURNING id, name, status, created_at, updated_at, purged_at
`

func (q *Queries) MarkClientDeleted(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, markClientDeleted, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PurgedAt,
	)
	return i, err
}

const markClientPurged = `-- name: MarkClientPurged :exec
UPDATE clients
SET purged_at = now(), updated_at = now()
WHERE id = $1 AND status = 'deleted' AND purged_at IS NULL
`

func (q *Queries) MarkClientPurged(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markClientPurged, id)
	return err
}

const purgeAPICredentialsForClient = `-- name: PurgeAPICredentialsForClient :execrows
DELETE FROM api_credentials WHERE client_id = $1
`

func (q *Queries) PurgeAPICredentialsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAPICredentialsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeAuditLogForClient = `-- name: PurgeAuditLogForClient :execrows
DELETE FROM audit_log
WHERE id IN (
    SELECT a.id
    FROM audit_log a
    WHERE (
            a.client_id = $1
            OR a.actor_id IN (SELECT id FROM client_users WHERE client_id = $1)
        )
      AND NOT (a.action = 'client.delete' AND a.client_id = $1)
    LIMIT 1000
)
`

func (q *Queries) PurgeAuditLogForClient(ctx context.Context, cid *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAuditLogForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeCallbackEventsForClientMessages = `-- name: PurgeCallbackEventsForClientMessages :execrows
DELETE FROM provider_callback_events
WHERE id IN (
    SELECT e.id
    FROM provider_callback_events e
    JOIN sms_messages m ON m.id = e.sms_message_id
    WHERE m.client_id = $1
    LIMIT 500
)
`

func (q *Queries) PurgeCallbackEventsForClientMessages(ctx context.Context, cid *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeCallbackEventsForClientMessages, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeClientTariffsForClient = `-- name: PurgeClientTariffsForClient :execrows
DELETE FROM client_tariffs WHERE client_id = $1
`

func (q *Queries) PurgeClientTariffsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeClientTariffsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeClientUsersForClient = `-- name: PurgeClientUsersForClient :execrows
DELETE FROM client_users WHERE client_id = $1
`

func (q *Queries) PurgeClientUsersForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeClientUsersForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeIdempotencyForClient = `-- name: PurgeIdempotencyForClient :execrows
DELETE FROM idempotency_keys
WHERE principal_id IN (
    SELECT u.id FROM client_users u WHERE u.client_id = $1
    UNION ALL
    SELECT cr.id FROM api_credentials cr WHERE cr.client_id = $1
)
`

func (q *Queries) PurgeIdempotencyForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeIdempotencyForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeLookupCSVPreviewsForClient = `-- name: PurgeLookupCSVPreviewsForClient :execrows
DELETE FROM lookup_csv_previews
WHERE id IN (
    SELECT p.id FROM lookup_csv_previews p
    WHERE p.client_id = $1
    LIMIT 200
)
`

func (q *Queries) PurgeLookupCSVPreviewsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeLookupCSVPreviewsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeLookupItemsForClient = `-- name: PurgeLookupItemsForClient :execrows
DELETE FROM lookup_items
WHERE id IN (
    SELECT i.id FROM lookup_items i
    WHERE i.client_id = $1
    LIMIT 500
)
`

func (q *Queries) PurgeLookupItemsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeLookupItemsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeLookupJobsForClient = `-- name: PurgeLookupJobsForClient :execrows
DELETE FROM lookup_jobs
WHERE id IN (
    SELECT j.id FROM lookup_jobs j
    WHERE j.client_id = $1
    LIMIT 100
)
`

func (q *Queries) PurgeLookupJobsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeLookupJobsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeNumberAssignmentsForClient = `-- name: PurgeNumberAssignmentsForClient :execrows
DELETE FROM number_assignments WHERE client_id = $1
`

func (q *Queries) PurgeNumberAssignmentsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeNumberAssignmentsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeOpsEventsForClient = `-- name: PurgeOpsEventsForClient :execrows
DELETE FROM ops_events
WHERE id IN (
    SELECT e.id
    FROM ops_events e
    WHERE e.client_id = $1
       OR e.actor_id IN (SELECT id FROM client_users WHERE client_id = $1)
    LIMIT 1000
)
`

func (q *Queries) PurgeOpsEventsForClient(ctx context.Context, cid *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOpsEventsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeProviderLookupCallbacksForClient = `-- name: PurgeProviderLookupCallbacksForClient :execrows
DELETE FROM provider_lookup_callbacks
WHERE id IN (
    SELECT c.id
    FROM provider_lookup_callbacks c
    WHERE c.client_id = $1
       OR c.job_item_id IN (SELECT id FROM lookup_items WHERE client_id = $1)
    LIMIT 500
)
`

func (q *Queries) PurgeProviderLookupCallbacksForClient(ctx context.Context, cid *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeProviderLookupCallbacksForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeProviderLookupRequestsForClient = `-- name: PurgeProviderLookupRequestsForClient :execrows
DELETE FROM provider_lookup_requests
WHERE id IN (
    SELECT r.id
    FROM provider_lookup_requests r
    WHERE r.client_id = $1
       OR r.job_item_id IN (SELECT id FROM lookup_items WHERE client_id = $1)
    LIMIT 500
)
`

func (q *Queries) PurgeProviderLookupRequestsForClient(ctx context.Context, cid *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeProviderLookupRequestsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeSendJobsForClient = `-- name: PurgeSendJobsForClient :execrows
WITH doomed AS (
    SELECT j.id
    FROM send_jobs j
    WHERE j.client_id = $1
       OR j.sms_message_id IN (SELECT id FROM sms_messages WHERE client_id = $1)
    LIMIT 200
),
del_attempts AS (
    DELETE FROM provider_send_attempts
    WHERE send_job_id IN (SELECT id FROM doomed)
)
DELETE FROM send_jobs
WHERE id IN (SELECT id FROM doomed)
`

func (q *Queries) PurgeSendJobsForClient(ctx context.Context, cid *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeSendJobsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeSessionsForClient = `-- name: PurgeSessionsForClient :execrows
DELETE FROM sessions
WHERE client_user_id IN (SELECT id FROM client_users WHERE client_id = $1)
`

func (q *Queries) PurgeSessionsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeSessionsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeSmsCampaignsForClient = `-- name: PurgeSmsCampaignsForClient :execrows
DELETE FROM sms_campaigns
WHERE id IN (
    SELECT c.id FROM sms_campaigns c
    WHERE c.client_id = $1
    LIMIT 100
)
`

func (q *Queries) PurgeSmsCampaignsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeSmsCampaignsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeSmsMessagesForClient = `-- name: PurgeSmsMessagesForClient :execrows
DELETE FROM sms_messages
WHERE id IN (
    SELECT m.id FROM sms_messages m
    WHERE m.client_id = $1
    LIMIT 200
)
`

func (q *Queries) PurgeSmsMessagesForClient(ctx context.Context, cid *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeSmsMessagesForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeWalletTransactionsForClient = `-- name: PurgeWalletTransactionsForClient :execrows
DELETE FROM wallet_transactions
WHERE id IN (
    SELECT t.id FROM wallet_transactions t
    WHERE t.client_id = $1
    LIMIT 500
)
`

func (q *Queries) PurgeWalletTransactionsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeWalletTransactionsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeWalletsForClient = `-- name: PurgeWalletsForClient :execrows
DELETE FROM wallets WHERE client_id = $1
`

func (q *Queries) PurgeWalletsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeWalletsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeWebhookDeliveriesForClient = `-- name: PurgeWebhookDeliveriesForClient :execrows
DELETE FROM webhook_deliveries
WHERE id IN (
    SELECT d.id FROM webhook_deliveries d
    WHERE d.client_id = $1
    LIMIT 500
)
`

func (q *Queries) PurgeWebhookDeliveriesForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeWebhookDeliveriesForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeWebhookEndpointsForClient = `-- name: PurgeWebhookEndpointsForClient :execrows
DELETE FROM webhook_endpoints
WHERE id IN (
    SELECT e.id FROM webhook_endpoints e
    WHERE e.client_id = $1
    LIMIT 100
)
`

func (q *Queries) PurgeWebhookEndpointsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeWebhookEndpointsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrambleClientUsersForDelete = `-- name: ScrambleClientUsersForDelete :execrows
UPDATE client_users
SET email = 'deleted-' || id::text || '@invalid',
    name = '',
    status = 'disabled',
    updated_at = now()
WHERE client_id = $1
  AND email NOT LIKE 'deleted-%@invalid'
`

func (q *Queries) ScrambleClientUsersForDelete(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, scrambleClientUsersForDelete, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryAdvisoryLockClientPurge = `-- name: TryAdvisoryLockClientPurge :one
SELECT pg_try_advisory_lock($1::integer, $2::integer) AS locked
`

type TryAdvisoryLockClientPurgeParams struct {
	Key1 int32 `json:"key1"`
	Key2 int32 `json:"key2"`
}

func (q *Queries) TryAdvisoryLockClientPurge(ctx context.Context, arg TryAdvisoryLockClientPurgeParams) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryLockClientPurge, arg.Key1, arg.Key2)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}

const unlinkCampaignRecipientsForClient = `-- name: UnlinkCampaignRecipientsForClient :execrows
UPDATE campaign_recipients
SET sms_message_id = NULL
WHERE sms_message_id IN (
    SELECT id FROM sms_messages WHERE client_id = $1
)
`

func (q *Queries) UnlinkCampaignRecipientsForClient(ctx context.Context, cid *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkCampaignRecipientsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlinkDirectionJobsForClient = `-- name: UnlinkDirectionJobsForClient :execrows
UPDATE number_direction_jobs
SET assignment_id = NULL
WHERE assignment_id IN (
    SELECT id FROM number_assignments WHERE client_id = $1
)
`

func (q *Queries) UnlinkDirectionJobsForClient(ctx context.Context, cid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkDirectionJobsForClient, cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
