// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_users.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const getClientUserByEmail = `-- name: GetClientUserByEmail :one
SELECT id, client_id, email, password_hash, role, status, created_at, updated_at FROM client_users WHERE LOWER(email) = LOWER($1) LIMIT 1
`

func (q *Queries) GetClientUserByEmail(ctx context.Context, email string) (ClientUser, error) {
	row := q.db.QueryRow(ctx, getClientUserByEmail, email)
	var i ClientUser
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientUserByID = `-- name: GetClientUserByID :one
SELECT id, client_id, email, password_hash, role, status, created_at, updated_at FROM client_users WHERE id = $1
`

func (q *Queries) GetClientUserByID(ctx context.Context, id uuid.UUID) (ClientUser, error) {
	row := q.db.QueryRow(ctx, getClientUserByID, id)
	var i ClientUser
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnerByClientID = `-- name: GetOwnerByClientID :one
SELECT id, client_id, email, password_hash, role, status, created_at, updated_at FROM client_users
WHERE client_id = $1 AND role = 'owner'
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetOwnerByClientID(ctx context.Context, clientID uuid.UUID) (ClientUser, error) {
	row := q.db.QueryRow(ctx, getOwnerByClientID, clientID)
	var i ClientUser
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertClientUser = `-- name: InsertClientUser :one
INSERT INTO client_users (client_id, email, password_hash, role, status)
VALUES ($1, $2, $3, 'owner', 'active')
RETURNING id, client_id, email, password_hash, role, status, created_at, updated_at
`

type InsertClientUserParams struct {
	ClientID     uuid.UUID `json:"client_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) InsertClientUser(ctx context.Context, arg InsertClientUserParams) (ClientUser, error) {
	row := q.db.QueryRow(ctx, insertClientUser, arg.ClientID, arg.Email, arg.PasswordHash)
	var i ClientUser
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClientUsersByClientID = `-- name: ListClientUsersByClientID :many
SELECT id, client_id, email, password_hash, role, status, created_at, updated_at FROM client_users
WHERE client_id = $1
ORDER BY created_at
`

func (q *Queries) ListClientUsersByClientID(ctx context.Context, clientID uuid.UUID) ([]ClientUser, error) {
	rows, err := q.db.Query(ctx, listClientUsersByClientID, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientUser
	for rows.Next() {
		var i ClientUser
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientUserPassword = `-- name: UpdateClientUserPassword :exec
UPDATE client_users
SET password_hash = $1, updated_at = now()
WHERE id = $2
`

type UpdateClientUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateClientUserPassword(ctx context.Context, arg UpdateClientUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateClientUserPassword, arg.PasswordHash, arg.ID)
	return err
}
