// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getClientByID = `-- name: GetClientByID :one
SELECT id, name, status, created_at, updated_at FROM clients WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByIDForUpdate = `-- name: GetClientByIDForUpdate :one
SELECT id, name, status, created_at, updated_at FROM clients WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetClientByIDForUpdate(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByIDForUpdate, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertClient = `-- name: InsertClient :one
INSERT INTO clients (name, status)
VALUES ($1, 'active')
RETURNING id, name, status, created_at, updated_at
`

func (q *Queries) InsertClient(ctx context.Context, name string) (Client, error) {
	row := q.db.QueryRow(ctx, insertClient, name)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT
    c.id,
    c.name,
    c.status,
    c.created_at,
    c.updated_at,
    COALESCE(ou.email, '') AS owner_email,
    (
        SELECT count(*)::bigint
        FROM number_assignments a
        WHERE a.client_id = c.id AND a.unassigned_at IS NULL
    ) AS assigned_count,
    w.available_balance,
    w.held_balance,
    w.currency AS wallet_currency
FROM clients c
LEFT JOIN wallets w ON w.client_id = c.id
LEFT JOIN LATERAL (
    SELECT email
    FROM client_users
    WHERE client_id = c.id AND role = 'owner'
    ORDER BY created_at
    LIMIT 1
) ou ON true
WHERE c.status <> 'deleted'
  AND ($1::client_status IS NULL OR c.status = $1)
ORDER BY c.created_at DESC
LIMIT $3 OFFSET $2
`

type ListClientsParams struct {
	Status     NullClientStatus `json:"status"`
	PageOffset int32            `json:"page_offset"`
	PageLimit  int32            `json:"page_limit"`
}

type ListClientsRow struct {
	ID               uuid.UUID        `json:"id"`
	Name             string           `json:"name"`
	Status           ClientStatus     `json:"status"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
	OwnerEmail       string           `json:"owner_email"`
	AssignedCount    int64            `json:"assigned_count"`
	AvailableBalance *decimal.Decimal `json:"available_balance"`
	HeldBalance      *decimal.Decimal `json:"held_balance"`
	WalletCurrency   *string          `json:"wallet_currency"`
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]ListClientsRow, error) {
	rows, err := q.db.Query(ctx, listClients, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientsRow
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerEmail,
			&i.AssignedCount,
			&i.AvailableBalance,
			&i.HeldBalance,
			&i.WalletCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClientStatus = `-- name: SetClientStatus :one
UPDATE clients
SET status = $1, updated_at = now()
WHERE id = $2 AND status <> 'deleted'
RETURNING id, name, status, created_at, updated_at
`

type SetClientStatusParams struct {
	Status ClientStatus `json:"status"`
	ID     uuid.UUID    `json:"id"`
}

func (q *Queries) SetClientStatus(ctx context.Context, arg SetClientStatusParams) (Client, error) {
	row := q.db.QueryRow(ctx, setClientStatus, arg.Status, arg.ID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClientName = `-- name: UpdateClientName :one
UPDATE clients
SET name = $1, updated_at = now()
WHERE id = $2 AND status <> 'deleted'
RETURNING id, name, status, created_at, updated_at
`

type UpdateClientNameParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateClientName(ctx context.Context, arg UpdateClientNameParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClientName, arg.Name, arg.ID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
