// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlcdb

import (
	"context"
)

// iteratorForInsertLookupItems implements pgx.CopyFromSource.
type iteratorForInsertLookupItems struct {
	rows                 []InsertLookupItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertLookupItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertLookupItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].JobID,
		r.rows[0].ClientID,
		r.rows[0].CheckType,
		r.rows[0].PhoneE164,
		r.rows[0].PhoneDigits,
		r.rows[0].UnitSellPrice,
		r.rows[0].TariffPlanID,
		r.rows[0].TariffPlanCode,
		r.rows[0].Currency,
		r.rows[0].EstimatedCost,
	}, nil
}

func (r iteratorForInsertLookupItems) Err() error {
	return nil
}

func (q *Queries) InsertLookupItems(ctx context.Context, arg []InsertLookupItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"lookup_items"}, []string{"job_id", "client_id", "check_type", "phone_e164", "phone_digits", "unit_sell_price", "tariff_plan_id", "tariff_plan_code", "currency", "estimated_cost"}, &iteratorForInsertLookupItems{rows: arg})
}
