// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :one
UPDATE idempotency_keys
SET response_status = $1,
    response_body = $2
WHERE id = $3
  AND response_status IS NULL
RETURNING id, principal_type, principal_id, key, request_hash, response_status, response_body, expires_at, created_at
`

type CompleteIdempotencyKeyParams struct {
	ResponseStatus *int32    `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyKey, arg.ResponseStatus, arg.ResponseBody, arg.ID)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKeyForUpdate = `-- name: GetIdempotencyKeyForUpdate :one
SELECT id, principal_type, principal_id, key, request_hash, response_status, response_body, expires_at, created_at FROM idempotency_keys
WHERE principal_type = $1
  AND principal_id = $2
  AND key = $3
FOR UPDATE
`

type GetIdempotencyKeyForUpdateParams struct {
	PrincipalType ActorType `json:"principal_type"`
	PrincipalID   uuid.UUID `json:"principal_id"`
	Key           string    `json:"key"`
}

func (q *Queries) GetIdempotencyKeyForUpdate(ctx context.Context, arg GetIdempotencyKeyForUpdateParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKeyForUpdate, arg.PrincipalType, arg.PrincipalID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (
    principal_type, principal_id, key, request_hash, expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (principal_type, principal_id, key) DO NOTHING
RETURNING id, principal_type, principal_id, key, request_hash, response_status, response_body, expires_at, created_at
`

type InsertIdempotencyKeyParams struct {
	PrincipalType ActorType `json:"principal_type"`
	PrincipalID   uuid.UUID `json:"principal_id"`
	Key           string    `json:"key"`
	RequestHash   string    `json:"request_hash"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Key,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
