// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingress.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getCallbackEventByID = `-- name: GetCallbackEventByID :one
SELECT id, kind, idempotency_key, method, path, query, headers, raw_body, content_type, parsed, sms_message_id, processed_at, created_at FROM provider_callback_events WHERE id = $1
`

func (q *Queries) GetCallbackEventByID(ctx context.Context, id uuid.UUID) (ProviderCallbackEvent, error) {
	row := q.db.QueryRow(ctx, getCallbackEventByID, id)
	var i ProviderCallbackEvent
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.IdempotencyKey,
		&i.Method,
		&i.Path,
		&i.Query,
		&i.Headers,
		&i.RawBody,
		&i.ContentType,
		&i.Parsed,
		&i.SmsMessageID,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertCallbackEvent = `-- name: InsertCallbackEvent :one
INSERT INTO provider_callback_events (
    kind, idempotency_key, method, path, query, headers, raw_body, content_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, kind, idempotency_key, method, path, query, headers, raw_body, content_type, parsed, sms_message_id, processed_at, created_at
`

type InsertCallbackEventParams struct {
	Kind           CallbackKind `json:"kind"`
	IdempotencyKey string       `json:"idempotency_key"`
	Method         string       `json:"method"`
	Path           string       `json:"path"`
	Query          *string      `json:"query"`
	Headers        []byte       `json:"headers"`
	RawBody        []byte       `json:"raw_body"`
	ContentType    *string      `json:"content_type"`
}

func (q *Queries) InsertCallbackEvent(ctx context.Context, arg InsertCallbackEventParams) (ProviderCallbackEvent, error) {
	row := q.db.QueryRow(ctx, insertCallbackEvent,
		arg.Kind,
		arg.IdempotencyKey,
		arg.Method,
		arg.Path,
		arg.Query,
		arg.Headers,
		arg.RawBody,
		arg.ContentType,
	)
	var i ProviderCallbackEvent
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.IdempotencyKey,
		&i.Method,
		&i.Path,
		&i.Query,
		&i.Headers,
		&i.RawBody,
		&i.ContentType,
		&i.Parsed,
		&i.SmsMessageID,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCallbackEvents = `-- name: ListCallbackEvents :many
SELECT
    id, kind, idempotency_key, method, path, query, content_type,
    octet_length(raw_body) AS body_bytes, created_at, processed_at
FROM provider_callback_events
WHERE ($1::callback_kind IS NULL OR kind = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListCallbackEventsParams struct {
	Kind       NullCallbackKind `json:"kind"`
	PageOffset int32            `json:"page_offset"`
	PageLimit  int32            `json:"page_limit"`
}

type ListCallbackEventsRow struct {
	ID             uuid.UUID    `json:"id"`
	Kind           CallbackKind `json:"kind"`
	IdempotencyKey string       `json:"idempotency_key"`
	Method         string       `json:"method"`
	Path           string       `json:"path"`
	Query          *string      `json:"query"`
	ContentType    *string      `json:"content_type"`
	BodyBytes      int32        `json:"body_bytes"`
	CreatedAt      time.Time    `json:"created_at"`
	ProcessedAt    *time.Time   `json:"processed_at"`
}

func (q *Queries) ListCallbackEvents(ctx context.Context, arg ListCallbackEventsParams) ([]ListCallbackEventsRow, error) {
	rows, err := q.db.Query(ctx, listCallbackEvents, arg.Kind, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCallbackEventsRow
	for rows.Next() {
		var i ListCallbackEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.IdempotencyKey,
			&i.Method,
			&i.Path,
			&i.Query,
			&i.ContentType,
			&i.BodyBytes,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedCallbackEvents = `-- name: ListUnprocessedCallbackEvents :many
SELECT id, kind, idempotency_key, method, path, query, headers, raw_body, content_type, parsed, sms_message_id, processed_at, created_at
FROM provider_callback_events
WHERE processed_at IS NULL
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListUnprocessedCallbackEvents(ctx context.Context, pageLimit int32) ([]ProviderCallbackEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedCallbackEvents, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderCallbackEvent
	for rows.Next() {
		var i ProviderCallbackEvent
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.IdempotencyKey,
			&i.Method,
			&i.Path,
			&i.Query,
			&i.Headers,
			&i.RawBody,
			&i.ContentType,
			&i.Parsed,
			&i.SmsMessageID,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCallbackProcessed = `-- name: MarkCallbackProcessed :execrows
UPDATE provider_callback_events
SET processed_at = now(),
    parsed = $1,
    sms_message_id = $2
WHERE id = $3
  AND processed_at IS NULL
`

type MarkCallbackProcessedParams struct {
	Parsed       []byte     `json:"parsed"`
	SmsMessageID *uuid.UUID `json:"sms_message_id"`
	ID           uuid.UUID  `json:"id"`
}

func (q *Queries) MarkCallbackProcessed(ctx context.Context, arg MarkCallbackProcessedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCallbackProcessed, arg.Parsed, arg.SmsMessageID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
