// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimDirectionJobs = `-- name: ClaimDirectionJobs :many
UPDATE number_direction_jobs
SET status = 'processing',
    locked_at = now(),
    locked_by = $1,
    updated_at = now()
WHERE id IN (
    SELECT id FROM number_direction_jobs
    WHERE status IN ('pending', 'retry')
      AND available_at <= now()
    ORDER BY available_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, def_number_id, assignment_id, msisdn, dir_in, dir_dom_out, dir_int_out, dir_in_mass, status, attempt, available_at, locked_at, locked_by, last_error, created_at, updated_at
`

type ClaimDirectionJobsParams struct {
	WorkerID   *string `json:"worker_id"`
	BatchLimit int32   `json:"batch_limit"`
}

func (q *Queries) ClaimDirectionJobs(ctx context.Context, arg ClaimDirectionJobsParams) ([]NumberDirectionJob, error) {
	rows, err := q.db.Query(ctx, claimDirectionJobs, arg.WorkerID, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NumberDirectionJob
	for rows.Next() {
		var i NumberDirectionJob
		if err := rows.Scan(
			&i.ID,
			&i.DefNumberID,
			&i.AssignmentID,
			&i.Msisdn,
			&i.DirIn,
			&i.DirDomOut,
			&i.DirIntOut,
			&i.DirInMass,
			&i.Status,
			&i.Attempt,
			&i.AvailableAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeAssignment = `-- name: CloseAssignment :one
UPDATE number_assignments
SET unassigned_at = now()
WHERE id = $1 AND unassigned_at IS NULL
RETURNING id, def_number_id, client_id, assigned_at, unassigned_at, assigned_by
`

func (q *Queries) CloseAssignment(ctx context.Context, id uuid.UUID) (NumberAssignment, error) {
	row := q.db.QueryRow(ctx, closeAssignment, id)
	var i NumberAssignment
	err := row.Scan(
		&i.ID,
		&i.DefNumberID,
		&i.ClientID,
		&i.AssignedAt,
		&i.UnassignedAt,
		&i.AssignedBy,
	)
	return i, err
}

const completeDirectionJob = `-- name: CompleteDirectionJob :exec
UPDATE number_direction_jobs
SET status = 'done',
    locked_at = NULL,
    locked_by = NULL,
    last_error = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) CompleteDirectionJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, completeDirectionJob, id)
	return err
}

const deadDirectionJob = `-- name: DeadDirectionJob :exec
UPDATE number_direction_jobs
SET status = 'dead',
    attempt = $1,
    locked_at = NULL,
    locked_by = NULL,
    last_error = $2,
    updated_at = now()
WHERE id = $3
`

type DeadDirectionJobParams struct {
	Attempt   int32     `json:"attempt"`
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) DeadDirectionJob(ctx context.Context, arg DeadDirectionJobParams) error {
	_, err := q.db.Exec(ctx, deadDirectionJob, arg.Attempt, arg.LastError, arg.ID)
	return err
}

const getDefNumberByID = `-- name: GetDefNumberByID :one
SELECT id, msisdn, status, region, notes, supports_sms, runexis_snapshot, created_at, updated_at FROM def_numbers WHERE id = $1
`

func (q *Queries) GetDefNumberByID(ctx context.Context, id uuid.UUID) (DefNumber, error) {
	row := q.db.QueryRow(ctx, getDefNumberByID, id)
	var i DefNumber
	err := row.Scan(
		&i.ID,
		&i.Msisdn,
		&i.Status,
		&i.Region,
		&i.Notes,
		&i.SupportsSms,
		&i.RunexisSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefNumberByIDForUpdate = `-- name: GetDefNumberByIDForUpdate :one
SELECT id, msisdn, status, region, notes, supports_sms, runexis_snapshot, created_at, updated_at FROM def_numbers WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetDefNumberByIDForUpdate(ctx context.Context, id uuid.UUID) (DefNumber, error) {
	row := q.db.QueryRow(ctx, getDefNumberByIDForUpdate, id)
	var i DefNumber
	err := row.Scan(
		&i.ID,
		&i.Msisdn,
		&i.Status,
		&i.Region,
		&i.Notes,
		&i.SupportsSms,
		&i.RunexisSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefNumberByMSISDN = `-- name: GetDefNumberByMSISDN :one
SELECT id, msisdn, status, region, notes, supports_sms, runexis_snapshot, created_at, updated_at FROM def_numbers WHERE msisdn = $1
`

func (q *Queries) GetDefNumberByMSISDN(ctx context.Context, msisdn string) (DefNumber, error) {
	row := q.db.QueryRow(ctx, getDefNumberByMSISDN, msisdn)
	var i DefNumber
	err := row.Scan(
		&i.ID,
		&i.Msisdn,
		&i.Status,
		&i.Region,
		&i.Notes,
		&i.SupportsSms,
		&i.RunexisSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefNumberView = `-- name: GetDefNumberView :one
SELECT
    n.id,
    n.msisdn,
    n.status,
    n.region,
    n.notes,
    n.supports_sms,
    n.created_at,
    n.updated_at,
    a.id AS assignment_id,
    a.client_id,
    a.assigned_at,
    c.name AS client_name
FROM def_numbers n
LEFT JOIN number_assignments a ON a.def_number_id = n.id AND a.unassigned_at IS NULL
LEFT JOIN clients c ON c.id = a.client_id
WHERE n.id = $1
`

type GetDefNumberViewRow struct {
	ID           uuid.UUID       `json:"id"`
	Msisdn       string          `json:"msisdn"`
	Status       DefNumberStatus `json:"status"`
	Region       *string         `json:"region"`
	Notes        *string         `json:"notes"`
	SupportsSms  bool            `json:"supports_sms"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	AssignmentID *uuid.UUID      `json:"assignment_id"`
	ClientID     *uuid.UUID      `json:"client_id"`
	AssignedAt   *time.Time      `json:"assigned_at"`
	ClientName   *string         `json:"client_name"`
}

func (q *Queries) GetDefNumberView(ctx context.Context, id uuid.UUID) (GetDefNumberViewRow, error) {
	row := q.db.QueryRow(ctx, getDefNumberView, id)
	var i GetDefNumberViewRow
	err := row.Scan(
		&i.ID,
		&i.Msisdn,
		&i.Status,
		&i.Region,
		&i.Notes,
		&i.SupportsSms,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentID,
		&i.ClientID,
		&i.AssignedAt,
		&i.ClientName,
	)
	return i, err
}

const getOpenAssignmentByNumber = `-- name: GetOpenAssignmentByNumber :one
SELECT id, def_number_id, client_id, assigned_at, unassigned_at, assigned_by FROM number_assignments
WHERE def_number_id = $1 AND unassigned_at IS NULL
`

func (q *Queries) GetOpenAssignmentByNumber(ctx context.Context, defNumberID uuid.UUID) (NumberAssignment, error) {
	row := q.db.QueryRow(ctx, getOpenAssignmentByNumber, defNumberID)
	var i NumberAssignment
	err := row.Scan(
		&i.ID,
		&i.DefNumberID,
		&i.ClientID,
		&i.AssignedAt,
		&i.UnassignedAt,
		&i.AssignedBy,
	)
	return i, err
}

const insertAssignment = `-- name: InsertAssignment :one
INSERT INTO number_assignments (def_number_id, client_id, assigned_by)
VALUES ($1, $2, $3)
RETURNING id, def_number_id, client_id, assigned_at, unassigned_at, assigned_by
`

type InsertAssignmentParams struct {
	DefNumberID uuid.UUID  `json:"def_number_id"`
	ClientID    uuid.UUID  `json:"client_id"`
	AssignedBy  *uuid.UUID `json:"assigned_by"`
}

func (q *Queries) InsertAssignment(ctx context.Context, arg InsertAssignmentParams) (NumberAssignment, error) {
	row := q.db.QueryRow(ctx, insertAssignment, arg.DefNumberID, arg.ClientID, arg.AssignedBy)
	var i NumberAssignment
	err := row.Scan(
		&i.ID,
		&i.DefNumberID,
		&i.ClientID,
		&i.AssignedAt,
		&i.UnassignedAt,
		&i.AssignedBy,
	)
	return i, err
}

const insertDefNumber = `-- name: InsertDefNumber :one
INSERT INTO def_numbers (msisdn, region, notes)
VALUES ($1, $2, $3)
ON CONFLICT (msisdn) DO NOTHING
RETURNING id, msisdn, status, region, notes, supports_sms, runexis_snapshot, created_at, updated_at
`

type InsertDefNumberParams struct {
	Msisdn string  `json:"msisdn"`
	Region *string `json:"region"`
	Notes  *string `json:"notes"`
}

func (q *Queries) InsertDefNumber(ctx context.Context, arg InsertDefNumberParams) (DefNumber, error) {
	row := q.db.QueryRow(ctx, insertDefNumber, arg.Msisdn, arg.Region, arg.Notes)
	var i DefNumber
	err := row.Scan(
		&i.ID,
		&i.Msisdn,
		&i.Status,
		&i.Region,
		&i.Notes,
		&i.SupportsSms,
		&i.RunexisSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDirectionJob = `-- name: InsertDirectionJob :one
INSERT INTO number_direction_jobs (
    def_number_id, assignment_id, msisdn,
    dir_in, dir_dom_out, dir_int_out, dir_in_mass
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, def_number_id, assignment_id, msisdn, dir_in, dir_dom_out, dir_int_out, dir_in_mass, status, attempt, available_at, locked_at, locked_by, last_error, created_at, updated_at
`

type InsertDirectionJobParams struct {
	DefNumberID  uuid.UUID  `json:"def_number_id"`
	AssignmentID *uuid.UUID `json:"assignment_id"`
	Msisdn       string     `json:"msisdn"`
	DirIn        bool       `json:"dir_in"`
	DirDomOut    bool       `json:"dir_dom_out"`
	DirIntOut    bool       `json:"dir_int_out"`
	DirInMass    bool       `json:"dir_in_mass"`
}

func (q *Queries) InsertDirectionJob(ctx context.Context, arg InsertDirectionJobParams) (NumberDirectionJob, error) {
	row := q.db.QueryRow(ctx, insertDirectionJob,
		arg.DefNumberID,
		arg.AssignmentID,
		arg.Msisdn,
		arg.DirIn,
		arg.DirDomOut,
		arg.DirIntOut,
		arg.DirInMass,
	)
	var i NumberDirectionJob
	err := row.Scan(
		&i.ID,
		&i.DefNumberID,
		&i.AssignmentID,
		&i.Msisdn,
		&i.DirIn,
		&i.DirDomOut,
		&i.DirIntOut,
		&i.DirInMass,
		&i.Status,
		&i.Attempt,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDefNumbers = `-- name: ListDefNumbers :many
SELECT
    n.id,
    n.msisdn,
    n.status,
    n.region,
    n.notes,
    n.supports_sms,
    n.created_at,
    n.updated_at,
    a.id AS assignment_id,
    a.client_id,
    a.assigned_at,
    c.name AS client_name
FROM def_numbers n
LEFT JOIN number_assignments a ON a.def_number_id = n.id AND a.unassigned_at IS NULL
LEFT JOIN clients c ON c.id = a.client_id
WHERE ($1::def_number_status IS NULL OR n.status = $1)
  AND ($2::uuid IS NULL OR a.client_id = $2)
  AND ($3::text IS NULL OR n.msisdn LIKE '%' || $3 || '%')
ORDER BY n.created_at DESC
LIMIT $5 OFFSET $4
`

type ListDefNumbersParams struct {
	Status     NullDefNumberStatus `json:"status"`
	ClientID   *uuid.UUID          `json:"client_id"`
	Q          *string             `json:"q"`
	PageOffset int32               `json:"page_offset"`
	PageLimit  int32               `json:"page_limit"`
}

type ListDefNumbersRow struct {
	ID           uuid.UUID       `json:"id"`
	Msisdn       string          `json:"msisdn"`
	Status       DefNumberStatus `json:"status"`
	Region       *string         `json:"region"`
	Notes        *string         `json:"notes"`
	SupportsSms  bool            `json:"supports_sms"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	AssignmentID *uuid.UUID      `json:"assignment_id"`
	ClientID     *uuid.UUID      `json:"client_id"`
	AssignedAt   *time.Time      `json:"assigned_at"`
	ClientName   *string         `json:"client_name"`
}

func (q *Queries) ListDefNumbers(ctx context.Context, arg ListDefNumbersParams) ([]ListDefNumbersRow, error) {
	rows, err := q.db.Query(ctx, listDefNumbers,
		arg.Status,
		arg.ClientID,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDefNumbersRow
	for rows.Next() {
		var i ListDefNumbersRow
		if err := rows.Scan(
			&i.ID,
			&i.Msisdn,
			&i.Status,
			&i.Region,
			&i.Notes,
			&i.SupportsSms,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignmentID,
			&i.ClientID,
			&i.AssignedAt,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenAssignmentsByClient = `-- name: ListOpenAssignmentsByClient :many
SELECT id, def_number_id, client_id, assigned_at, unassigned_at, assigned_by FROM number_assignments
WHERE client_id = $1 AND unassigned_at IS NULL
FOR UPDATE
`

func (q *Queries) ListOpenAssignmentsByClient(ctx context.Context, clientID uuid.UUID) ([]NumberAssignment, error) {
	rows, err := q.db.Query(ctx, listOpenAssignmentsByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NumberAssignment
	for rows.Next() {
		var i NumberAssignment
		if err := rows.Scan(
			&i.ID,
			&i.DefNumberID,
			&i.ClientID,
			&i.AssignedAt,
			&i.UnassignedAt,
			&i.AssignedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reclaimStaleDirectionJobs = `-- name: ReclaimStaleDirectionJobs :execrows
UPDATE number_direction_jobs
SET status = 'pending',
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
WHERE status = 'processing'
  AND locked_at < $1
`

func (q *Queries) ReclaimStaleDirectionJobs(ctx context.Context, staleBefore *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimStaleDirectionJobs, staleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryDirectionJob = `-- name: RetryDirectionJob :exec
UPDATE number_direction_jobs
SET status = 'retry',
    attempt = $1,
    available_at = $2,
    locked_at = NULL,
    locked_by = NULL,
    last_error = $3,
    updated_at = now()
WHERE id = $4
`

type RetryDirectionJobParams struct {
	Attempt     int32     `json:"attempt"`
	AvailableAt time.Time `json:"available_at"`
	LastError   *string   `json:"last_error"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) RetryDirectionJob(ctx context.Context, arg RetryDirectionJobParams) error {
	_, err := q.db.Exec(ctx, retryDirectionJob,
		arg.Attempt,
		arg.AvailableAt,
		arg.LastError,
		arg.ID,
	)
	return err
}

const setDefNumberSupportsSMSByMSISDN = `-- name: SetDefNumberSupportsSMSByMSISDN :execrows
UPDATE def_numbers
SET supports_sms = $1,
    runexis_snapshot = COALESCE($2, runexis_snapshot),
    updated_at = now()
WHERE msisdn = $3
`

type SetDefNumberSupportsSMSByMSISDNParams struct {
	SupportsSms     bool   `json:"supports_sms"`
	RunexisSnapshot []byte `json:"runexis_snapshot"`
	Msisdn          string `json:"msisdn"`
}

func (q *Queries) SetDefNumberSupportsSMSByMSISDN(ctx context.Context, arg SetDefNumberSupportsSMSByMSISDNParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDefNumberSupportsSMSByMSISDN, arg.SupportsSms, arg.RunexisSnapshot, arg.Msisdn)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDefNumberMeta = `-- name: UpdateDefNumberMeta :one
UPDATE def_numbers
SET region = $1, notes = $2, updated_at = now()
WHERE id = $3
RETURNING id, msisdn, status, region, notes, supports_sms, runexis_snapshot, created_at, updated_at
`

type UpdateDefNumberMetaParams struct {
	Region *string   `json:"region"`
	Notes  *string   `json:"notes"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateDefNumberMeta(ctx context.Context, arg UpdateDefNumberMetaParams) (DefNumber, error) {
	row := q.db.QueryRow(ctx, updateDefNumberMeta, arg.Region, arg.Notes, arg.ID)
	var i DefNumber
	err := row.Scan(
		&i.ID,
		&i.Msisdn,
		&i.Status,
		&i.Region,
		&i.Notes,
		&i.SupportsSms,
		&i.RunexisSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDefNumberStatus = `-- name: UpdateDefNumberStatus :one
UPDATE def_numbers
SET status = $1, updated_at = now()
WHERE id = $2
RETURNING id, msisdn, status, region, notes, supports_sms, runexis_snapshot, created_at, updated_at
`

type UpdateDefNumberStatusParams struct {
	Status DefNumberStatus `json:"status"`
	ID     uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateDefNumberStatus(ctx context.Context, arg UpdateDefNumberStatusParams) (DefNumber, error) {
	row := q.db.QueryRow(ctx, updateDefNumberStatus, arg.Status, arg.ID)
	var i DefNumber
	err := row.Scan(
		&i.ID,
		&i.Msisdn,
		&i.Status,
		&i.Region,
		&i.Notes,
		&i.SupportsSms,
		&i.RunexisSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDefNumberFromSync = `-- name: UpsertDefNumberFromSync :one
INSERT INTO def_numbers (msisdn, region, supports_sms, runexis_snapshot)
VALUES ($1, $2, $3, $4)
ON CONFLICT (msisdn) DO UPDATE SET
    supports_sms = EXCLUDED.supports_sms,
    runexis_snapshot = COALESCE(EXCLUDED.runexis_snapshot, def_numbers.runexis_snapshot),
    region = COALESCE(def_numbers.region, EXCLUDED.region),
    updated_at = now()
RETURNING id, msisdn, status, region, notes, supports_sms, runexis_snapshot, created_at, updated_at
`

type UpsertDefNumberFromSyncParams struct {
	Msisdn          string  `json:"msisdn"`
	Region          *string `json:"region"`
	SupportsSms     bool    `json:"supports_sms"`
	RunexisSnapshot []byte  `json:"runexis_snapshot"`
}

func (q *Queries) UpsertDefNumberFromSync(ctx context.Context, arg UpsertDefNumberFromSyncParams) (DefNumber, error) {
	row := q.db.QueryRow(ctx, upsertDefNumberFromSync,
		arg.Msisdn,
		arg.Region,
		arg.SupportsSms,
		arg.RunexisSnapshot,
	)
	var i DefNumber
	err := row.Scan(
		&i.ID,
		&i.Msisdn,
		&i.Status,
		&i.Region,
		&i.Notes,
		&i.SupportsSms,
		&i.RunexisSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
