// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lookup.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const bumpLookupItemEnrichAttempt = `-- name: BumpLookupItemEnrichAttempt :exec
UPDATE lookup_items
SET enrich_attempts = enrich_attempts + 1,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) BumpLookupItemEnrichAttempt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpLookupItemEnrichAttempt, id)
	return err
}

const claimItemForSubmit = `-- name: ClaimItemForSubmit :one
UPDATE lookup_items
SET status = 'reserved', updated_at = now()
WHERE id = $1
  AND status IN ('queued', 'reserved')
RETURNING id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
`

func (q *Queries) ClaimItemForSubmit(ctx context.Context, id uuid.UUID) (LookupItem, error) {
	row := q.db.QueryRow(ctx, claimItemForSubmit, id)
	var i LookupItem
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ClientID,
		&i.CheckType,
		&i.Status,
		&i.PhoneE164,
		&i.PhoneDigits,
		&i.ProviderCode,
		&i.ProviderMessageID,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.ResultStatus,
		&i.IsReachable,
		&i.Imsi,
		&i.Mcc,
		&i.Mnc,
		&i.OperatorName,
		&i.CountryCode,
		&i.Ported,
		&i.Roaming,
		&i.NormalizedResult,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.BillingAction,
		&i.NextPollAt,
		&i.PollAttempts,
		&i.SentAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrichAttempts,
	)
	return i, err
}

const claimLookupCSVPreviewReady = `-- name: ClaimLookupCSVPreviewReady :one
UPDATE lookup_csv_previews
SET status = 'consuming',
    updated_at = now()
WHERE id = $1
  AND client_id = $2
  AND status = 'ready'
  AND expires_at > now()
RETURNING id, client_id, check_type, status, original_filename, phone_count, phones_json, error_message, job_id, expires_at, created_at, updated_at
`

type ClaimLookupCSVPreviewReadyParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) ClaimLookupCSVPreviewReady(ctx context.Context, arg ClaimLookupCSVPreviewReadyParams) (LookupCsvPreview, error) {
	row := q.db.QueryRow(ctx, claimLookupCSVPreviewReady, arg.ID, arg.ClientID)
	var i LookupCsvPreview
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Status,
		&i.OriginalFilename,
		&i.PhoneCount,
		&i.PhonesJson,
		&i.ErrorMessage,
		&i.JobID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimLookupCSVPreviewsPendingParse = `-- name: ClaimLookupCSVPreviewsPendingParse :many
UPDATE lookup_csv_previews AS p
SET status = 'consuming',
    updated_at = now()
WHERE p.id IN (
    SELECT id
    FROM lookup_csv_previews
    WHERE status = 'ready'
      AND job_id IS NOT NULL
      AND phones_json ? 'raw'
    ORDER BY created_at, id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, client_id, check_type, status, original_filename, phone_count, phones_json, error_message, job_id, expires_at, created_at, updated_at
`

func (q *Queries) ClaimLookupCSVPreviewsPendingParse(ctx context.Context, pageLimit int32) ([]LookupCsvPreview, error) {
	rows, err := q.db.Query(ctx, claimLookupCSVPreviewsPendingParse, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupCsvPreview
	for rows.Next() {
		var i LookupCsvPreview
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.OriginalFilename,
			&i.PhoneCount,
			&i.PhonesJson,
			&i.ErrorMessage,
			&i.JobID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimLookupItemsNeedingHLREnrich = `-- name: ClaimLookupItemsNeedingHLREnrich :many
UPDATE lookup_items AS i
SET updated_at = now()
WHERE i.id IN (
    SELECT e.id
    FROM lookup_items e
    WHERE e.check_type = 'hlr'
      AND e.status IN ('completed', 'failed')
      AND e.provider_message_id IS NOT NULL
      AND e.provider_message_id <> ''
      AND e.enrich_attempts < $1
      AND (
            e.imsi IS NULL OR btrim(e.imsi) = ''
            OR COALESCE(e.normalized_result#>>'{extras,msc}', '') = ''
          )
      AND e.updated_at <= now() - interval '15 seconds'
    ORDER BY e.updated_at, e.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
`

type ClaimLookupItemsNeedingHLREnrichParams struct {
	MaxAttempts int32 `json:"max_attempts"`
	PageLimit   int32 `json:"page_limit"`
}

func (q *Queries) ClaimLookupItemsNeedingHLREnrich(ctx context.Context, arg ClaimLookupItemsNeedingHLREnrichParams) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, claimLookupItemsNeedingHLREnrich, arg.MaxAttempts, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimPendingLookupItemsFair = `-- name: ClaimPendingLookupItemsFair :many
UPDATE lookup_items AS i
SET next_poll_at = now() + interval '120 seconds',
    updated_at = now()
WHERE i.id IN (
    SELECT j.id
    FROM (
        SELECT client_id
        FROM lookup_items
        WHERE status = 'pending'
          AND next_poll_at IS NOT NULL
          AND next_poll_at <= now()
        GROUP BY client_id
        ORDER BY MIN(next_poll_at)
        LIMIT $1
    ) c
    CROSS JOIN LATERAL (
        SELECT id
        FROM lookup_items
        WHERE client_id IS NOT DISTINCT FROM c.client_id
          AND status = 'pending'
          AND next_poll_at IS NOT NULL
          AND next_poll_at <= now()
        ORDER BY next_poll_at, id
        LIMIT $2
        FOR UPDATE SKIP LOCKED
    ) j
)
RETURNING id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
`

type ClaimPendingLookupItemsFairParams struct {
	ClientLimit int32 `json:"client_limit"`
	PerClient   int32 `json:"per_client"`
}

func (q *Queries) ClaimPendingLookupItemsFair(ctx context.Context, arg ClaimPendingLookupItemsFairParams) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, claimPendingLookupItemsFair, arg.ClientLimit, arg.PerClient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimQueuedLookupItemsFair = `-- name: ClaimQueuedLookupItemsFair :many
UPDATE lookup_items AS i
SET status = 'reserved', updated_at = now()
WHERE i.id IN (
    SELECT j.id
    FROM (
        SELECT client_id
        FROM lookup_items
        WHERE status = 'queued'
        GROUP BY client_id
        ORDER BY MIN(created_at)
        LIMIT $1
    ) c
    CROSS JOIN LATERAL (
        SELECT id
        FROM lookup_items
        WHERE client_id IS NOT DISTINCT FROM c.client_id
          AND status = 'queued'
        ORDER BY created_at, id
        LIMIT $2
        FOR UPDATE SKIP LOCKED
    ) j
)
RETURNING id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
`

type ClaimQueuedLookupItemsFairParams struct {
	ClientLimit int32 `json:"client_limit"`
	PerClient   int32 `json:"per_client"`
}

func (q *Queries) ClaimQueuedLookupItemsFair(ctx context.Context, arg ClaimQueuedLookupItemsFairParams) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, claimQueuedLookupItemsFair, arg.ClientLimit, arg.PerClient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimReservedLookupItemsFair = `-- name: ClaimReservedLookupItemsFair :many
UPDATE lookup_items AS i
SET status = status
WHERE i.id IN (
    SELECT j.id
    FROM (
        SELECT client_id
        FROM lookup_items
        WHERE status = 'reserved'
          AND updated_at <= now() - interval '5 seconds'
        GROUP BY client_id
        ORDER BY MIN(updated_at)
        LIMIT $1
    ) c
    CROSS JOIN LATERAL (
        SELECT id
        FROM lookup_items
        WHERE client_id IS NOT DISTINCT FROM c.client_id
          AND status = 'reserved'
          AND updated_at <= now() - interval '5 seconds'
        ORDER BY updated_at, id
        LIMIT $2
        FOR UPDATE SKIP LOCKED
    ) j
)
RETURNING id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
`

type ClaimReservedLookupItemsFairParams struct {
	ClientLimit int32 `json:"client_limit"`
	PerClient   int32 `json:"per_client"`
}

func (q *Queries) ClaimReservedLookupItemsFair(ctx context.Context, arg ClaimReservedLookupItemsFairParams) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, claimReservedLookupItemsFair, arg.ClientLimit, arg.PerClient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLookupItemsByJob = `-- name: CountLookupItemsByJob :one
SELECT count(*)::bigint AS n
FROM lookup_items
WHERE job_id = $1
`

func (q *Queries) CountLookupItemsByJob(ctx context.Context, jobID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLookupItemsByJob, jobID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countLookupItemsForClient = `-- name: CountLookupItemsForClient :one
SELECT count(*)::bigint AS n
FROM lookup_items
WHERE client_id = $1
  AND ($2::lookup_item_status IS NULL OR status = $2)
  AND ($3::lookup_check_type IS NULL OR check_type = $3)
`

type CountLookupItemsForClientParams struct {
	ClientID        uuid.UUID            `json:"client_id"`
	FilterStatus    NullLookupItemStatus `json:"filter_status"`
	FilterCheckType NullLookupCheckType  `json:"filter_check_type"`
}

func (q *Queries) CountLookupItemsForClient(ctx context.Context, arg CountLookupItemsForClientParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLookupItemsForClient, arg.ClientID, arg.FilterStatus, arg.FilterCheckType)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countLookupItemsSinceByStatusForClient = `-- name: CountLookupItemsSinceByStatusForClient :many
SELECT status, count(*)::bigint AS n
FROM lookup_items
WHERE client_id = $1
  AND created_at >= $2
GROUP BY status
`

type CountLookupItemsSinceByStatusForClientParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Since    time.Time `json:"since"`
}

type CountLookupItemsSinceByStatusForClientRow struct {
	Status LookupItemStatus `json:"status"`
	N      int64            `json:"n"`
}

func (q *Queries) CountLookupItemsSinceByStatusForClient(ctx context.Context, arg CountLookupItemsSinceByStatusForClientParams) ([]CountLookupItemsSinceByStatusForClientRow, error) {
	rows, err := q.db.Query(ctx, countLookupItemsSinceByStatusForClient, arg.ClientID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountLookupItemsSinceByStatusForClientRow
	for rows.Next() {
		var i CountLookupItemsSinceByStatusForClientRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLookupItemsSinceByTypeForClient = `-- name: CountLookupItemsSinceByTypeForClient :many
SELECT check_type, count(*)::bigint AS n
FROM lookup_items
WHERE client_id = $1
  AND created_at >= $2
GROUP BY check_type
`

type CountLookupItemsSinceByTypeForClientParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Since    time.Time `json:"since"`
}

type CountLookupItemsSinceByTypeForClientRow struct {
	CheckType LookupCheckType `json:"check_type"`
	N         int64           `json:"n"`
}

func (q *Queries) CountLookupItemsSinceByTypeForClient(ctx context.Context, arg CountLookupItemsSinceByTypeForClientParams) ([]CountLookupItemsSinceByTypeForClientRow, error) {
	rows, err := q.db.Query(ctx, countLookupItemsSinceByTypeForClient, arg.ClientID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountLookupItemsSinceByTypeForClientRow
	for rows.Next() {
		var i CountLookupItemsSinceByTypeForClientRow
		if err := rows.Scan(&i.CheckType, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLookupJobs = `-- name: CountLookupJobs :one
SELECT count(*)::bigint AS n
FROM lookup_jobs
WHERE ($1::uuid IS NULL OR client_id = $1)
  AND ($2::lookup_job_status IS NULL OR status = $2)
  AND ($3::lookup_check_type IS NULL OR check_type = $3)
`

type CountLookupJobsParams struct {
	ClientID        *uuid.UUID          `json:"client_id"`
	FilterStatus    NullLookupJobStatus `json:"filter_status"`
	FilterCheckType NullLookupCheckType `json:"filter_check_type"`
}

func (q *Queries) CountLookupJobs(ctx context.Context, arg CountLookupJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLookupJobs, arg.ClientID, arg.FilterStatus, arg.FilterCheckType)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countProviderLookupCallbacksSince = `-- name: CountProviderLookupCallbacksSince :one
SELECT count(*)::bigint AS n
FROM provider_lookup_callbacks
WHERE created_at >= $1
`

func (q *Queries) CountProviderLookupCallbacksSince(ctx context.Context, since time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderLookupCallbacksSince, since)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countProviderLookupRequestsSince = `-- name: CountProviderLookupRequestsSince :one
SELECT count(*)::bigint AS n
FROM provider_lookup_requests
WHERE created_at >= $1
`

func (q *Queries) CountProviderLookupRequestsSince(ctx context.Context, since time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderLookupRequestsSince, since)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const deleteLookupCSVPreview = `-- name: DeleteLookupCSVPreview :execrows
DELETE FROM lookup_csv_previews
WHERE id = $1
  AND client_id = $2
  AND status IN ('ready', 'invalid', 'expired')
`

type DeleteLookupCSVPreviewParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) DeleteLookupCSVPreview(ctx context.Context, arg DeleteLookupCSVPreviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLookupCSVPreview, arg.ID, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeLookupJob = `-- name: FinalizeLookupJob :one
UPDATE lookup_jobs
SET status = $1,
    error_code = $2,
    error_message = $3,
    completed_at = now(),
    updated_at = now()
WHERE id = $4
  AND status IN ('queued', 'processing')
RETURNING id, client_id, check_type, source, status, item_count, success_count, failure_count, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, original_filename, idempotency_key, created_by, api_credential_id, error_code, error_message, started_at, completed_at, metadata, created_at, updated_at
`

type FinalizeLookupJobParams struct {
	Status       LookupJobStatus `json:"status"`
	ErrorCode    *string         `json:"error_code"`
	ErrorMessage *string         `json:"error_message"`
	ID           uuid.UUID       `json:"id"`
}

func (q *Queries) FinalizeLookupJob(ctx context.Context, arg FinalizeLookupJobParams) (LookupJob, error) {
	row := q.db.QueryRow(ctx, finalizeLookupJob,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	var i LookupJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Source,
		&i.Status,
		&i.ItemCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.OriginalFilename,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.ApiCredentialID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestProviderSendByIdempotency = `-- name: GetLatestProviderSendByIdempotency :one
SELECT id, client_id, job_item_id, provider_code, kind, status, provider_message_id, http_status, error_code, error_message, request_payload, response_payload, normalized_result, idempotency_key, started_at, finished_at, created_at
FROM provider_lookup_requests
WHERE provider_code = $1
  AND idempotency_key = $2
  AND kind = 'send'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetLatestProviderSendByIdempotencyParams struct {
	ProviderCode   string  `json:"provider_code"`
	IdempotencyKey *string `json:"idempotency_key"`
}

func (q *Queries) GetLatestProviderSendByIdempotency(ctx context.Context, arg GetLatestProviderSendByIdempotencyParams) (ProviderLookupRequest, error) {
	row := q.db.QueryRow(ctx, getLatestProviderSendByIdempotency, arg.ProviderCode, arg.IdempotencyKey)
	var i ProviderLookupRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.JobItemID,
		&i.ProviderCode,
		&i.Kind,
		&i.Status,
		&i.ProviderMessageID,
		&i.HttpStatus,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.NormalizedResult,
		&i.IdempotencyKey,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLookupCSVPreviewForClient = `-- name: GetLookupCSVPreviewForClient :one
SELECT id, client_id, check_type, status, original_filename, phone_count, phones_json, error_message, job_id, expires_at, created_at, updated_at
FROM lookup_csv_previews
WHERE id = $1
  AND client_id = $2
`

type GetLookupCSVPreviewForClientParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) GetLookupCSVPreviewForClient(ctx context.Context, arg GetLookupCSVPreviewForClientParams) (LookupCsvPreview, error) {
	row := q.db.QueryRow(ctx, getLookupCSVPreviewForClient, arg.ID, arg.ClientID)
	var i LookupCsvPreview
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Status,
		&i.OriginalFilename,
		&i.PhoneCount,
		&i.PhonesJson,
		&i.ErrorMessage,
		&i.JobID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLookupItemByProviderMessage = `-- name: GetLookupItemByProviderMessage :one
SELECT id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
FROM lookup_items
WHERE provider_code = $1
  AND provider_message_id = $2
`

type GetLookupItemByProviderMessageParams struct {
	ProviderCode      string  `json:"provider_code"`
	ProviderMessageID *string `json:"provider_message_id"`
}

func (q *Queries) GetLookupItemByProviderMessage(ctx context.Context, arg GetLookupItemByProviderMessageParams) (LookupItem, error) {
	row := q.db.QueryRow(ctx, getLookupItemByProviderMessage, arg.ProviderCode, arg.ProviderMessageID)
	var i LookupItem
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ClientID,
		&i.CheckType,
		&i.Status,
		&i.PhoneE164,
		&i.PhoneDigits,
		&i.ProviderCode,
		&i.ProviderMessageID,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.ResultStatus,
		&i.IsReachable,
		&i.Imsi,
		&i.Mcc,
		&i.Mnc,
		&i.OperatorName,
		&i.CountryCode,
		&i.Ported,
		&i.Roaming,
		&i.NormalizedResult,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.BillingAction,
		&i.NextPollAt,
		&i.PollAttempts,
		&i.SentAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrichAttempts,
	)
	return i, err
}

const getLookupItemForClient = `-- name: GetLookupItemForClient :one
SELECT id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
FROM lookup_items
WHERE id = $1
  AND client_id = $2
`

type GetLookupItemForClientParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) GetLookupItemForClient(ctx context.Context, arg GetLookupItemForClientParams) (LookupItem, error) {
	row := q.db.QueryRow(ctx, getLookupItemForClient, arg.ID, arg.ClientID)
	var i LookupItem
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ClientID,
		&i.CheckType,
		&i.Status,
		&i.PhoneE164,
		&i.PhoneDigits,
		&i.ProviderCode,
		&i.ProviderMessageID,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.ResultStatus,
		&i.IsReachable,
		&i.Imsi,
		&i.Mcc,
		&i.Mnc,
		&i.OperatorName,
		&i.CountryCode,
		&i.Ported,
		&i.Roaming,
		&i.NormalizedResult,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.BillingAction,
		&i.NextPollAt,
		&i.PollAttempts,
		&i.SentAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrichAttempts,
	)
	return i, err
}

const getLookupJobByCSVPreview = `-- name: GetLookupJobByCSVPreview :one
SELECT id, client_id, check_type, source, status, item_count, success_count, failure_count, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, original_filename, idempotency_key, created_by, api_credential_id, error_code, error_message, started_at, completed_at, metadata, created_at, updated_at
FROM lookup_jobs
WHERE client_id = $1
  AND metadata->>'csv_preview_id' = $2::text
ORDER BY created_at
LIMIT 1
`

type GetLookupJobByCSVPreviewParams struct {
	ClientID  uuid.UUID `json:"client_id"`
	PreviewID string    `json:"preview_id"`
}

func (q *Queries) GetLookupJobByCSVPreview(ctx context.Context, arg GetLookupJobByCSVPreviewParams) (LookupJob, error) {
	row := q.db.QueryRow(ctx, getLookupJobByCSVPreview, arg.ClientID, arg.PreviewID)
	var i LookupJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Source,
		&i.Status,
		&i.ItemCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.OriginalFilename,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.ApiCredentialID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLookupJobByIdempotency = `-- name: GetLookupJobByIdempotency :one
SELECT id, client_id, check_type, source, status, item_count, success_count, failure_count, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, original_filename, idempotency_key, created_by, api_credential_id, error_code, error_message, started_at, completed_at, metadata, created_at, updated_at
FROM lookup_jobs
WHERE client_id = $1
  AND idempotency_key = $2
`

type GetLookupJobByIdempotencyParams struct {
	ClientID       uuid.UUID `json:"client_id"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

func (q *Queries) GetLookupJobByIdempotency(ctx context.Context, arg GetLookupJobByIdempotencyParams) (LookupJob, error) {
	row := q.db.QueryRow(ctx, getLookupJobByIdempotency, arg.ClientID, arg.IdempotencyKey)
	var i LookupJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Source,
		&i.Status,
		&i.ItemCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.OriginalFilename,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.ApiCredentialID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLookupJobForClient = `-- name: GetLookupJobForClient :one
SELECT id, client_id, check_type, source, status, item_count, success_count, failure_count, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, original_filename, idempotency_key, created_by, api_credential_id, error_code, error_message, started_at, completed_at, metadata, created_at, updated_at
FROM lookup_jobs
WHERE id = $1
  AND client_id = $2
`

type GetLookupJobForClientParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) GetLookupJobForClient(ctx context.Context, arg GetLookupJobForClientParams) (LookupJob, error) {
	row := q.db.QueryRow(ctx, getLookupJobForClient, arg.ID, arg.ClientID)
	var i LookupJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Source,
		&i.Status,
		&i.ItemCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.OriginalFilename,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.ApiCredentialID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderLookupCallbackByDedupe = `-- name: GetProviderLookupCallbackByDedupe :one
SELECT id, client_id, job_item_id, provider_code, provider_message_id, raw_payload, normalized_result, dedupe_key, signature_valid, processed_at, process_error, created_at
FROM provider_lookup_callbacks
WHERE provider_code = $1
  AND dedupe_key = $2
`

type GetProviderLookupCallbackByDedupeParams struct {
	ProviderCode string  `json:"provider_code"`
	DedupeKey    *string `json:"dedupe_key"`
}

func (q *Queries) GetProviderLookupCallbackByDedupe(ctx context.Context, arg GetProviderLookupCallbackByDedupeParams) (ProviderLookupCallback, error) {
	row := q.db.QueryRow(ctx, getProviderLookupCallbackByDedupe, arg.ProviderCode, arg.DedupeKey)
	var i ProviderLookupCallback
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.JobItemID,
		&i.ProviderCode,
		&i.ProviderMessageID,
		&i.RawPayload,
		&i.NormalizedResult,
		&i.DedupeKey,
		&i.SignatureValid,
		&i.ProcessedAt,
		&i.ProcessError,
		&i.CreatedAt,
	)
	return i, err
}

const getSucceededProviderSendByIdempotency = `-- name: GetSucceededProviderSendByIdempotency :one
SELECT id, client_id, job_item_id, provider_code, kind, status, provider_message_id, http_status, error_code, error_message, request_payload, response_payload, normalized_result, idempotency_key, started_at, finished_at, created_at
FROM provider_lookup_requests
WHERE provider_code = $1
  AND idempotency_key = $2
  AND kind = 'send'
  AND status = 'succeeded'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetSucceededProviderSendByIdempotencyParams struct {
	ProviderCode   string  `json:"provider_code"`
	IdempotencyKey *string `json:"idempotency_key"`
}

func (q *Queries) GetSucceededProviderSendByIdempotency(ctx context.Context, arg GetSucceededProviderSendByIdempotencyParams) (ProviderLookupRequest, error) {
	row := q.db.QueryRow(ctx, getSucceededProviderSendByIdempotency, arg.ProviderCode, arg.IdempotencyKey)
	var i ProviderLookupRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.JobItemID,
		&i.ProviderCode,
		&i.Kind,
		&i.Status,
		&i.ProviderMessageID,
		&i.HttpStatus,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.NormalizedResult,
		&i.IdempotencyKey,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const healStaleConsumingLookupCSVPreviews = `-- name: HealStaleConsumingLookupCSVPreviews :execrows
UPDATE lookup_csv_previews
SET status = CASE
        WHEN job_id IS NOT NULL AND NOT (phones_json ? 'raw') THEN 'consumed'::lookup_csv_preview_status
        ELSE 'ready'::lookup_csv_preview_status
    END,
    updated_at = now()
WHERE status = 'consuming'
  AND updated_at <= $1
`

func (q *Queries) HealStaleConsumingLookupCSVPreviews(ctx context.Context, olderThan time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, healStaleConsumingLookupCSVPreviews, olderThan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertLookupCSVPreview = `-- name: InsertLookupCSVPreview :one
INSERT INTO lookup_csv_previews (
    client_id,
    check_type,
    status,
    original_filename,
    phone_count,
    phones_json,
    job_id,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, client_id, check_type, status, original_filename, phone_count, phones_json, error_message, job_id, expires_at, created_at, updated_at
`

type InsertLookupCSVPreviewParams struct {
	ClientID         uuid.UUID              `json:"client_id"`
	CheckType        LookupCheckType        `json:"check_type"`
	Status           LookupCsvPreviewStatus `json:"status"`
	OriginalFilename *string                `json:"original_filename"`
	PhoneCount       int32                  `json:"phone_count"`
	PhonesJson       []byte                 `json:"phones_json"`
	JobID            *uuid.UUID             `json:"job_id"`
	ExpiresAt        time.Time              `json:"expires_at"`
}

func (q *Queries) InsertLookupCSVPreview(ctx context.Context, arg InsertLookupCSVPreviewParams) (LookupCsvPreview, error) {
	row := q.db.QueryRow(ctx, insertLookupCSVPreview,
		arg.ClientID,
		arg.CheckType,
		arg.Status,
		arg.OriginalFilename,
		arg.PhoneCount,
		arg.PhonesJson,
		arg.JobID,
		arg.ExpiresAt,
	)
	var i LookupCsvPreview
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Status,
		&i.OriginalFilename,
		&i.PhoneCount,
		&i.PhonesJson,
		&i.ErrorMessage,
		&i.JobID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type InsertLookupItemsParams struct {
	JobID          uuid.UUID        `json:"job_id"`
	ClientID       uuid.UUID        `json:"client_id"`
	CheckType      LookupCheckType  `json:"check_type"`
	PhoneE164      string           `json:"phone_e164"`
	PhoneDigits    string           `json:"phone_digits"`
	UnitSellPrice  *decimal.Decimal `json:"unit_sell_price"`
	TariffPlanID   *uuid.UUID       `json:"tariff_plan_id"`
	TariffPlanCode *string          `json:"tariff_plan_code"`
	Currency       *string          `json:"currency"`
	EstimatedCost  *decimal.Decimal `json:"estimated_cost"`
}

const insertLookupJob = `-- name: InsertLookupJob :one
INSERT INTO lookup_jobs (
    client_id,
    check_type,
    source,
    status,
    item_count,
    unit_sell_price,
    tariff_plan_id,
    tariff_plan_code,
    currency,
    estimated_cost,
    original_filename,
    idempotency_key,
    created_by,
    api_credential_id,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
RETURNING id, client_id, check_type, source, status, item_count, success_count, failure_count, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, original_filename, idempotency_key, created_by, api_credential_id, error_code, error_message, started_at, completed_at, metadata, created_at, updated_at
`

type InsertLookupJobParams struct {
	ClientID         uuid.UUID        `json:"client_id"`
	CheckType        LookupCheckType  `json:"check_type"`
	Source           LookupJobSource  `json:"source"`
	Status           LookupJobStatus  `json:"status"`
	ItemCount        int32            `json:"item_count"`
	UnitSellPrice    *decimal.Decimal `json:"unit_sell_price"`
	TariffPlanID     *uuid.UUID       `json:"tariff_plan_id"`
	TariffPlanCode   *string          `json:"tariff_plan_code"`
	Currency         string           `json:"currency"`
	EstimatedCost    *decimal.Decimal `json:"estimated_cost"`
	OriginalFilename *string          `json:"original_filename"`
	IdempotencyKey   *string          `json:"idempotency_key"`
	CreatedBy        *uuid.UUID       `json:"created_by"`
	ApiCredentialID  *uuid.UUID       `json:"api_credential_id"`
	Metadata         []byte           `json:"metadata"`
}

func (q *Queries) InsertLookupJob(ctx context.Context, arg InsertLookupJobParams) (LookupJob, error) {
	row := q.db.QueryRow(ctx, insertLookupJob,
		arg.ClientID,
		arg.CheckType,
		arg.Source,
		arg.Status,
		arg.ItemCount,
		arg.UnitSellPrice,
		arg.TariffPlanID,
		arg.TariffPlanCode,
		arg.Currency,
		arg.EstimatedCost,
		arg.OriginalFilename,
		arg.IdempotencyKey,
		arg.CreatedBy,
		arg.ApiCredentialID,
		arg.Metadata,
	)
	var i LookupJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Source,
		&i.Status,
		&i.ItemCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.OriginalFilename,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.ApiCredentialID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProviderLookupCallback = `-- name: InsertProviderLookupCallback :one
INSERT INTO provider_lookup_callbacks (
    client_id,
    job_item_id,
    provider_code,
    provider_message_id,
    raw_payload,
    normalized_result,
    dedupe_key,
    signature_valid,
    processed_at,
    process_error
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, client_id, job_item_id, provider_code, provider_message_id, raw_payload, normalized_result, dedupe_key, signature_valid, processed_at, process_error, created_at
`

type InsertProviderLookupCallbackParams struct {
	ClientID          *uuid.UUID `json:"client_id"`
	JobItemID         *uuid.UUID `json:"job_item_id"`
	ProviderCode      string     `json:"provider_code"`
	ProviderMessageID *string    `json:"provider_message_id"`
	RawPayload        []byte     `json:"raw_payload"`
	NormalizedResult  []byte     `json:"normalized_result"`
	DedupeKey         *string    `json:"dedupe_key"`
	SignatureValid    *bool      `json:"signature_valid"`
	ProcessedAt       *time.Time `json:"processed_at"`
	ProcessError      *string    `json:"process_error"`
}

func (q *Queries) InsertProviderLookupCallback(ctx context.Context, arg InsertProviderLookupCallbackParams) (ProviderLookupCallback, error) {
	row := q.db.QueryRow(ctx, insertProviderLookupCallback,
		arg.ClientID,
		arg.JobItemID,
		arg.ProviderCode,
		arg.ProviderMessageID,
		arg.RawPayload,
		arg.NormalizedResult,
		arg.DedupeKey,
		arg.SignatureValid,
		arg.ProcessedAt,
		arg.ProcessError,
	)
	var i ProviderLookupCallback
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.JobItemID,
		&i.ProviderCode,
		&i.ProviderMessageID,
		&i.RawPayload,
		&i.NormalizedResult,
		&i.DedupeKey,
		&i.SignatureValid,
		&i.ProcessedAt,
		&i.ProcessError,
		&i.CreatedAt,
	)
	return i, err
}

const insertProviderLookupRequest = `-- name: InsertProviderLookupRequest :one
INSERT INTO provider_lookup_requests (
    client_id,
    job_item_id,
    provider_code,
    kind,
    status,
    provider_message_id,
    request_payload,
    idempotency_key,
    started_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, client_id, job_item_id, provider_code, kind, status, provider_message_id, http_status, error_code, error_message, request_payload, response_payload, normalized_result, idempotency_key, started_at, finished_at, created_at
`

type InsertProviderLookupRequestParams struct {
	ClientID          *uuid.UUID                  `json:"client_id"`
	JobItemID         *uuid.UUID                  `json:"job_item_id"`
	ProviderCode      string                      `json:"provider_code"`
	Kind              ProviderLookupKind          `json:"kind"`
	Status            ProviderLookupRequestStatus `json:"status"`
	ProviderMessageID *string                     `json:"provider_message_id"`
	RequestPayload    []byte                      `json:"request_payload"`
	IdempotencyKey    *string                     `json:"idempotency_key"`
	StartedAt         *time.Time                  `json:"started_at"`
}

func (q *Queries) InsertProviderLookupRequest(ctx context.Context, arg InsertProviderLookupRequestParams) (ProviderLookupRequest, error) {
	row := q.db.QueryRow(ctx, insertProviderLookupRequest,
		arg.ClientID,
		arg.JobItemID,
		arg.ProviderCode,
		arg.Kind,
		arg.Status,
		arg.ProviderMessageID,
		arg.RequestPayload,
		arg.IdempotencyKey,
		arg.StartedAt,
	)
	var i ProviderLookupRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.JobItemID,
		&i.ProviderCode,
		&i.Kind,
		&i.Status,
		&i.ProviderMessageID,
		&i.HttpStatus,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.NormalizedResult,
		&i.IdempotencyKey,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEmptyCsvLookupShells = `-- name: ListEmptyCsvLookupShells :many
SELECT id, client_id, check_type, source, status, item_count, success_count, failure_count, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, original_filename, idempotency_key, created_by, api_credential_id, error_code, error_message, started_at, completed_at, metadata, created_at, updated_at
FROM lookup_jobs
WHERE item_count = 0
  AND status = 'queued'
  AND created_at <= $1
  AND metadata ? 'csv_file_path'
ORDER BY created_at
LIMIT $2
`

type ListEmptyCsvLookupShellsParams struct {
	OlderThan time.Time `json:"older_than"`
	PageLimit int32     `json:"page_limit"`
}

func (q *Queries) ListEmptyCsvLookupShells(ctx context.Context, arg ListEmptyCsvLookupShellsParams) ([]LookupJob, error) {
	rows, err := q.db.Query(ctx, listEmptyCsvLookupShells, arg.OlderThan, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupJob
	for rows.Next() {
		var i LookupJob
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.CheckType,
			&i.Source,
			&i.Status,
			&i.ItemCount,
			&i.SuccessCount,
			&i.FailureCount,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.OriginalFilename,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.ApiCredentialID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsNeedingFinalize = `-- name: ListJobsNeedingFinalize :many
SELECT id, client_id, check_type, source, status, item_count, success_count, failure_count, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, original_filename, idempotency_key, created_by, api_credential_id, error_code, error_message, started_at, completed_at, metadata, created_at, updated_at
FROM lookup_jobs
WHERE status = 'processing'
  AND item_count > 0
  AND item_count = success_count + failure_count
ORDER BY updated_at
LIMIT $1
`

func (q *Queries) ListJobsNeedingFinalize(ctx context.Context, pageLimit int32) ([]LookupJob, error) {
	rows, err := q.db.Query(ctx, listJobsNeedingFinalize, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupJob
	for rows.Next() {
		var i LookupJob
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.CheckType,
			&i.Source,
			&i.Status,
			&i.ItemCount,
			&i.SuccessCount,
			&i.FailureCount,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.OriginalFilename,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.ApiCredentialID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsNeedingSubmitResume = `-- name: ListJobsNeedingSubmitResume :many
SELECT j.id, j.client_id, j.check_type, j.source, j.status, j.item_count, j.success_count, j.failure_count, j.unit_sell_price, j.tariff_plan_id, j.tariff_plan_code, j.currency, j.estimated_cost, j.actual_cost, j.original_filename, j.idempotency_key, j.created_by, j.api_credential_id, j.error_code, j.error_message, j.started_at, j.completed_at, j.metadata, j.created_at, j.updated_at
FROM lookup_jobs j
WHERE j.status IN ('queued', 'processing')
  AND j.item_count > 0
  AND EXISTS (
      SELECT 1 FROM lookup_items i
      WHERE i.job_id = j.id AND i.status = 'queued'
  )
  AND j.updated_at <= $1
ORDER BY j.updated_at
LIMIT $2
`

type ListJobsNeedingSubmitResumeParams struct {
	OlderThan time.Time `json:"older_than"`
	PageLimit int32     `json:"page_limit"`
}

func (q *Queries) ListJobsNeedingSubmitResume(ctx context.Context, arg ListJobsNeedingSubmitResumeParams) ([]LookupJob, error) {
	rows, err := q.db.Query(ctx, listJobsNeedingSubmitResume, arg.OlderThan, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupJob
	for rows.Next() {
		var i LookupJob
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.CheckType,
			&i.Source,
			&i.Status,
			&i.ItemCount,
			&i.SuccessCount,
			&i.FailureCount,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.OriginalFilename,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.ApiCredentialID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLookupItemsByJob = `-- name: ListLookupItemsByJob :many
SELECT id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
FROM lookup_items
WHERE job_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListLookupItemsByJob(ctx context.Context, jobID uuid.UUID) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, listLookupItemsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLookupItemsByJobPage = `-- name: ListLookupItemsByJobPage :many
SELECT id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
FROM lookup_items
WHERE job_id = $1
ORDER BY created_at, id
LIMIT $3 OFFSET $2
`

type ListLookupItemsByJobPageParams struct {
	JobID      uuid.UUID `json:"job_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListLookupItemsByJobPage(ctx context.Context, arg ListLookupItemsByJobPageParams) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, listLookupItemsByJobPage, arg.JobID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLookupItemsByProviderMessage = `-- name: ListLookupItemsByProviderMessage :many
SELECT id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
FROM lookup_items
WHERE provider_code = $1
  AND provider_message_id = $2
ORDER BY created_at, id
`

type ListLookupItemsByProviderMessageParams struct {
	ProviderCode      string  `json:"provider_code"`
	ProviderMessageID *string `json:"provider_message_id"`
}

func (q *Queries) ListLookupItemsByProviderMessage(ctx context.Context, arg ListLookupItemsByProviderMessageParams) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, listLookupItemsByProviderMessage, arg.ProviderCode, arg.ProviderMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLookupItemsForClient = `-- name: ListLookupItemsForClient :many
SELECT id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
FROM lookup_items
WHERE client_id = $1
  AND ($2::lookup_item_status IS NULL OR status = $2)
  AND ($3::lookup_check_type IS NULL OR check_type = $3)
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListLookupItemsForClientParams struct {
	ClientID        uuid.UUID            `json:"client_id"`
	FilterStatus    NullLookupItemStatus `json:"filter_status"`
	FilterCheckType NullLookupCheckType  `json:"filter_check_type"`
	PageOffset      int32                `json:"page_offset"`
	PageLimit       int32                `json:"page_limit"`
}

func (q *Queries) ListLookupItemsForClient(ctx context.Context, arg ListLookupItemsForClientParams) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, listLookupItemsForClient,
		arg.ClientID,
		arg.FilterStatus,
		arg.FilterCheckType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLookupJobs = `-- name: ListLookupJobs :many
SELECT id, client_id, check_type, source, status, item_count, success_count, failure_count, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, original_filename, idempotency_key, created_by, api_credential_id, error_code, error_message, started_at, completed_at, metadata, created_at, updated_at
FROM lookup_jobs
WHERE ($1::uuid IS NULL OR client_id = $1)
  AND ($2::lookup_job_status IS NULL OR status = $2)
  AND ($3::lookup_check_type IS NULL OR check_type = $3)
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListLookupJobsParams struct {
	ClientID        *uuid.UUID          `json:"client_id"`
	FilterStatus    NullLookupJobStatus `json:"filter_status"`
	FilterCheckType NullLookupCheckType `json:"filter_check_type"`
	PageOffset      int32               `json:"page_offset"`
	PageLimit       int32               `json:"page_limit"`
}

func (q *Queries) ListLookupJobs(ctx context.Context, arg ListLookupJobsParams) ([]LookupJob, error) {
	rows, err := q.db.Query(ctx, listLookupJobs,
		arg.ClientID,
		arg.FilterStatus,
		arg.FilterCheckType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupJob
	for rows.Next() {
		var i LookupJob
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.CheckType,
			&i.Source,
			&i.Status,
			&i.ItemCount,
			&i.SuccessCount,
			&i.FailureCount,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.OriginalFilename,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.ApiCredentialID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenLookupItemsForCallbackPhone = `-- name: ListOpenLookupItemsForCallbackPhone :many
SELECT id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
FROM lookup_items
WHERE phone_digits = $1
  AND status IN ('queued', 'reserved', 'pending')
  AND created_at >= $2
  AND (
    provider_message_id IS NULL
    OR provider_message_id = ''
    OR provider_message_id = $3
  )
ORDER BY created_at, id
`

type ListOpenLookupItemsForCallbackPhoneParams struct {
	PhoneDigits       string    `json:"phone_digits"`
	CreatedAfter      time.Time `json:"created_after"`
	ProviderMessageID *string   `json:"provider_message_id"`
}

func (q *Queries) ListOpenLookupItemsForCallbackPhone(ctx context.Context, arg ListOpenLookupItemsForCallbackPhoneParams) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, listOpenLookupItemsForCallbackPhone, arg.PhoneDigits, arg.CreatedAfter, arg.ProviderMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenLookupItemsForCallbackPhoneTail = `-- name: ListOpenLookupItemsForCallbackPhoneTail :many
SELECT id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
FROM lookup_items
WHERE right(phone_digits, 10) = $1
  AND status IN ('queued', 'reserved', 'pending')
  AND created_at >= $2
  AND (
    provider_message_id IS NULL
    OR provider_message_id = ''
    OR provider_message_id = $3
  )
ORDER BY created_at, id
`

type ListOpenLookupItemsForCallbackPhoneTailParams struct {
	PhoneTail         string    `json:"phone_tail"`
	CreatedAfter      time.Time `json:"created_after"`
	ProviderMessageID *string   `json:"provider_message_id"`
}

func (q *Queries) ListOpenLookupItemsForCallbackPhoneTail(ctx context.Context, arg ListOpenLookupItemsForCallbackPhoneTailParams) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, listOpenLookupItemsForCallbackPhoneTail, arg.PhoneTail, arg.CreatedAfter, arg.ProviderMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenLookupItemsForCallbackSendID = `-- name: ListOpenLookupItemsForCallbackSendID :many
SELECT i.id, i.job_id, i.client_id, i.check_type, i.status, i.phone_e164, i.phone_digits, i.provider_code, i.provider_message_id, i.unit_sell_price, i.tariff_plan_id, i.tariff_plan_code, i.currency, i.estimated_cost, i.actual_cost, i.result_status, i.is_reachable, i.imsi, i.mcc, i.mnc, i.operator_name, i.country_code, i.ported, i.roaming, i.normalized_result, i.error_code, i.error_message, i.billing_action, i.next_poll_at, i.poll_attempts, i.sent_at, i.completed_at, i.created_at, i.updated_at, i.enrich_attempts
FROM provider_lookup_requests r
JOIN lookup_items i ON i.id = r.job_item_id
WHERE r.kind = 'send'
  AND r.created_at >= $1
  AND i.status IN ('queued', 'reserved', 'pending')
  AND (
    r.provider_message_id = $2::text
    OR r.request_payload->>'id' = $2::text
  )
ORDER BY i.created_at, i.id
`

type ListOpenLookupItemsForCallbackSendIDParams struct {
	CreatedAfter time.Time `json:"created_after"`
	CallbackID   string    `json:"callback_id"`
}

func (q *Queries) ListOpenLookupItemsForCallbackSendID(ctx context.Context, arg ListOpenLookupItemsForCallbackSendIDParams) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, listOpenLookupItemsForCallbackSendID, arg.CreatedAfter, arg.CallbackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedLookupItemIDs = `-- name: ListQueuedLookupItemIDs :many
SELECT id
FROM lookup_items
WHERE job_id = $1
  AND status = 'queued'
ORDER BY created_at, id
`

func (q *Queries) ListQueuedLookupItemIDs(ctx context.Context, jobID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listQueuedLookupItemIDs, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentProviderLookupCallbacks = `-- name: ListRecentProviderLookupCallbacks :many
SELECT id, provider_code, provider_message_id, signature_valid, processed_at, process_error, raw_payload, created_at
FROM provider_lookup_callbacks
ORDER BY created_at DESC
LIMIT $1
`

type ListRecentProviderLookupCallbacksRow struct {
	ID                uuid.UUID  `json:"id"`
	ProviderCode      string     `json:"provider_code"`
	ProviderMessageID *string    `json:"provider_message_id"`
	SignatureValid    *bool      `json:"signature_valid"`
	ProcessedAt       *time.Time `json:"processed_at"`
	ProcessError      *string    `json:"process_error"`
	RawPayload        []byte     `json:"raw_payload"`
	CreatedAt         time.Time  `json:"created_at"`
}

func (q *Queries) ListRecentProviderLookupCallbacks(ctx context.Context, pageLimit int32) ([]ListRecentProviderLookupCallbacksRow, error) {
	rows, err := q.db.Query(ctx, listRecentProviderLookupCallbacks, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentProviderLookupCallbacksRow
	for rows.Next() {
		var i ListRecentProviderLookupCallbacksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.SignatureValid,
			&i.ProcessedAt,
			&i.ProcessError,
			&i.RawPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentProviderLookupRequests = `-- name: ListRecentProviderLookupRequests :many
SELECT id, provider_code, kind, status, provider_message_id, http_status, error_code, error_message, request_payload, response_payload, created_at
FROM provider_lookup_requests
ORDER BY created_at DESC
LIMIT $1
`

type ListRecentProviderLookupRequestsRow struct {
	ID                uuid.UUID                   `json:"id"`
	ProviderCode      string                      `json:"provider_code"`
	Kind              ProviderLookupKind          `json:"kind"`
	Status            ProviderLookupRequestStatus `json:"status"`
	ProviderMessageID *string                     `json:"provider_message_id"`
	HttpStatus        *int32                      `json:"http_status"`
	ErrorCode         *string                     `json:"error_code"`
	ErrorMessage      *string                     `json:"error_message"`
	RequestPayload    []byte                      `json:"request_payload"`
	ResponsePayload   []byte                      `json:"response_payload"`
	CreatedAt         time.Time                   `json:"created_at"`
}

func (q *Queries) ListRecentProviderLookupRequests(ctx context.Context, pageLimit int32) ([]ListRecentProviderLookupRequestsRow, error) {
	rows, err := q.db.Query(ctx, listRecentProviderLookupRequests, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentProviderLookupRequestsRow
	for rows.Next() {
		var i ListRecentProviderLookupRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderCode,
			&i.Kind,
			&i.Status,
			&i.ProviderMessageID,
			&i.HttpStatus,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalePendingLookupItems = `-- name: ListStalePendingLookupItems :many
SELECT id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
FROM lookup_items
WHERE status = 'pending'
  AND updated_at <= $1
ORDER BY updated_at, id
LIMIT $2
`

type ListStalePendingLookupItemsParams struct {
	OlderThan time.Time `json:"older_than"`
	PageLimit int32     `json:"page_limit"`
}

func (q *Queries) ListStalePendingLookupItems(ctx context.Context, arg ListStalePendingLookupItemsParams) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, listStalePendingLookupItems, arg.OlderThan, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleReservedLookupItems = `-- name: ListStaleReservedLookupItems :many
SELECT id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
FROM lookup_items
WHERE status = 'reserved'
  AND updated_at <= $1
ORDER BY updated_at, id
LIMIT $2
`

type ListStaleReservedLookupItemsParams struct {
	OlderThan time.Time `json:"older_than"`
	PageLimit int32     `json:"page_limit"`
}

func (q *Queries) ListStaleReservedLookupItems(ctx context.Context, arg ListStaleReservedLookupItemsParams) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, listStaleReservedLookupItems, arg.OlderThan, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedProviderLookupCallbacks = `-- name: ListUnprocessedProviderLookupCallbacks :many
SELECT id, client_id, job_item_id, provider_code, provider_message_id, raw_payload, normalized_result, dedupe_key, signature_valid, processed_at, process_error, created_at
FROM provider_lookup_callbacks
WHERE processed_at IS NULL
ORDER BY created_at, id
LIMIT $1
`

func (q *Queries) ListUnprocessedProviderLookupCallbacks(ctx context.Context, pageLimit int32) ([]ProviderLookupCallback, error) {
	rows, err := q.db.Query(ctx, listUnprocessedProviderLookupCallbacks, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderLookupCallback
	for rows.Next() {
		var i ProviderLookupCallback
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.JobItemID,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.RawPayload,
			&i.NormalizedResult,
			&i.DedupeKey,
			&i.SignatureValid,
			&i.ProcessedAt,
			&i.ProcessError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLookupCSVPreviewConsumed = `-- name: MarkLookupCSVPreviewConsumed :one
UPDATE lookup_csv_previews
SET status = 'consumed',
    job_id = COALESCE($1, job_id),
    updated_at = now()
WHERE id = $2
  AND status = 'consuming'
RETURNING id, client_id, check_type, status, original_filename, phone_count, phones_json, error_message, job_id, expires_at, created_at, updated_at
`

type MarkLookupCSVPreviewConsumedParams struct {
	JobID *uuid.UUID `json:"job_id"`
	ID    uuid.UUID  `json:"id"`
}

func (q *Queries) MarkLookupCSVPreviewConsumed(ctx context.Context, arg MarkLookupCSVPreviewConsumedParams) (LookupCsvPreview, error) {
	row := q.db.QueryRow(ctx, markLookupCSVPreviewConsumed, arg.JobID, arg.ID)
	var i LookupCsvPreview
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Status,
		&i.OriginalFilename,
		&i.PhoneCount,
		&i.PhonesJson,
		&i.ErrorMessage,
		&i.JobID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markLookupJobProcessing = `-- name: MarkLookupJobProcessing :one
UPDATE lookup_jobs
SET status = 'processing',
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE id = $1
  AND status IN ('queued', 'processing')
RETURNING id, client_id, check_type, source, status, item_count, success_count, failure_count, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, original_filename, idempotency_key, created_by, api_credential_id, error_code, error_message, started_at, completed_at, metadata, created_at, updated_at
`

func (q *Queries) MarkLookupJobProcessing(ctx context.Context, id uuid.UUID) (LookupJob, error) {
	row := q.db.QueryRow(ctx, markLookupJobProcessing, id)
	var i LookupJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Source,
		&i.Status,
		&i.ItemCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.OriginalFilename,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.ApiCredentialID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markProviderLookupCallbackProcessed = `-- name: MarkProviderLookupCallbackProcessed :exec
UPDATE provider_lookup_callbacks
SET processed_at = now(),
    process_error = $1,
    job_item_id = COALESCE($2, job_item_id),
    client_id = COALESCE($3, client_id)
WHERE id = $4
`

type MarkProviderLookupCallbackProcessedParams struct {
	ProcessError *string    `json:"process_error"`
	JobItemID    *uuid.UUID `json:"job_item_id"`
	ClientID     *uuid.UUID `json:"client_id"`
	ID           uuid.UUID  `json:"id"`
}

func (q *Queries) MarkProviderLookupCallbackProcessed(ctx context.Context, arg MarkProviderLookupCallbackProcessedParams) error {
	_, err := q.db.Exec(ctx, markProviderLookupCallbackProcessed,
		arg.ProcessError,
		arg.JobItemID,
		arg.ClientID,
		arg.ID,
	)
	return err
}

const patchLookupJobAfterParse = `-- name: PatchLookupJobAfterParse :one
UPDATE lookup_jobs
SET item_count = $1,
    unit_sell_price = $2,
    tariff_plan_id = $3,
    tariff_plan_code = $4,
    currency = $5,
    estimated_cost = $6,
    original_filename = COALESCE($7, original_filename),
    updated_at = now()
WHERE id = $8
  AND status = 'queued'
  AND item_count = 0
RETURNING id, client_id, check_type, source, status, item_count, success_count, failure_count, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, original_filename, idempotency_key, created_by, api_credential_id, error_code, error_message, started_at, completed_at, metadata, created_at, updated_at
`

type PatchLookupJobAfterParseParams struct {
	ItemCount        int32            `json:"item_count"`
	UnitSellPrice    *decimal.Decimal `json:"unit_sell_price"`
	TariffPlanID     *uuid.UUID       `json:"tariff_plan_id"`
	TariffPlanCode   *string          `json:"tariff_plan_code"`
	Currency         string           `json:"currency"`
	EstimatedCost    *decimal.Decimal `json:"estimated_cost"`
	OriginalFilename *string          `json:"original_filename"`
	ID               uuid.UUID        `json:"id"`
}

func (q *Queries) PatchLookupJobAfterParse(ctx context.Context, arg PatchLookupJobAfterParseParams) (LookupJob, error) {
	row := q.db.QueryRow(ctx, patchLookupJobAfterParse,
		arg.ItemCount,
		arg.UnitSellPrice,
		arg.TariffPlanID,
		arg.TariffPlanCode,
		arg.Currency,
		arg.EstimatedCost,
		arg.OriginalFilename,
		arg.ID,
	)
	var i LookupJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Source,
		&i.Status,
		&i.ItemCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.OriginalFilename,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.ApiCredentialID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const patchLookupJobMetadata = `-- name: PatchLookupJobMetadata :one
UPDATE lookup_jobs
SET metadata = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, client_id, check_type, source, status, item_count, success_count, failure_count, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, original_filename, idempotency_key, created_by, api_credential_id, error_code, error_message, started_at, completed_at, metadata, created_at, updated_at
`

type PatchLookupJobMetadataParams struct {
	Metadata []byte    `json:"metadata"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) PatchLookupJobMetadata(ctx context.Context, arg PatchLookupJobMetadataParams) (LookupJob, error) {
	row := q.db.QueryRow(ctx, patchLookupJobMetadata, arg.Metadata, arg.ID)
	var i LookupJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Source,
		&i.Status,
		&i.ItemCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.OriginalFilename,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.ApiCredentialID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const refreshLookupJobCounters = `-- name: RefreshLookupJobCounters :one
UPDATE lookup_jobs j
SET success_count = (
        SELECT count(*)::int FROM lookup_items WHERE job_id = j.id AND status = 'completed'
    ),
    failure_count = (
        SELECT count(*)::int FROM lookup_items WHERE job_id = j.id AND status = 'failed'
    ),
    actual_cost = (
        SELECT COALESCE(sum(i.actual_cost), 0)::billing_money
        FROM lookup_items i
        WHERE i.job_id = j.id
          AND i.billing_action = 'capture'
    ),
    updated_at = now()
WHERE j.id = $1
RETURNING id, client_id, check_type, source, status, item_count, success_count, failure_count, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, original_filename, idempotency_key, created_by, api_credential_id, error_code, error_message, started_at, completed_at, metadata, created_at, updated_at
`

func (q *Queries) RefreshLookupJobCounters(ctx context.Context, id uuid.UUID) (LookupJob, error) {
	row := q.db.QueryRow(ctx, refreshLookupJobCounters, id)
	var i LookupJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Source,
		&i.Status,
		&i.ItemCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.OriginalFilename,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.ApiCredentialID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reopenUnappliedLookupCallbacks = `-- name: ReopenUnappliedLookupCallbacks :execrows
UPDATE provider_lookup_callbacks
SET processed_at = NULL,
    process_error = NULL
WHERE processed_at IS NOT NULL
  AND created_at >= $1
  AND COALESCE(process_error, '') IN ('', 'not_found', 'item_not_found', 'ambiguous', 'phone_mismatch')
`

func (q *Queries) ReopenUnappliedLookupCallbacks(ctx context.Context, createdAfter time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, reopenUnappliedLookupCallbacks, createdAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rollbackLookupCSVPreviewConsuming = `-- name: RollbackLookupCSVPreviewConsuming :one
UPDATE lookup_csv_previews
SET status = 'ready',
    updated_at = now()
WHERE id = $1
  AND status = 'consuming'
RETURNING id, client_id, check_type, status, original_filename, phone_count, phones_json, error_message, job_id, expires_at, created_at, updated_at
`

func (q *Queries) RollbackLookupCSVPreviewConsuming(ctx context.Context, id uuid.UUID) (LookupCsvPreview, error) {
	row := q.db.QueryRow(ctx, rollbackLookupCSVPreviewConsuming, id)
	var i LookupCsvPreview
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Status,
		&i.OriginalFilename,
		&i.PhoneCount,
		&i.PhonesJson,
		&i.ErrorMessage,
		&i.JobID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const stampLookupItemClientSendID = `-- name: StampLookupItemClientSendID :exec
UPDATE lookup_items
SET provider_code = $1,
    provider_message_id = $2,
    updated_at = now()
WHERE id = $3
  AND (provider_message_id IS NULL OR provider_message_id = '')
`

type StampLookupItemClientSendIDParams struct {
	ProviderCode      string    `json:"provider_code"`
	ProviderMessageID *string   `json:"provider_message_id"`
	ID                uuid.UUID `json:"id"`
}

func (q *Queries) StampLookupItemClientSendID(ctx context.Context, arg StampLookupItemClientSendIDParams) error {
	_, err := q.db.Exec(ctx, stampLookupItemClientSendID, arg.ProviderCode, arg.ProviderMessageID, arg.ID)
	return err
}

const transitionLookupItem = `-- name: TransitionLookupItem :one
UPDATE lookup_items
SET status = $1,
    provider_code = COALESCE($2, provider_code),
    provider_message_id = COALESCE($3, provider_message_id),
    result_status = COALESCE($4, result_status),
    is_reachable = COALESCE($5, is_reachable),
    imsi = COALESCE($6, imsi),
    mcc = COALESCE($7, mcc),
    mnc = COALESCE($8, mnc),
    operator_name = COALESCE($9, operator_name),
    country_code = COALESCE($10, country_code),
    ported = COALESCE($11, ported),
    roaming = COALESCE($12, roaming),
    normalized_result = COALESCE($13, normalized_result),
    error_code = COALESCE($14, error_code),
    error_message = COALESCE($15, error_message),
    next_poll_at = COALESCE($16, next_poll_at),
    poll_attempts = COALESCE($17, poll_attempts),
    sent_at = COALESCE($18, sent_at),
    completed_at = COALESCE($19, completed_at),
    updated_at = now()
WHERE id = $20
  AND status = ANY($21::text[]::lookup_item_status[])
RETURNING id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
`

type TransitionLookupItemParams struct {
	ToStatus          LookupItemStatus `json:"to_status"`
	ProviderCode      *string          `json:"provider_code"`
	ProviderMessageID *string          `json:"provider_message_id"`
	ResultStatus      *string          `json:"result_status"`
	IsReachable       *bool            `json:"is_reachable"`
	Imsi              *string          `json:"imsi"`
	Mcc               *string          `json:"mcc"`
	Mnc               *string          `json:"mnc"`
	OperatorName      *string          `json:"operator_name"`
	CountryCode       *string          `json:"country_code"`
	Ported            *bool            `json:"ported"`
	Roaming           *bool            `json:"roaming"`
	NormalizedResult  []byte           `json:"normalized_result"`
	ErrorCode         *string          `json:"error_code"`
	ErrorMessage      *string          `json:"error_message"`
	NextPollAt        *time.Time       `json:"next_poll_at"`
	PollAttempts      *int32           `json:"poll_attempts"`
	SentAt            *time.Time       `json:"sent_at"`
	CompletedAt       *time.Time       `json:"completed_at"`
	ID                uuid.UUID        `json:"id"`
	FromStatuses      []string         `json:"from_statuses"`
}

// billing_action is written only by SetLookupItemBillingAction inside settle.
func (q *Queries) TransitionLookupItem(ctx context.Context, arg TransitionLookupItemParams) (LookupItem, error) {
	row := q.db.QueryRow(ctx, transitionLookupItem,
		arg.ToStatus,
		arg.ProviderCode,
		arg.ProviderMessageID,
		arg.ResultStatus,
		arg.IsReachable,
		arg.Imsi,
		arg.Mcc,
		arg.Mnc,
		arg.OperatorName,
		arg.CountryCode,
		arg.Ported,
		arg.Roaming,
		arg.NormalizedResult,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.NextPollAt,
		arg.PollAttempts,
		arg.SentAt,
		arg.CompletedAt,
		arg.ID,
		arg.FromStatuses,
	)
	var i LookupItem
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ClientID,
		&i.CheckType,
		&i.Status,
		&i.PhoneE164,
		&i.PhoneDigits,
		&i.ProviderCode,
		&i.ProviderMessageID,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.ResultStatus,
		&i.IsReachable,
		&i.Imsi,
		&i.Mcc,
		&i.Mnc,
		&i.OperatorName,
		&i.CountryCode,
		&i.Ported,
		&i.Roaming,
		&i.NormalizedResult,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.BillingAction,
		&i.NextPollAt,
		&i.PollAttempts,
		&i.SentAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrichAttempts,
	)
	return i, err
}

const updateLookupCSVPreview = `-- name: UpdateLookupCSVPreview :one
UPDATE lookup_csv_previews
SET status = COALESCE($1, status),
    phone_count = COALESCE($2, phone_count),
    phones_json = COALESCE($3, phones_json),
    error_message = $4,
    job_id = COALESCE($5, job_id),
    updated_at = now()
WHERE id = $6
RETURNING id, client_id, check_type, status, original_filename, phone_count, phones_json, error_message, job_id, expires_at, created_at, updated_at
`

type UpdateLookupCSVPreviewParams struct {
	Status       NullLookupCsvPreviewStatus `json:"status"`
	PhoneCount   *int32                     `json:"phone_count"`
	PhonesJson   []byte                     `json:"phones_json"`
	ErrorMessage *string                    `json:"error_message"`
	JobID        *uuid.UUID                 `json:"job_id"`
	ID           uuid.UUID                  `json:"id"`
}

func (q *Queries) UpdateLookupCSVPreview(ctx context.Context, arg UpdateLookupCSVPreviewParams) (LookupCsvPreview, error) {
	row := q.db.QueryRow(ctx, updateLookupCSVPreview,
		arg.Status,
		arg.PhoneCount,
		arg.PhonesJson,
		arg.ErrorMessage,
		arg.JobID,
		arg.ID,
	)
	var i LookupCsvPreview
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Status,
		&i.OriginalFilename,
		&i.PhoneCount,
		&i.PhonesJson,
		&i.ErrorMessage,
		&i.JobID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProviderLookupRequest = `-- name: UpdateProviderLookupRequest :exec
UPDATE provider_lookup_requests
SET status = $1,
    provider_message_id = COALESCE($2, provider_message_id),
    http_status = $3,
    error_code = $4,
    error_message = $5,
    response_payload = $6,
    normalized_result = $7,
    finished_at = $8
WHERE id = $9
`

type UpdateProviderLookupRequestParams struct {
	Status            ProviderLookupRequestStatus `json:"status"`
	ProviderMessageID *string                     `json:"provider_message_id"`
	HttpStatus        *int32                      `json:"http_status"`
	ErrorCode         *string                     `json:"error_code"`
	ErrorMessage      *string                     `json:"error_message"`
	ResponsePayload   []byte                      `json:"response_payload"`
	NormalizedResult  []byte                      `json:"normalized_result"`
	FinishedAt        *time.Time                  `json:"finished_at"`
	ID                uuid.UUID                   `json:"id"`
}

func (q *Queries) UpdateProviderLookupRequest(ctx context.Context, arg UpdateProviderLookupRequestParams) error {
	_, err := q.db.Exec(ctx, updateProviderLookupRequest,
		arg.Status,
		arg.ProviderMessageID,
		arg.HttpStatus,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ResponsePayload,
		arg.NormalizedResult,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
