// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lookup_billing.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countLookupItemsBlockingRemainder = `-- name: CountLookupItemsBlockingRemainder :one
SELECT count(*)::bigint AS n
FROM lookup_items
WHERE job_id = $1
  AND (
    status NOT IN ('completed', 'failed')
    OR billing_action IS NULL
  )
`

// Remainder must not run while any item is still open or terminal-but-unposted.
func (q *Queries) CountLookupItemsBlockingRemainder(ctx context.Context, jobID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLookupItemsBlockingRemainder, jobID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countOpenLookupHolds = `-- name: CountOpenLookupHolds :one
SELECT count(*)::bigint AS n
FROM wallet_transactions h
WHERE h.type = 'HOLD'
  AND h.lookup_job_id IS NOT NULL
  AND (h.amount - COALESCE((
        SELECT sum(s.amount)
        FROM wallet_transactions s
        WHERE s.related_hold_id = h.id
          AND s.type IN ('DEBIT', 'RELEASE')
    ), 0)) > 0
`

func (q *Queries) CountOpenLookupHolds(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenLookupHolds)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const getLookupItem = `-- name: GetLookupItem :one
SELECT id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts FROM lookup_items WHERE id = $1
`

func (q *Queries) GetLookupItem(ctx context.Context, id uuid.UUID) (LookupItem, error) {
	row := q.db.QueryRow(ctx, getLookupItem, id)
	var i LookupItem
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ClientID,
		&i.CheckType,
		&i.Status,
		&i.PhoneE164,
		&i.PhoneDigits,
		&i.ProviderCode,
		&i.ProviderMessageID,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.ResultStatus,
		&i.IsReachable,
		&i.Imsi,
		&i.Mcc,
		&i.Mnc,
		&i.OperatorName,
		&i.CountryCode,
		&i.Ported,
		&i.Roaming,
		&i.NormalizedResult,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.BillingAction,
		&i.NextPollAt,
		&i.PollAttempts,
		&i.SentAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrichAttempts,
	)
	return i, err
}

const getLookupJob = `-- name: GetLookupJob :one
SELECT id, client_id, check_type, source, status, item_count, success_count, failure_count, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, original_filename, idempotency_key, created_by, api_credential_id, error_code, error_message, started_at, completed_at, metadata, created_at, updated_at, reachable_count, unreachable_count FROM lookup_jobs WHERE id = $1
`

func (q *Queries) GetLookupJob(ctx context.Context, id uuid.UUID) (LookupJob, error) {
	row := q.db.QueryRow(ctx, getLookupJob, id)
	var i LookupJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CheckType,
		&i.Source,
		&i.Status,
		&i.ItemCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.UnitSellPrice,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.OriginalFilename,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.ApiCredentialID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReachableCount,
		&i.UnreachableCount,
	)
	return i, err
}

const getLookupJobHold = `-- name: GetLookupJobHold :one
SELECT id, wallet_id, client_id, type, amount, currency, balance_after_available, balance_after_held, related_hold_id, sms_message_id, idempotency_key, description, metadata, created_by, created_at, lookup_job_id, lookup_item_id
FROM wallet_transactions
WHERE lookup_job_id = $1
  AND type = 'HOLD'
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetLookupJobHold(ctx context.Context, lookupJobID *uuid.UUID) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, getLookupJobHold, lookupJobID)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.ClientID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.BalanceAfterAvailable,
		&i.BalanceAfterHeld,
		&i.RelatedHoldID,
		&i.SmsMessageID,
		&i.IdempotencyKey,
		&i.Description,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LookupJobID,
		&i.LookupItemID,
	)
	return i, err
}

const listOpenLookupJobHolds = `-- name: ListOpenLookupJobHolds :many
SELECT
    h.id AS hold_id,
    h.client_id,
    h.lookup_job_id,
    h.amount AS hold_amount,
    (h.amount - COALESCE((
        SELECT sum(s.amount)
        FROM wallet_transactions s
        WHERE s.related_hold_id = h.id
          AND s.type IN ('DEBIT', 'RELEASE')
    ), 0))::billing_money AS remaining,
    j.status AS job_status
FROM wallet_transactions h
JOIN lookup_jobs j ON j.id = h.lookup_job_id
WHERE h.type = 'HOLD'
  AND h.lookup_job_id IS NOT NULL
  AND (h.amount - COALESCE((
        SELECT sum(s.amount)
        FROM wallet_transactions s
        WHERE s.related_hold_id = h.id
          AND s.type IN ('DEBIT', 'RELEASE')
    ), 0)) > 0
ORDER BY h.created_at
LIMIT $1
`

type ListOpenLookupJobHoldsRow struct {
	HoldID      uuid.UUID       `json:"hold_id"`
	ClientID    uuid.UUID       `json:"client_id"`
	LookupJobID *uuid.UUID      `json:"lookup_job_id"`
	HoldAmount  decimal.Decimal `json:"hold_amount"`
	Remaining   decimal.Decimal `json:"remaining"`
	JobStatus   LookupJobStatus `json:"job_status"`
}

func (q *Queries) ListOpenLookupJobHolds(ctx context.Context, pageLimit int32) ([]ListOpenLookupJobHoldsRow, error) {
	rows, err := q.db.Query(ctx, listOpenLookupJobHolds, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenLookupJobHoldsRow
	for rows.Next() {
		var i ListOpenLookupJobHoldsRow
		if err := rows.Scan(
			&i.HoldID,
			&i.ClientID,
			&i.LookupJobID,
			&i.HoldAmount,
			&i.Remaining,
			&i.JobStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsettledTerminalLookupItems = `-- name: ListUnsettledTerminalLookupItems :many
SELECT id, job_id, client_id, check_type, status, phone_e164, phone_digits, provider_code, provider_message_id, unit_sell_price, tariff_plan_id, tariff_plan_code, currency, estimated_cost, actual_cost, result_status, is_reachable, imsi, mcc, mnc, operator_name, country_code, ported, roaming, normalized_result, error_code, error_message, billing_action, next_poll_at, poll_attempts, sent_at, completed_at, created_at, updated_at, enrich_attempts
FROM lookup_items
WHERE job_id = $1
  AND status IN ('completed', 'failed')
  AND billing_action IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListUnsettledTerminalLookupItems(ctx context.Context, jobID uuid.UUID) ([]LookupItem, error) {
	rows, err := q.db.Query(ctx, listUnsettledTerminalLookupItems, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupItem
	for rows.Next() {
		var i LookupItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClientID,
			&i.CheckType,
			&i.Status,
			&i.PhoneE164,
			&i.PhoneDigits,
			&i.ProviderCode,
			&i.ProviderMessageID,
			&i.UnitSellPrice,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.EstimatedCost,
			&i.ActualCost,
			&i.ResultStatus,
			&i.IsReachable,
			&i.Imsi,
			&i.Mcc,
			&i.Mnc,
			&i.OperatorName,
			&i.CountryCode,
			&i.Ported,
			&i.Roaming,
			&i.NormalizedResult,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.BillingAction,
			&i.NextPollAt,
			&i.PollAttempts,
			&i.SentAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLookupItemBillingAction = `-- name: SetLookupItemBillingAction :exec
UPDATE lookup_items
SET billing_action = $1,
    actual_cost = $2,
    updated_at = now()
WHERE id = $3
`

type SetLookupItemBillingActionParams struct {
	BillingAction NullBillingAction `json:"billing_action"`
	ActualCost    *decimal.Decimal  `json:"actual_cost"`
	ID            uuid.UUID         `json:"id"`
}

func (q *Queries) SetLookupItemBillingAction(ctx context.Context, arg SetLookupItemBillingActionParams) error {
	_, err := q.db.Exec(ctx, setLookupItemBillingAction, arg.BillingAction, arg.ActualCost, arg.ID)
	return err
}

const sumSettledAgainstHold = `-- name: SumSettledAgainstHold :one
SELECT COALESCE(sum(amount), 0)::billing_money AS settled
FROM wallet_transactions
WHERE related_hold_id = $1
  AND type IN ('DEBIT', 'RELEASE')
`

func (q *Queries) SumSettledAgainstHold(ctx context.Context, holdID *uuid.UUID) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, sumSettledAgainstHold, holdID)
	var settled decimal.Decimal
	err := row.Scan(&settled)
	return settled, err
}
