// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getAssignedNumberForClient = `-- name: GetAssignedNumberForClient :one
SELECT n.id, n.msisdn, n.status
FROM def_numbers n
JOIN number_assignments a ON a.def_number_id = n.id AND a.unassigned_at IS NULL
WHERE n.msisdn = $1
  AND a.client_id = $2
  AND n.status = 'assigned'
`

type GetAssignedNumberForClientParams struct {
	Msisdn   string    `json:"msisdn"`
	ClientID uuid.UUID `json:"client_id"`
}

type GetAssignedNumberForClientRow struct {
	ID     uuid.UUID       `json:"id"`
	Msisdn string          `json:"msisdn"`
	Status DefNumberStatus `json:"status"`
}

func (q *Queries) GetAssignedNumberForClient(ctx context.Context, arg GetAssignedNumberForClientParams) (GetAssignedNumberForClientRow, error) {
	row := q.db.QueryRow(ctx, getAssignedNumberForClient, arg.Msisdn, arg.ClientID)
	var i GetAssignedNumberForClientRow
	err := row.Scan(&i.ID, &i.Msisdn, &i.Status)
	return i, err
}

const getOpenAssignmentByMSISDN = `-- name: GetOpenAssignmentByMSISDN :one
SELECT a.id, a.def_number_id, a.client_id, a.assigned_at, n.msisdn
FROM def_numbers n
JOIN number_assignments a ON a.def_number_id = n.id AND a.unassigned_at IS NULL
WHERE n.msisdn = $1
`

type GetOpenAssignmentByMSISDNRow struct {
	ID          uuid.UUID `json:"id"`
	DefNumberID uuid.UUID `json:"def_number_id"`
	ClientID    uuid.UUID `json:"client_id"`
	AssignedAt  time.Time `json:"assigned_at"`
	Msisdn      string    `json:"msisdn"`
}

func (q *Queries) GetOpenAssignmentByMSISDN(ctx context.Context, msisdn string) (GetOpenAssignmentByMSISDNRow, error) {
	row := q.db.QueryRow(ctx, getOpenAssignmentByMSISDN, msisdn)
	var i GetOpenAssignmentByMSISDNRow
	err := row.Scan(
		&i.ID,
		&i.DefNumberID,
		&i.ClientID,
		&i.AssignedAt,
		&i.Msisdn,
	)
	return i, err
}

const getSmsMessageByID = `-- name: GetSmsMessageByID :one
SELECT id, client_id, direction, from_msisdn, to_msisdn, text, provider, provider_sms_id, provider_status, pdu_count, campaign_id, status, idempotency_key, created_at, accepted_at, sent_at, delivered_at, failed_at, unit_sell_price, billed_segments, tariff_plan_id, tariff_plan_code, currency, billing_action FROM sms_messages WHERE id = $1
`

func (q *Queries) GetSmsMessageByID(ctx context.Context, id uuid.UUID) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, getSmsMessageByID, id)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Direction,
		&i.FromMsisdn,
		&i.ToMsisdn,
		&i.Text,
		&i.Provider,
		&i.ProviderSmsID,
		&i.ProviderStatus,
		&i.PduCount,
		&i.CampaignID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UnitSellPrice,
		&i.BilledSegments,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.BillingAction,
	)
	return i, err
}

const getSmsMessageByIdempotency = `-- name: GetSmsMessageByIdempotency :one
SELECT id, client_id, direction, from_msisdn, to_msisdn, text, provider, provider_sms_id, provider_status, pdu_count, campaign_id, status, idempotency_key, created_at, accepted_at, sent_at, delivered_at, failed_at, unit_sell_price, billed_segments, tariff_plan_id, tariff_plan_code, currency, billing_action FROM sms_messages
WHERE client_id = $1::uuid
  AND idempotency_key = $2
`

type GetSmsMessageByIdempotencyParams struct {
	ClientID       uuid.UUID `json:"client_id"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

func (q *Queries) GetSmsMessageByIdempotency(ctx context.Context, arg GetSmsMessageByIdempotencyParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, getSmsMessageByIdempotency, arg.ClientID, arg.IdempotencyKey)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Direction,
		&i.FromMsisdn,
		&i.ToMsisdn,
		&i.Text,
		&i.Provider,
		&i.ProviderSmsID,
		&i.ProviderStatus,
		&i.PduCount,
		&i.CampaignID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UnitSellPrice,
		&i.BilledSegments,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.BillingAction,
	)
	return i, err
}

const getSmsMessageByProviderID = `-- name: GetSmsMessageByProviderID :one
SELECT id, client_id, direction, from_msisdn, to_msisdn, text, provider, provider_sms_id, provider_status, pdu_count, campaign_id, status, idempotency_key, created_at, accepted_at, sent_at, delivered_at, failed_at, unit_sell_price, billed_segments, tariff_plan_id, tariff_plan_code, currency, billing_action FROM sms_messages
WHERE provider_sms_id = $1
`

func (q *Queries) GetSmsMessageByProviderID(ctx context.Context, providerSmsID *string) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, getSmsMessageByProviderID, providerSmsID)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Direction,
		&i.FromMsisdn,
		&i.ToMsisdn,
		&i.Text,
		&i.Provider,
		&i.ProviderSmsID,
		&i.ProviderStatus,
		&i.PduCount,
		&i.CampaignID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UnitSellPrice,
		&i.BilledSegments,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.BillingAction,
	)
	return i, err
}

const getSmsMessageForClient = `-- name: GetSmsMessageForClient :one
SELECT id, client_id, direction, from_msisdn, to_msisdn, text, provider, provider_sms_id, provider_status, pdu_count, campaign_id, status, idempotency_key, created_at, accepted_at, sent_at, delivered_at, failed_at, unit_sell_price, billed_segments, tariff_plan_id, tariff_plan_code, currency, billing_action FROM sms_messages
WHERE id = $1 AND client_id = $2::uuid
`

type GetSmsMessageForClientParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) GetSmsMessageForClient(ctx context.Context, arg GetSmsMessageForClientParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, getSmsMessageForClient, arg.ID, arg.ClientID)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Direction,
		&i.FromMsisdn,
		&i.ToMsisdn,
		&i.Text,
		&i.Provider,
		&i.ProviderSmsID,
		&i.ProviderStatus,
		&i.PduCount,
		&i.CampaignID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UnitSellPrice,
		&i.BilledSegments,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.BillingAction,
	)
	return i, err
}

const insertInboundMessage = `-- name: InsertInboundMessage :one
INSERT INTO sms_messages (
    client_id, direction, from_msisdn, to_msisdn, text,
    provider_sms_id, pdu_count, status, accepted_at, delivered_at
) VALUES (
    $1, 'inbound', $2, $3, $4, $5, $6, 'delivered', now(), now()
)
ON CONFLICT (provider_sms_id) WHERE provider_sms_id IS NOT NULL DO NOTHING
RETURNING id, client_id, direction, from_msisdn, to_msisdn, text, provider, provider_sms_id, provider_status, pdu_count, campaign_id, status, idempotency_key, created_at, accepted_at, sent_at, delivered_at, failed_at, unit_sell_price, billed_segments, tariff_plan_id, tariff_plan_code, currency, billing_action
`

type InsertInboundMessageParams struct {
	ClientID      *uuid.UUID `json:"client_id"`
	FromMsisdn    string     `json:"from_msisdn"`
	ToMsisdn      string     `json:"to_msisdn"`
	Text          string     `json:"text"`
	ProviderSmsID *string    `json:"provider_sms_id"`
	PduCount      *int32     `json:"pdu_count"`
}

func (q *Queries) InsertInboundMessage(ctx context.Context, arg InsertInboundMessageParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, insertInboundMessage,
		arg.ClientID,
		arg.FromMsisdn,
		arg.ToMsisdn,
		arg.Text,
		arg.ProviderSmsID,
		arg.PduCount,
	)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Direction,
		&i.FromMsisdn,
		&i.ToMsisdn,
		&i.Text,
		&i.Provider,
		&i.ProviderSmsID,
		&i.ProviderStatus,
		&i.PduCount,
		&i.CampaignID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UnitSellPrice,
		&i.BilledSegments,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.BillingAction,
	)
	return i, err
}

const insertSmsMessage = `-- name: InsertSmsMessage :one
INSERT INTO sms_messages (
    client_id, direction, from_msisdn, to_msisdn, text, status, campaign_id, idempotency_key,
    unit_sell_price, billed_segments, tariff_plan_id, tariff_plan_code, currency
) VALUES (
    $1, $2, $3, $4, $5, 'queued', $6, $7,
    $8, $9, $10,
    $11, $12
)
RETURNING id, client_id, direction, from_msisdn, to_msisdn, text, provider, provider_sms_id, provider_status, pdu_count, campaign_id, status, idempotency_key, created_at, accepted_at, sent_at, delivered_at, failed_at, unit_sell_price, billed_segments, tariff_plan_id, tariff_plan_code, currency, billing_action
`

type InsertSmsMessageParams struct {
	ClientID       *uuid.UUID       `json:"client_id"`
	Direction      SmsDirection     `json:"direction"`
	FromMsisdn     string           `json:"from_msisdn"`
	ToMsisdn       string           `json:"to_msisdn"`
	Text           string           `json:"text"`
	CampaignID     *uuid.UUID       `json:"campaign_id"`
	IdempotencyKey *string          `json:"idempotency_key"`
	UnitSellPrice  *decimal.Decimal `json:"unit_sell_price"`
	BilledSegments *int32           `json:"billed_segments"`
	TariffPlanID   *uuid.UUID       `json:"tariff_plan_id"`
	TariffPlanCode *string          `json:"tariff_plan_code"`
	Currency       *string          `json:"currency"`
}

func (q *Queries) InsertSmsMessage(ctx context.Context, arg InsertSmsMessageParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, insertSmsMessage,
		arg.ClientID,
		arg.Direction,
		arg.FromMsisdn,
		arg.ToMsisdn,
		arg.Text,
		arg.CampaignID,
		arg.IdempotencyKey,
		arg.UnitSellPrice,
		arg.BilledSegments,
		arg.TariffPlanID,
		arg.TariffPlanCode,
		arg.Currency,
	)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Direction,
		&i.FromMsisdn,
		&i.ToMsisdn,
		&i.Text,
		&i.Provider,
		&i.ProviderSmsID,
		&i.ProviderStatus,
		&i.PduCount,
		&i.CampaignID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UnitSellPrice,
		&i.BilledSegments,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.BillingAction,
	)
	return i, err
}

const listSmsMessagesForClient = `-- name: ListSmsMessagesForClient :many
SELECT id, client_id, direction, from_msisdn, to_msisdn, text, provider, provider_sms_id, provider_status, pdu_count, campaign_id, status, idempotency_key, created_at, accepted_at, sent_at, delivered_at, failed_at, unit_sell_price, billed_segments, tariff_plan_id, tariff_plan_code, currency, billing_action FROM sms_messages
WHERE client_id = $1::uuid
  AND ($2::sms_direction IS NULL OR direction = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListSmsMessagesForClientParams struct {
	ClientID   uuid.UUID        `json:"client_id"`
	Direction  NullSmsDirection `json:"direction"`
	PageOffset int32            `json:"page_offset"`
	PageLimit  int32            `json:"page_limit"`
}

func (q *Queries) ListSmsMessagesForClient(ctx context.Context, arg ListSmsMessagesForClientParams) ([]SmsMessage, error) {
	rows, err := q.db.Query(ctx, listSmsMessagesForClient,
		arg.ClientID,
		arg.Direction,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmsMessage
	for rows.Next() {
		var i SmsMessage
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.Text,
			&i.Provider,
			&i.ProviderSmsID,
			&i.ProviderStatus,
			&i.PduCount,
			&i.CampaignID,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.AcceptedAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.UnitSellPrice,
			&i.BilledSegments,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.BillingAction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleOutbound = `-- name: ListStaleOutbound :many
SELECT id, client_id, direction, from_msisdn, to_msisdn, text, provider, provider_sms_id, provider_status, pdu_count, campaign_id, status, idempotency_key, created_at, accepted_at, sent_at, delivered_at, failed_at, unit_sell_price, billed_segments, tariff_plan_id, tariff_plan_code, currency, billing_action FROM sms_messages
WHERE direction = 'outbound'
  AND status IN ('accepted', 'sent')
  AND created_at < $1
ORDER BY created_at
LIMIT $2
`

type ListStaleOutboundParams struct {
	Before    time.Time `json:"before"`
	PageLimit int32     `json:"page_limit"`
}

func (q *Queries) ListStaleOutbound(ctx context.Context, arg ListStaleOutboundParams) ([]SmsMessage, error) {
	rows, err := q.db.Query(ctx, listStaleOutbound, arg.Before, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmsMessage
	for rows.Next() {
		var i SmsMessage
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Direction,
			&i.FromMsisdn,
			&i.ToMsisdn,
			&i.Text,
			&i.Provider,
			&i.ProviderSmsID,
			&i.ProviderStatus,
			&i.PduCount,
			&i.CampaignID,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.AcceptedAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.UnitSellPrice,
			&i.BilledSegments,
			&i.TariffPlanID,
			&i.TariffPlanCode,
			&i.Currency,
			&i.BillingAction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSmsMessageAccepted = `-- name: UpdateSmsMessageAccepted :one
UPDATE sms_messages
SET status = 'accepted',
    provider_sms_id = COALESCE($1, provider_sms_id),
    pdu_count = COALESCE($2, pdu_count),
    accepted_at = COALESCE(accepted_at, now())
WHERE id = $3
  AND status IN ('queued', 'accepted')
RETURNING id, client_id, direction, from_msisdn, to_msisdn, text, provider, provider_sms_id, provider_status, pdu_count, campaign_id, status, idempotency_key, created_at, accepted_at, sent_at, delivered_at, failed_at, unit_sell_price, billed_segments, tariff_plan_id, tariff_plan_code, currency, billing_action
`

type UpdateSmsMessageAcceptedParams struct {
	ProviderSmsID *string   `json:"provider_sms_id"`
	PduCount      *int32    `json:"pdu_count"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateSmsMessageAccepted(ctx context.Context, arg UpdateSmsMessageAcceptedParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, updateSmsMessageAccepted, arg.ProviderSmsID, arg.PduCount, arg.ID)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Direction,
		&i.FromMsisdn,
		&i.ToMsisdn,
		&i.Text,
		&i.Provider,
		&i.ProviderSmsID,
		&i.ProviderStatus,
		&i.PduCount,
		&i.CampaignID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UnitSellPrice,
		&i.BilledSegments,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.BillingAction,
	)
	return i, err
}

const updateSmsMessageFailed = `-- name: UpdateSmsMessageFailed :one
UPDATE sms_messages
SET status = 'failed',
    provider_status = $1,
    failed_at = COALESCE(failed_at, now())
WHERE id = $2
  AND status IN ('queued', 'accepted', 'sent')
RETURNING id, client_id, direction, from_msisdn, to_msisdn, text, provider, provider_sms_id, provider_status, pdu_count, campaign_id, status, idempotency_key, created_at, accepted_at, sent_at, delivered_at, failed_at, unit_sell_price, billed_segments, tariff_plan_id, tariff_plan_code, currency, billing_action
`

type UpdateSmsMessageFailedParams struct {
	ProviderStatus *string   `json:"provider_status"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) UpdateSmsMessageFailed(ctx context.Context, arg UpdateSmsMessageFailedParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, updateSmsMessageFailed, arg.ProviderStatus, arg.ID)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Direction,
		&i.FromMsisdn,
		&i.ToMsisdn,
		&i.Text,
		&i.Provider,
		&i.ProviderSmsID,
		&i.ProviderStatus,
		&i.PduCount,
		&i.CampaignID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UnitSellPrice,
		&i.BilledSegments,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.BillingAction,
	)
	return i, err
}

const updateSmsMessageFromStatistic = `-- name: UpdateSmsMessageFromStatistic :one
UPDATE sms_messages
SET
    provider_sms_id = COALESCE(sms_messages.provider_sms_id, $1),
    provider_status = COALESCE($2, provider_status),
    pdu_count = COALESCE($3, pdu_count),
    status = CASE
        WHEN $4::boolean THEN 'delivered'::sms_status
        WHEN $5::boolean THEN 'sent'::sms_status
        ELSE 'accepted'::sms_status
    END,
    accepted_at = COALESCE(accepted_at, now()),
    sent_at = CASE
        WHEN $5::boolean OR $4::boolean THEN COALESCE(sent_at, now())
        ELSE sent_at
    END,
    delivered_at = CASE
        WHEN $4::boolean THEN COALESCE(delivered_at, now())
        ELSE delivered_at
    END
WHERE id = $6
  AND status IN ('queued', 'accepted', 'sent')
RETURNING id, client_id, direction, from_msisdn, to_msisdn, text, provider, provider_sms_id, provider_status, pdu_count, campaign_id, status, idempotency_key, created_at, accepted_at, sent_at, delivered_at, failed_at, unit_sell_price, billed_segments, tariff_plan_id, tariff_plan_code, currency, billing_action
`

type UpdateSmsMessageFromStatisticParams struct {
	ProviderSmsID  *string   `json:"provider_sms_id"`
	ProviderStatus *string   `json:"provider_status"`
	PduCount       *int32    `json:"pdu_count"`
	Delivered      bool      `json:"delivered"`
	Sent           bool      `json:"sent"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) UpdateSmsMessageFromStatistic(ctx context.Context, arg UpdateSmsMessageFromStatisticParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, updateSmsMessageFromStatistic,
		arg.ProviderSmsID,
		arg.ProviderStatus,
		arg.PduCount,
		arg.Delivered,
		arg.Sent,
		arg.ID,
	)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Direction,
		&i.FromMsisdn,
		&i.ToMsisdn,
		&i.Text,
		&i.Provider,
		&i.ProviderSmsID,
		&i.ProviderStatus,
		&i.PduCount,
		&i.CampaignID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UnitSellPrice,
		&i.BilledSegments,
		&i.TariffPlanID,
		&i.TariffPlanCode,
		&i.Currency,
		&i.BillingAction,
	)
	return i, err
}
