// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package sqlcdb

import (
	"context"
	"time"
)

const countSendJobsByStatus = `-- name: CountSendJobsByStatus :many
SELECT status, count(*)::bigint AS n
FROM send_jobs
GROUP BY status
`

type CountSendJobsByStatusRow struct {
	Status SendJobStatus `json:"status"`
	N      int64         `json:"n"`
}

func (q *Queries) CountSendJobsByStatus(ctx context.Context) ([]CountSendJobsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countSendJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSendJobsByStatusRow
	for rows.Next() {
		var i CountSendJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSmsMessagesByStatus = `-- name: CountSmsMessagesByStatus :many
SELECT status, count(*)::bigint AS n
FROM sms_messages
GROUP BY status
`

type CountSmsMessagesByStatusRow struct {
	Status SmsStatus `json:"status"`
	N      int64     `json:"n"`
}

func (q *Queries) CountSmsMessagesByStatus(ctx context.Context) ([]CountSmsMessagesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countSmsMessagesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSmsMessagesByStatusRow
	for rows.Next() {
		var i CountSmsMessagesByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnprocessedCallbacks = `-- name: CountUnprocessedCallbacks :one
SELECT count(*)::bigint AS n
FROM provider_callback_events
WHERE processed_at IS NULL
`

func (q *Queries) CountUnprocessedCallbacks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnprocessedCallbacks)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countLookupItemsByStatus = `-- name: CountLookupItemsByStatus :many
SELECT status, count(*)::bigint AS n
FROM lookup_items
GROUP BY status
`

type CountLookupItemsByStatusRow struct {
	Status LookupItemStatus `json:"status"`
	N      int64            `json:"n"`
}

func (q *Queries) CountLookupItemsByStatus(ctx context.Context) ([]CountLookupItemsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countLookupItemsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountLookupItemsByStatusRow
	for rows.Next() {
		var i CountLookupItemsByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLookupJobsByStatus = `-- name: CountLookupJobsByStatus :many
SELECT status, count(*)::bigint AS n
FROM lookup_jobs
GROUP BY status
`

type CountLookupJobsByStatusRow struct {
	Status LookupJobStatus `json:"status"`
	N      int64           `json:"n"`
}

func (q *Queries) CountLookupJobsByStatus(ctx context.Context) ([]CountLookupJobsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countLookupJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountLookupJobsByStatusRow
	for rows.Next() {
		var i CountLookupJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestUnprocessedLookupCallbackAt = `-- name: OldestUnprocessedLookupCallbackAt :one
SELECT min(created_at) AS created_at
FROM provider_lookup_callbacks
WHERE processed_at IS NULL
`

func (q *Queries) OldestUnprocessedLookupCallbackAt(ctx context.Context) (*time.Time, error) {
	row := q.db.QueryRow(ctx, oldestUnprocessedLookupCallbackAt)
	var createdAt *time.Time
	err := row.Scan(&createdAt)
	return createdAt, err
}
