// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type ActorType string

const (
	ActorTypeAdmin      ActorType = "admin"
	ActorTypeClientUser ActorType = "client_user"
	ActorTypeApiKey     ActorType = "api_key"
	ActorTypeSystem     ActorType = "system"
)

func (e *ActorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActorType(s)
	case string:
		*e = ActorType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActorType: %T", src)
	}
	return nil
}

type NullActorType struct {
	ActorType ActorType `json:"actor_type"`
	Valid     bool      `json:"valid"` // Valid is true if ActorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActorType) Scan(value interface{}) error {
	if value == nil {
		ns.ActorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActorType), nil
}

type BillingAction string

const (
	BillingActionCapture BillingAction = "capture"
	BillingActionRelease BillingAction = "release"
)

func (e *BillingAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingAction(s)
	case string:
		*e = BillingAction(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingAction: %T", src)
	}
	return nil
}

type NullBillingAction struct {
	BillingAction BillingAction `json:"billing_action"`
	Valid         bool          `json:"valid"` // Valid is true if BillingAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingAction) Scan(value interface{}) error {
	if value == nil {
		ns.BillingAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingAction), nil
}

type BillingProduct string

const (
	BillingProductSmsDomestic      BillingProduct = "sms_domestic"
	BillingProductSmsInternational BillingProduct = "sms_international"
	BillingProductHlr              BillingProduct = "hlr"
	BillingProductSilentSms        BillingProduct = "silent_sms"
)

func (e *BillingProduct) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingProduct(s)
	case string:
		*e = BillingProduct(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingProduct: %T", src)
	}
	return nil
}

type NullBillingProduct struct {
	BillingProduct BillingProduct `json:"billing_product"`
	Valid          bool           `json:"valid"` // Valid is true if BillingProduct is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingProduct) Scan(value interface{}) error {
	if value == nil {
		ns.BillingProduct, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingProduct.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingProduct) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingProduct), nil
}

type CallbackKind string

const (
	CallbackKindDlr CallbackKind = "dlr"
	CallbackKindMo  CallbackKind = "mo"
)

func (e *CallbackKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CallbackKind(s)
	case string:
		*e = CallbackKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CallbackKind: %T", src)
	}
	return nil
}

type NullCallbackKind struct {
	CallbackKind CallbackKind `json:"callback_kind"`
	Valid        bool         `json:"valid"` // Valid is true if CallbackKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCallbackKind) Scan(value interface{}) error {
	if value == nil {
		ns.CallbackKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CallbackKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCallbackKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CallbackKind), nil
}

type CampaignRecipientStatus string

const (
	CampaignRecipientStatusPending  CampaignRecipientStatus = "pending"
	CampaignRecipientStatusEnqueued CampaignRecipientStatus = "enqueued"
	CampaignRecipientStatusSkipped  CampaignRecipientStatus = "skipped"
	CampaignRecipientStatusFailed   CampaignRecipientStatus = "failed"
)

func (e *CampaignRecipientStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CampaignRecipientStatus(s)
	case string:
		*e = CampaignRecipientStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CampaignRecipientStatus: %T", src)
	}
	return nil
}

type NullCampaignRecipientStatus struct {
	CampaignRecipientStatus CampaignRecipientStatus `json:"campaign_recipient_status"`
	Valid                   bool                    `json:"valid"` // Valid is true if CampaignRecipientStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCampaignRecipientStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CampaignRecipientStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CampaignRecipientStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCampaignRecipientStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CampaignRecipientStatus), nil
}

type CampaignStatus string

const (
	CampaignStatusDraft     CampaignStatus = "draft"
	CampaignStatusQueued    CampaignStatus = "queued"
	CampaignStatusRunning   CampaignStatus = "running"
	CampaignStatusCompleted CampaignStatus = "completed"
	CampaignStatusFailed    CampaignStatus = "failed"
	CampaignStatusCancelled CampaignStatus = "cancelled"
)

func (e *CampaignStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CampaignStatus(s)
	case string:
		*e = CampaignStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CampaignStatus: %T", src)
	}
	return nil
}

type NullCampaignStatus struct {
	CampaignStatus CampaignStatus `json:"campaign_status"`
	Valid          bool           `json:"valid"` // Valid is true if CampaignStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCampaignStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CampaignStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CampaignStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCampaignStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CampaignStatus), nil
}

type ClientStatus string

const (
	ClientStatusActive    ClientStatus = "active"
	ClientStatusSuspended ClientStatus = "suspended"
	ClientStatusDeleted   ClientStatus = "deleted"
)

func (e *ClientStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClientStatus(s)
	case string:
		*e = ClientStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ClientStatus: %T", src)
	}
	return nil
}

type NullClientStatus struct {
	ClientStatus ClientStatus `json:"client_status"`
	Valid        bool         `json:"valid"` // Valid is true if ClientStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClientStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ClientStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClientStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClientStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClientStatus), nil
}

type ClientUserRole string

const (
	ClientUserRoleOwner ClientUserRole = "owner"
)

func (e *ClientUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClientUserRole(s)
	case string:
		*e = ClientUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ClientUserRole: %T", src)
	}
	return nil
}

type NullClientUserRole struct {
	ClientUserRole ClientUserRole `json:"client_user_role"`
	Valid          bool           `json:"valid"` // Valid is true if ClientUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClientUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.ClientUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClientUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClientUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClientUserRole), nil
}

type CredentialStatus string

const (
	CredentialStatusActive  CredentialStatus = "active"
	CredentialStatusRevoked CredentialStatus = "revoked"
)

func (e *CredentialStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CredentialStatus(s)
	case string:
		*e = CredentialStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CredentialStatus: %T", src)
	}
	return nil
}

type NullCredentialStatus struct {
	CredentialStatus CredentialStatus `json:"credential_status"`
	Valid            bool             `json:"valid"` // Valid is true if CredentialStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCredentialStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CredentialStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CredentialStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCredentialStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CredentialStatus), nil
}

type DefNumberStatus string

const (
	DefNumberStatusInventory DefNumberStatus = "inventory"
	DefNumberStatusAssigned  DefNumberStatus = "assigned"
	DefNumberStatusDisabled  DefNumberStatus = "disabled"
)

func (e *DefNumberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DefNumberStatus(s)
	case string:
		*e = DefNumberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DefNumberStatus: %T", src)
	}
	return nil
}

type NullDefNumberStatus struct {
	DefNumberStatus DefNumberStatus `json:"def_number_status"`
	Valid           bool            `json:"valid"` // Valid is true if DefNumberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDefNumberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DefNumberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DefNumberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDefNumberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DefNumberStatus), nil
}

type DirectionJobStatus string

const (
	DirectionJobStatusPending    DirectionJobStatus = "pending"
	DirectionJobStatusProcessing DirectionJobStatus = "processing"
	DirectionJobStatusDone       DirectionJobStatus = "done"
	DirectionJobStatusRetry      DirectionJobStatus = "retry"
	DirectionJobStatusDead       DirectionJobStatus = "dead"
)

func (e *DirectionJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DirectionJobStatus(s)
	case string:
		*e = DirectionJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DirectionJobStatus: %T", src)
	}
	return nil
}

type NullDirectionJobStatus struct {
	DirectionJobStatus DirectionJobStatus `json:"direction_job_status"`
	Valid              bool               `json:"valid"` // Valid is true if DirectionJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDirectionJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DirectionJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DirectionJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDirectionJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DirectionJobStatus), nil
}

type LookupCheckType string

const (
	LookupCheckTypeHlr  LookupCheckType = "hlr"
	LookupCheckTypePing LookupCheckType = "ping"
)

func (e *LookupCheckType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LookupCheckType(s)
	case string:
		*e = LookupCheckType(s)
	default:
		return fmt.Errorf("unsupported scan type for LookupCheckType: %T", src)
	}
	return nil
}

type NullLookupCheckType struct {
	LookupCheckType LookupCheckType `json:"lookup_check_type"`
	Valid           bool            `json:"valid"` // Valid is true if LookupCheckType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLookupCheckType) Scan(value interface{}) error {
	if value == nil {
		ns.LookupCheckType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LookupCheckType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLookupCheckType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LookupCheckType), nil
}

type LookupCsvPreviewStatus string

const (
	LookupCsvPreviewStatusReady     LookupCsvPreviewStatus = "ready"
	LookupCsvPreviewStatusInvalid   LookupCsvPreviewStatus = "invalid"
	LookupCsvPreviewStatusConsuming LookupCsvPreviewStatus = "consuming"
	LookupCsvPreviewStatusConsumed  LookupCsvPreviewStatus = "consumed"
	LookupCsvPreviewStatusExpired   LookupCsvPreviewStatus = "expired"
)

func (e *LookupCsvPreviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LookupCsvPreviewStatus(s)
	case string:
		*e = LookupCsvPreviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LookupCsvPreviewStatus: %T", src)
	}
	return nil
}

type NullLookupCsvPreviewStatus struct {
	LookupCsvPreviewStatus LookupCsvPreviewStatus `json:"lookup_csv_preview_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if LookupCsvPreviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLookupCsvPreviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LookupCsvPreviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LookupCsvPreviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLookupCsvPreviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LookupCsvPreviewStatus), nil
}

type LookupItemStatus string

const (
	LookupItemStatusQueued    LookupItemStatus = "queued"
	LookupItemStatusReserved  LookupItemStatus = "reserved"
	LookupItemStatusPending   LookupItemStatus = "pending"
	LookupItemStatusCompleted LookupItemStatus = "completed"
	LookupItemStatusFailed    LookupItemStatus = "failed"
)

func (e *LookupItemStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LookupItemStatus(s)
	case string:
		*e = LookupItemStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LookupItemStatus: %T", src)
	}
	return nil
}

type NullLookupItemStatus struct {
	LookupItemStatus LookupItemStatus `json:"lookup_item_status"`
	Valid            bool             `json:"valid"` // Valid is true if LookupItemStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLookupItemStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LookupItemStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LookupItemStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLookupItemStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LookupItemStatus), nil
}

type LookupJobSource string

const (
	LookupJobSourceSingle LookupJobSource = "single"
	LookupJobSourceBulk   LookupJobSource = "bulk"
	LookupJobSourceApi    LookupJobSource = "api"
)

func (e *LookupJobSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LookupJobSource(s)
	case string:
		*e = LookupJobSource(s)
	default:
		return fmt.Errorf("unsupported scan type for LookupJobSource: %T", src)
	}
	return nil
}

type NullLookupJobSource struct {
	LookupJobSource LookupJobSource `json:"lookup_job_source"`
	Valid           bool            `json:"valid"` // Valid is true if LookupJobSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLookupJobSource) Scan(value interface{}) error {
	if value == nil {
		ns.LookupJobSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LookupJobSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLookupJobSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LookupJobSource), nil
}

type LookupJobStatus string

const (
	LookupJobStatusQueued              LookupJobStatus = "queued"
	LookupJobStatusProcessing          LookupJobStatus = "processing"
	LookupJobStatusCompleted           LookupJobStatus = "completed"
	LookupJobStatusCompletedWithErrors LookupJobStatus = "completed_with_errors"
	LookupJobStatusFailed              LookupJobStatus = "failed"
)

func (e *LookupJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LookupJobStatus(s)
	case string:
		*e = LookupJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LookupJobStatus: %T", src)
	}
	return nil
}

type NullLookupJobStatus struct {
	LookupJobStatus LookupJobStatus `json:"lookup_job_status"`
	Valid           bool            `json:"valid"` // Valid is true if LookupJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLookupJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LookupJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LookupJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLookupJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LookupJobStatus), nil
}

type ProviderLookupKind string

const (
	ProviderLookupKindSend    ProviderLookupKind = "send"
	ProviderLookupKindStatus  ProviderLookupKind = "status"
	ProviderLookupKindCost    ProviderLookupKind = "cost"
	ProviderLookupKindBalance ProviderLookupKind = "balance"
)

func (e *ProviderLookupKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderLookupKind(s)
	case string:
		*e = ProviderLookupKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderLookupKind: %T", src)
	}
	return nil
}

type NullProviderLookupKind struct {
	ProviderLookupKind ProviderLookupKind `json:"provider_lookup_kind"`
	Valid              bool               `json:"valid"` // Valid is true if ProviderLookupKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderLookupKind) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderLookupKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderLookupKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderLookupKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderLookupKind), nil
}

type ProviderLookupRequestStatus string

const (
	ProviderLookupRequestStatusPending   ProviderLookupRequestStatus = "pending"
	ProviderLookupRequestStatusSucceeded ProviderLookupRequestStatus = "succeeded"
	ProviderLookupRequestStatusFailed    ProviderLookupRequestStatus = "failed"
)

func (e *ProviderLookupRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderLookupRequestStatus(s)
	case string:
		*e = ProviderLookupRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderLookupRequestStatus: %T", src)
	}
	return nil
}

type NullProviderLookupRequestStatus struct {
	ProviderLookupRequestStatus ProviderLookupRequestStatus `json:"provider_lookup_request_status"`
	Valid                       bool                        `json:"valid"` // Valid is true if ProviderLookupRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderLookupRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderLookupRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderLookupRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderLookupRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderLookupRequestStatus), nil
}

type SendAttemptKind string

const (
	SendAttemptKindAccepted    SendAttemptKind = "accepted"
	SendAttemptKindRejected4xx SendAttemptKind = "rejected_4xx"
	SendAttemptKindRateLimited SendAttemptKind = "rate_limited"
	SendAttemptKindTimeout     SendAttemptKind = "timeout"
	SendAttemptKind5xx         SendAttemptKind = "5xx"
)

func (e *SendAttemptKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SendAttemptKind(s)
	case string:
		*e = SendAttemptKind(s)
	default:
		return fmt.Errorf("unsupported scan type for SendAttemptKind: %T", src)
	}
	return nil
}

type NullSendAttemptKind struct {
	SendAttemptKind SendAttemptKind `json:"send_attempt_kind"`
	Valid           bool            `json:"valid"` // Valid is true if SendAttemptKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSendAttemptKind) Scan(value interface{}) error {
	if value == nil {
		ns.SendAttemptKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SendAttemptKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSendAttemptKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SendAttemptKind), nil
}

type SendJobStatus string

const (
	SendJobStatusPending    SendJobStatus = "pending"
	SendJobStatusProcessing SendJobStatus = "processing"
	SendJobStatusDone       SendJobStatus = "done"
	SendJobStatusRetry      SendJobStatus = "retry"
	SendJobStatusUncertain  SendJobStatus = "uncertain"
	SendJobStatusDead       SendJobStatus = "dead"
)

func (e *SendJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SendJobStatus(s)
	case string:
		*e = SendJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SendJobStatus: %T", src)
	}
	return nil
}

type NullSendJobStatus struct {
	SendJobStatus SendJobStatus `json:"send_job_status"`
	Valid         bool          `json:"valid"` // Valid is true if SendJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSendJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SendJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SendJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSendJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SendJobStatus), nil
}

type SessionAudience string

const (
	SessionAudienceAdmin  SessionAudience = "admin"
	SessionAudienceClient SessionAudience = "client"
)

func (e *SessionAudience) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionAudience(s)
	case string:
		*e = SessionAudience(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionAudience: %T", src)
	}
	return nil
}

type NullSessionAudience struct {
	SessionAudience SessionAudience `json:"session_audience"`
	Valid           bool            `json:"valid"` // Valid is true if SessionAudience is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionAudience) Scan(value interface{}) error {
	if value == nil {
		ns.SessionAudience, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionAudience.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionAudience) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionAudience), nil
}

type SmsDirection string

const (
	SmsDirectionOutbound SmsDirection = "outbound"
	SmsDirectionInbound  SmsDirection = "inbound"
)

func (e *SmsDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SmsDirection(s)
	case string:
		*e = SmsDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for SmsDirection: %T", src)
	}
	return nil
}

type NullSmsDirection struct {
	SmsDirection SmsDirection `json:"sms_direction"`
	Valid        bool         `json:"valid"` // Valid is true if SmsDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSmsDirection) Scan(value interface{}) error {
	if value == nil {
		ns.SmsDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SmsDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSmsDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SmsDirection), nil
}

type SmsStatus string

const (
	SmsStatusQueued    SmsStatus = "queued"
	SmsStatusAccepted  SmsStatus = "accepted"
	SmsStatusSent      SmsStatus = "sent"
	SmsStatusDelivered SmsStatus = "delivered"
	SmsStatusFailed    SmsStatus = "failed"
)

func (e *SmsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SmsStatus(s)
	case string:
		*e = SmsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SmsStatus: %T", src)
	}
	return nil
}

type NullSmsStatus struct {
	SmsStatus SmsStatus `json:"sms_status"`
	Valid     bool      `json:"valid"` // Valid is true if SmsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSmsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SmsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SmsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSmsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SmsStatus), nil
}

type UserStatus string

const (
	UserStatusActive   UserStatus = "active"
	UserStatusDisabled UserStatus = "disabled"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type WalletTxType string

const (
	WalletTxTypeCREDIT     WalletTxType = "CREDIT"
	WalletTxTypeHOLD       WalletTxType = "HOLD"
	WalletTxTypeDEBIT      WalletTxType = "DEBIT"
	WalletTxTypeRELEASE    WalletTxType = "RELEASE"
	WalletTxTypeADJUSTMENT WalletTxType = "ADJUSTMENT"
)

func (e *WalletTxType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletTxType(s)
	case string:
		*e = WalletTxType(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletTxType: %T", src)
	}
	return nil
}

type NullWalletTxType struct {
	WalletTxType WalletTxType `json:"wallet_tx_type"`
	Valid        bool         `json:"valid"` // Valid is true if WalletTxType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletTxType) Scan(value interface{}) error {
	if value == nil {
		ns.WalletTxType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletTxType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletTxType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletTxType), nil
}

type WebhookDeliveryStatus string

const (
	WebhookDeliveryStatusPending   WebhookDeliveryStatus = "pending"
	WebhookDeliveryStatusDelivered WebhookDeliveryStatus = "delivered"
	WebhookDeliveryStatusFailed    WebhookDeliveryStatus = "failed"
	WebhookDeliveryStatusDead      WebhookDeliveryStatus = "dead"
)

func (e *WebhookDeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookDeliveryStatus(s)
	case string:
		*e = WebhookDeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookDeliveryStatus: %T", src)
	}
	return nil
}

type NullWebhookDeliveryStatus struct {
	WebhookDeliveryStatus WebhookDeliveryStatus `json:"webhook_delivery_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if WebhookDeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookDeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookDeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookDeliveryStatus), nil
}

type AdminUser struct {
	ID           uuid.UUID  `json:"id"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	Name         string     `json:"name"`
	Status       UserStatus `json:"status"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

type ApiCredential struct {
	ID           uuid.UUID        `json:"id"`
	ClientID     uuid.UUID        `json:"client_id"`
	Name         string           `json:"name"`
	KeyPrefix    string           `json:"key_prefix"`
	SecretHash   string           `json:"secret_hash"`
	Scopes       []string         `json:"scopes"`
	Status       CredentialStatus `json:"status"`
	AllowedCidrs []netip.Addr     `json:"allowed_cidrs"`
	LastUsedAt   *time.Time       `json:"last_used_at"`
	CreatedBy    *uuid.UUID       `json:"created_by"`
	CreatedAt    time.Time        `json:"created_at"`
}

type AuditLog struct {
	ID           uuid.UUID   `json:"id"`
	ActorType    ActorType   `json:"actor_type"`
	ActorID      *uuid.UUID  `json:"actor_id"`
	ClientID     *uuid.UUID  `json:"client_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   *uuid.UUID  `json:"resource_id"`
	Ip           *netip.Addr `json:"ip"`
	UserAgent    *string     `json:"user_agent"`
	Metadata     []byte      `json:"metadata"`
	CreatedAt    time.Time   `json:"created_at"`
}

type CampaignRecipient struct {
	ID           uuid.UUID               `json:"id"`
	CampaignID   uuid.UUID               `json:"campaign_id"`
	ToMsisdn     string                  `json:"to_msisdn"`
	Status       CampaignRecipientStatus `json:"status"`
	SmsMessageID *uuid.UUID              `json:"sms_message_id"`
	CreatedAt    time.Time               `json:"created_at"`
}

type Client struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Status    ClientStatus `json:"status"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type ClientTariff struct {
	ID            uuid.UUID        `json:"id"`
	ClientID      uuid.UUID        `json:"client_id"`
	Product       BillingProduct   `json:"product"`
	TariffPlanID  uuid.UUID        `json:"tariff_plan_id"`
	PriceOverride *decimal.Decimal `json:"price_override"`
	EffectiveFrom time.Time        `json:"effective_from"`
	EffectiveTo   *time.Time       `json:"effective_to"`
	CreatedAt     time.Time        `json:"created_at"`
	UpdatedAt     time.Time        `json:"updated_at"`
}

type ClientUser struct {
	ID           uuid.UUID      `json:"id"`
	ClientID     uuid.UUID      `json:"client_id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Role         ClientUserRole `json:"role"`
	Status       UserStatus     `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	Name         string         `json:"name"`
}

type DefNumber struct {
	ID              uuid.UUID       `json:"id"`
	Msisdn          string          `json:"msisdn"`
	Status          DefNumberStatus `json:"status"`
	Region          *string         `json:"region"`
	Notes           *string         `json:"notes"`
	SupportsSms     bool            `json:"supports_sms"`
	RunexisSnapshot []byte          `json:"runexis_snapshot"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type IdempotencyKey struct {
	ID             uuid.UUID `json:"id"`
	PrincipalType  ActorType `json:"principal_type"`
	PrincipalID    uuid.UUID `json:"principal_id"`
	Key            string    `json:"key"`
	RequestHash    string    `json:"request_hash"`
	ResponseStatus *int32    `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
	ExpiresAt      time.Time `json:"expires_at"`
	CreatedAt      time.Time `json:"created_at"`
}

type LookupCsvPreview struct {
	ID               uuid.UUID              `json:"id"`
	ClientID         uuid.UUID              `json:"client_id"`
	CheckType        LookupCheckType        `json:"check_type"`
	Status           LookupCsvPreviewStatus `json:"status"`
	OriginalFilename *string                `json:"original_filename"`
	PhoneCount       int32                  `json:"phone_count"`
	PhonesJson       []byte                 `json:"phones_json"`
	ErrorMessage     *string                `json:"error_message"`
	JobID            *uuid.UUID             `json:"job_id"`
	ExpiresAt        time.Time              `json:"expires_at"`
	CreatedAt        time.Time              `json:"created_at"`
	UpdatedAt        time.Time              `json:"updated_at"`
}

type LookupItem struct {
	ID                uuid.UUID         `json:"id"`
	JobID             uuid.UUID         `json:"job_id"`
	ClientID          uuid.UUID         `json:"client_id"`
	CheckType         LookupCheckType   `json:"check_type"`
	Status            LookupItemStatus  `json:"status"`
	PhoneE164         string            `json:"phone_e164"`
	PhoneDigits       string            `json:"phone_digits"`
	ProviderCode      string            `json:"provider_code"`
	ProviderMessageID *string           `json:"provider_message_id"`
	UnitSellPrice     *decimal.Decimal  `json:"unit_sell_price"`
	TariffPlanID      *uuid.UUID        `json:"tariff_plan_id"`
	TariffPlanCode    *string           `json:"tariff_plan_code"`
	Currency          *string           `json:"currency"`
	EstimatedCost     *decimal.Decimal  `json:"estimated_cost"`
	ActualCost        *decimal.Decimal  `json:"actual_cost"`
	ResultStatus      *string           `json:"result_status"`
	IsReachable       *bool             `json:"is_reachable"`
	Imsi              *string           `json:"imsi"`
	Mcc               *string           `json:"mcc"`
	Mnc               *string           `json:"mnc"`
	OperatorName      *string           `json:"operator_name"`
	CountryCode       *string           `json:"country_code"`
	Ported            *bool             `json:"ported"`
	Roaming           *bool             `json:"roaming"`
	NormalizedResult  []byte            `json:"normalized_result"`
	ErrorCode         *string           `json:"error_code"`
	ErrorMessage      *string           `json:"error_message"`
	BillingAction     NullBillingAction `json:"billing_action"`
	NextPollAt        *time.Time        `json:"next_poll_at"`
	PollAttempts      int32             `json:"poll_attempts"`
	SentAt            *time.Time        `json:"sent_at"`
	CompletedAt       *time.Time        `json:"completed_at"`
	CreatedAt         time.Time         `json:"created_at"`
	UpdatedAt         time.Time         `json:"updated_at"`
	EnrichAttempts    int32             `json:"enrich_attempts"`
}

type LookupJob struct {
	ID               uuid.UUID        `json:"id"`
	ClientID         uuid.UUID        `json:"client_id"`
	CheckType        LookupCheckType  `json:"check_type"`
	Source           LookupJobSource  `json:"source"`
	Status           LookupJobStatus  `json:"status"`
	ItemCount        int32            `json:"item_count"`
	SuccessCount     int32            `json:"success_count"`
	FailureCount     int32            `json:"failure_count"`
	UnitSellPrice    *decimal.Decimal `json:"unit_sell_price"`
	TariffPlanID     *uuid.UUID       `json:"tariff_plan_id"`
	TariffPlanCode   *string          `json:"tariff_plan_code"`
	Currency         string           `json:"currency"`
	EstimatedCost    *decimal.Decimal `json:"estimated_cost"`
	ActualCost       *decimal.Decimal `json:"actual_cost"`
	OriginalFilename *string          `json:"original_filename"`
	IdempotencyKey   *string          `json:"idempotency_key"`
	CreatedBy        *uuid.UUID       `json:"created_by"`
	ApiCredentialID  *uuid.UUID       `json:"api_credential_id"`
	ErrorCode        *string          `json:"error_code"`
	ErrorMessage     *string          `json:"error_message"`
	StartedAt        *time.Time       `json:"started_at"`
	CompletedAt      *time.Time       `json:"completed_at"`
	Metadata         []byte           `json:"metadata"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
	ReachableCount   int32            `json:"reachable_count"`
	UnreachableCount int32            `json:"unreachable_count"`
}

type NumberAssignment struct {
	ID           uuid.UUID  `json:"id"`
	DefNumberID  uuid.UUID  `json:"def_number_id"`
	ClientID     uuid.UUID  `json:"client_id"`
	AssignedAt   time.Time  `json:"assigned_at"`
	UnassignedAt *time.Time `json:"unassigned_at"`
	AssignedBy   *uuid.UUID `json:"assigned_by"`
}

type NumberDirectionJob struct {
	ID           uuid.UUID          `json:"id"`
	DefNumberID  uuid.UUID          `json:"def_number_id"`
	AssignmentID *uuid.UUID         `json:"assignment_id"`
	Msisdn       string             `json:"msisdn"`
	DirIn        bool               `json:"dir_in"`
	DirDomOut    bool               `json:"dir_dom_out"`
	DirIntOut    bool               `json:"dir_int_out"`
	DirInMass    bool               `json:"dir_in_mass"`
	Status       DirectionJobStatus `json:"status"`
	Attempt      int32              `json:"attempt"`
	AvailableAt  time.Time          `json:"available_at"`
	LockedAt     *time.Time         `json:"locked_at"`
	LockedBy     *string            `json:"locked_by"`
	LastError    *string            `json:"last_error"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type OpsEvent struct {
	ID           uuid.UUID     `json:"id"`
	CreatedAt    time.Time     `json:"created_at"`
	Category     string        `json:"category"`
	Level        string        `json:"level"`
	RequestID    *string       `json:"request_id"`
	ActorType    NullActorType `json:"actor_type"`
	ActorID      *uuid.UUID    `json:"actor_id"`
	ClientID     *uuid.UUID    `json:"client_id"`
	Action       string        `json:"action"`
	ResourceType *string       `json:"resource_type"`
	ResourceID   *uuid.UUID    `json:"resource_id"`
	HttpMethod   *string       `json:"http_method"`
	HttpPath     *string       `json:"http_path"`
	HttpStatus   *int32        `json:"http_status"`
	LatencyMs    *int32        `json:"latency_ms"`
	Summary      *string       `json:"summary"`
	Detail       []byte        `json:"detail"`
	Error        *string       `json:"error"`
	Ip           *netip.Addr   `json:"ip"`
}

type ProviderCallbackEvent struct {
	ID             uuid.UUID    `json:"id"`
	Kind           CallbackKind `json:"kind"`
	IdempotencyKey string       `json:"idempotency_key"`
	Method         string       `json:"method"`
	Path           string       `json:"path"`
	Query          *string      `json:"query"`
	Headers        []byte       `json:"headers"`
	RawBody        []byte       `json:"raw_body"`
	ContentType    *string      `json:"content_type"`
	Parsed         []byte       `json:"parsed"`
	SmsMessageID   *uuid.UUID   `json:"sms_message_id"`
	ProcessedAt    *time.Time   `json:"processed_at"`
	CreatedAt      time.Time    `json:"created_at"`
}

type ProviderLookupCallback struct {
	ID                uuid.UUID  `json:"id"`
	ClientID          *uuid.UUID `json:"client_id"`
	JobItemID         *uuid.UUID `json:"job_item_id"`
	ProviderCode      string     `json:"provider_code"`
	ProviderMessageID *string    `json:"provider_message_id"`
	RawPayload        []byte     `json:"raw_payload"`
	NormalizedResult  []byte     `json:"normalized_result"`
	DedupeKey         *string    `json:"dedupe_key"`
	SignatureValid    *bool      `json:"signature_valid"`
	ProcessedAt       *time.Time `json:"processed_at"`
	ProcessError      *string    `json:"process_error"`
	CreatedAt         time.Time  `json:"created_at"`
}

type ProviderLookupRequest struct {
	ID                uuid.UUID                   `json:"id"`
	ClientID          *uuid.UUID                  `json:"client_id"`
	JobItemID         *uuid.UUID                  `json:"job_item_id"`
	ProviderCode      string                      `json:"provider_code"`
	Kind              ProviderLookupKind          `json:"kind"`
	Status            ProviderLookupRequestStatus `json:"status"`
	ProviderMessageID *string                     `json:"provider_message_id"`
	HttpStatus        *int32                      `json:"http_status"`
	ErrorCode         *string                     `json:"error_code"`
	ErrorMessage      *string                     `json:"error_message"`
	RequestPayload    []byte                      `json:"request_payload"`
	ResponsePayload   []byte                      `json:"response_payload"`
	NormalizedResult  []byte                      `json:"normalized_result"`
	IdempotencyKey    *string                     `json:"idempotency_key"`
	StartedAt         *time.Time                  `json:"started_at"`
	FinishedAt        *time.Time                  `json:"finished_at"`
	CreatedAt         time.Time                   `json:"created_at"`
}

type ProviderSendAttempt struct {
	ID           uuid.UUID           `json:"id"`
	SendJobID    uuid.UUID           `json:"send_job_id"`
	Attempt      int32               `json:"attempt"`
	RequestMeta  []byte              `json:"request_meta"`
	HttpStatus   *int32              `json:"http_status"`
	ResponseBody *string             `json:"response_body"`
	LatencyMs    *int32              `json:"latency_ms"`
	ErrorKind    NullSendAttemptKind `json:"error_kind"`
	CreatedAt    time.Time           `json:"created_at"`
}

type SendJob struct {
	ID           uuid.UUID     `json:"id"`
	SmsMessageID uuid.UUID     `json:"sms_message_id"`
	ClientID     *uuid.UUID    `json:"client_id"`
	Status       SendJobStatus `json:"status"`
	Attempt      int32         `json:"attempt"`
	AvailableAt  time.Time     `json:"available_at"`
	LockedAt     *time.Time    `json:"locked_at"`
	LockedBy     *string       `json:"locked_by"`
	LastError    *string       `json:"last_error"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID       `json:"id"`
	Audience     SessionAudience `json:"audience"`
	AdminUserID  *uuid.UUID      `json:"admin_user_id"`
	ClientUserID *uuid.UUID      `json:"client_user_id"`
	ExpiresAt    time.Time       `json:"expires_at"`
	RevokedAt    *time.Time      `json:"revoked_at"`
	Ip           *netip.Addr     `json:"ip"`
	UserAgent    *string         `json:"user_agent"`
	CreatedAt    time.Time       `json:"created_at"`
	LastSeenAt   time.Time       `json:"last_seen_at"`
}

type SmsCampaign struct {
	ID             uuid.UUID      `json:"id"`
	ClientID       uuid.UUID      `json:"client_id"`
	FromMsisdn     string         `json:"from_msisdn"`
	Text           string         `json:"text"`
	Status         CampaignStatus `json:"status"`
	TotalCount     int32          `json:"total_count"`
	AcceptedCount  int32          `json:"accepted_count"`
	DeliveredCount int32          `json:"delivered_count"`
	FailedCount    int32          `json:"failed_count"`
	CreatedBy      *uuid.UUID     `json:"created_by"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type SmsMessage struct {
	ID             uuid.UUID         `json:"id"`
	ClientID       *uuid.UUID        `json:"client_id"`
	Direction      SmsDirection      `json:"direction"`
	FromMsisdn     string            `json:"from_msisdn"`
	ToMsisdn       string            `json:"to_msisdn"`
	Text           string            `json:"text"`
	Provider       string            `json:"provider"`
	ProviderSmsID  *string           `json:"provider_sms_id"`
	ProviderStatus *string           `json:"provider_status"`
	PduCount       *int32            `json:"pdu_count"`
	CampaignID     *uuid.UUID        `json:"campaign_id"`
	Status         SmsStatus         `json:"status"`
	IdempotencyKey *string           `json:"idempotency_key"`
	CreatedAt      time.Time         `json:"created_at"`
	AcceptedAt     *time.Time        `json:"accepted_at"`
	SentAt         *time.Time        `json:"sent_at"`
	DeliveredAt    *time.Time        `json:"delivered_at"`
	FailedAt       *time.Time        `json:"failed_at"`
	UnitSellPrice  *decimal.Decimal  `json:"unit_sell_price"`
	BilledSegments *int32            `json:"billed_segments"`
	TariffPlanID   *uuid.UUID        `json:"tariff_plan_id"`
	TariffPlanCode *string           `json:"tariff_plan_code"`
	Currency       *string           `json:"currency"`
	BillingAction  NullBillingAction `json:"billing_action"`
}

type SystemSetting struct {
	ID                           int16           `json:"id"`
	RunexisEmail                 *string         `json:"runexis_email"`
	RunexisPasswordCiphertext    []byte          `json:"runexis_password_ciphertext"`
	DekKeyID                     *string         `json:"dek_key_id"`
	CallbackBaseUrl              *string         `json:"callback_base_url"`
	SmsDirIn                     bool            `json:"sms_dir_in"`
	SmsDirDomOut                 bool            `json:"sms_dir_dom_out"`
	SmsDirIntOut                 bool            `json:"sms_dir_int_out"`
	SmsDirInMass                 bool            `json:"sms_dir_in_mass"`
	ProviderRps                  pgtype.Numeric  `json:"provider_rps"`
	ClientRpsDefault             pgtype.Numeric  `json:"client_rps_default"`
	RetentionDays                int32           `json:"retention_days"`
	AuditRetentionDays           int32           `json:"audit_retention_days"`
	IngressTokenHash             *string         `json:"ingress_token_hash"`
	UpdatedAt                    time.Time       `json:"updated_at"`
	UpdatedBy                    *uuid.UUID      `json:"updated_by"`
	OpsRetentionDays             int32           `json:"ops_retention_days"`
	BillingEnforced              bool            `json:"billing_enforced"`
	LowBalanceThreshold          decimal.Decimal `json:"low_balance_threshold"`
	LookupEnabled                bool            `json:"lookup_enabled"`
	LookupCheckTimeoutSec        int32           `json:"lookup_check_timeout_sec"`
	LookupPollIntervalSec        int32           `json:"lookup_poll_interval_sec"`
	LookupMaxCsvRows             int32           `json:"lookup_max_csv_rows"`
	LookupMaxCsvBytes            int32           `json:"lookup_max_csv_bytes"`
	LookupMaxBatchPhones         int32           `json:"lookup_max_batch_phones"`
	LookupWebhookMaxAttempts     int32           `json:"lookup_webhook_max_attempts"`
	LookupWebhookTimeoutMs       int32           `json:"lookup_webhook_timeout_ms"`
	LookupRetentionDays          int32           `json:"lookup_retention_days"`
	SmscBaseUrl                  *string         `json:"smsc_base_url"`
	SmscLogin                    *string         `json:"smsc_login"`
	SmscPasswordCiphertext       []byte          `json:"smsc_password_ciphertext"`
	SmscApikeyCiphertext         []byte          `json:"smsc_apikey_ciphertext"`
	SmscCallbackSecretCiphertext []byte          `json:"smsc_callback_secret_ciphertext"`
	SmscCurrency                 string          `json:"smsc_currency"`
}

type TariffPlan struct {
	ID          uuid.UUID       `json:"id"`
	Code        string          `json:"code"`
	Name        string          `json:"name"`
	Product     BillingProduct  `json:"product"`
	SellPrice   decimal.Decimal `json:"sell_price"`
	Currency    string          `json:"currency"`
	IsDefault   bool            `json:"is_default"`
	IsActive    bool            `json:"is_active"`
	Description *string         `json:"description"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type Wallet struct {
	ID               uuid.UUID       `json:"id"`
	ClientID         uuid.UUID       `json:"client_id"`
	Currency         string          `json:"currency"`
	AvailableBalance decimal.Decimal `json:"available_balance"`
	HeldBalance      decimal.Decimal `json:"held_balance"`
	Version          int32           `json:"version"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type WalletTransaction struct {
	ID                    uuid.UUID        `json:"id"`
	WalletID              uuid.UUID        `json:"wallet_id"`
	ClientID              uuid.UUID        `json:"client_id"`
	Type                  WalletTxType     `json:"type"`
	Amount                decimal.Decimal  `json:"amount"`
	Currency              string           `json:"currency"`
	BalanceAfterAvailable *decimal.Decimal `json:"balance_after_available"`
	BalanceAfterHeld      *decimal.Decimal `json:"balance_after_held"`
	RelatedHoldID         *uuid.UUID       `json:"related_hold_id"`
	SmsMessageID          *uuid.UUID       `json:"sms_message_id"`
	IdempotencyKey        *string          `json:"idempotency_key"`
	Description           *string          `json:"description"`
	Metadata              []byte           `json:"metadata"`
	CreatedBy             *uuid.UUID       `json:"created_by"`
	CreatedAt             time.Time        `json:"created_at"`
	LookupJobID           *uuid.UUID       `json:"lookup_job_id"`
	LookupItemID          *uuid.UUID       `json:"lookup_item_id"`
}

type WebhookDelivery struct {
	ID               uuid.UUID             `json:"id"`
	ClientID         uuid.UUID             `json:"client_id"`
	EndpointID       uuid.UUID             `json:"endpoint_id"`
	JobID            *uuid.UUID            `json:"job_id"`
	JobItemID        *uuid.UUID            `json:"job_item_id"`
	EventType        string                `json:"event_type"`
	Payload          []byte                `json:"payload"`
	Status           WebhookDeliveryStatus `json:"status"`
	AttemptCount     int32                 `json:"attempt_count"`
	MaxAttempts      int32                 `json:"max_attempts"`
	NextAttemptAt    *time.Time            `json:"next_attempt_at"`
	LastResponseCode *int32                `json:"last_response_code"`
	LastError        *string               `json:"last_error"`
	DeliveredAt      *time.Time            `json:"delivered_at"`
	CreatedAt        time.Time             `json:"created_at"`
	UpdatedAt        time.Time             `json:"updated_at"`
}

type WebhookEndpoint struct {
	ID                  uuid.UUID `json:"id"`
	ClientID            uuid.UUID `json:"client_id"`
	Url                 string    `json:"url"`
	SecretCiphertext    []byte    `json:"secret_ciphertext"`
	DekKeyID            string    `json:"dek_key_id"`
	Description         *string   `json:"description"`
	Enabled             bool      `json:"enabled"`
	Events              []string  `json:"events"`
	ConsecutiveFailures int32     `json:"consecutive_failures"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}
