// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ops.sql

package sqlcdb

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const getOpsEventByID = `-- name: GetOpsEventByID :one
SELECT id, created_at, category, level, request_id, actor_type, actor_id, client_id, action, resource_type, resource_id, http_method, http_path, http_status, latency_ms, summary, detail, error, ip FROM ops_events WHERE id = $1
`

func (q *Queries) GetOpsEventByID(ctx context.Context, id uuid.UUID) (OpsEvent, error) {
	row := q.db.QueryRow(ctx, getOpsEventByID, id)
	var i OpsEvent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Category,
		&i.Level,
		&i.RequestID,
		&i.ActorType,
		&i.ActorID,
		&i.ClientID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.HttpMethod,
		&i.HttpPath,
		&i.HttpStatus,
		&i.LatencyMs,
		&i.Summary,
		&i.Detail,
		&i.Error,
		&i.Ip,
	)
	return i, err
}

const insertOpsEvent = `-- name: InsertOpsEvent :exec
INSERT INTO ops_events (
    category, level, request_id, actor_type, actor_id, client_id,
    action, resource_type, resource_id,
    http_method, http_path, http_status, latency_ms,
    summary, detail, error, ip
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
`

type InsertOpsEventParams struct {
	Category     string        `json:"category"`
	Level        string        `json:"level"`
	RequestID    *string       `json:"request_id"`
	ActorType    NullActorType `json:"actor_type"`
	ActorID      *uuid.UUID    `json:"actor_id"`
	ClientID     *uuid.UUID    `json:"client_id"`
	Action       string        `json:"action"`
	ResourceType *string       `json:"resource_type"`
	ResourceID   *uuid.UUID    `json:"resource_id"`
	HttpMethod   *string       `json:"http_method"`
	HttpPath     *string       `json:"http_path"`
	HttpStatus   *int32        `json:"http_status"`
	LatencyMs    *int32        `json:"latency_ms"`
	Summary      *string       `json:"summary"`
	Detail       []byte        `json:"detail"`
	Error        *string       `json:"error"`
	Ip           *netip.Addr   `json:"ip"`
}

func (q *Queries) InsertOpsEvent(ctx context.Context, arg InsertOpsEventParams) error {
	_, err := q.db.Exec(ctx, insertOpsEvent,
		arg.Category,
		arg.Level,
		arg.RequestID,
		arg.ActorType,
		arg.ActorID,
		arg.ClientID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.HttpMethod,
		arg.HttpPath,
		arg.HttpStatus,
		arg.LatencyMs,
		arg.Summary,
		arg.Detail,
		arg.Error,
		arg.Ip,
	)
	return err
}

const listOpsEvents = `-- name: ListOpsEvents :many
SELECT
    id, created_at, category, level, request_id,
    actor_type, actor_id, client_id, action,
    resource_type, resource_id,
    http_method, http_path, http_status, latency_ms,
    summary, error, ip
FROM ops_events
WHERE created_at >= $1
  AND created_at < $2
  AND ($3::text IS NULL OR category = $3)
  AND ($4::text IS NULL OR level = $4)
  AND ($5::text IS NULL OR request_id = $5)
  AND ($6::uuid IS NULL OR client_id = $6)
  AND (
        $7::text IS NULL
        OR summary ILIKE $7
        OR action ILIKE $7
        OR COALESCE(error, '') ILIKE $7
      )
ORDER BY created_at DESC
LIMIT $9 OFFSET $8
`

type ListOpsEventsParams struct {
	FromTs     time.Time  `json:"from_ts"`
	ToTs       time.Time  `json:"to_ts"`
	Category   *string    `json:"category"`
	Level      *string    `json:"level"`
	RequestID  *string    `json:"request_id"`
	ClientID   *uuid.UUID `json:"client_id"`
	Q          *string    `json:"q"`
	PageOffset int32      `json:"page_offset"`
	PageLimit  int32      `json:"page_limit"`
}

type ListOpsEventsRow struct {
	ID           uuid.UUID     `json:"id"`
	CreatedAt    time.Time     `json:"created_at"`
	Category     string        `json:"category"`
	Level        string        `json:"level"`
	RequestID    *string       `json:"request_id"`
	ActorType    NullActorType `json:"actor_type"`
	ActorID      *uuid.UUID    `json:"actor_id"`
	ClientID     *uuid.UUID    `json:"client_id"`
	Action       string        `json:"action"`
	ResourceType *string       `json:"resource_type"`
	ResourceID   *uuid.UUID    `json:"resource_id"`
	HttpMethod   *string       `json:"http_method"`
	HttpPath     *string       `json:"http_path"`
	HttpStatus   *int32        `json:"http_status"`
	LatencyMs    *int32        `json:"latency_ms"`
	Summary      *string       `json:"summary"`
	Error        *string       `json:"error"`
	Ip           *netip.Addr   `json:"ip"`
}

func (q *Queries) ListOpsEvents(ctx context.Context, arg ListOpsEventsParams) ([]ListOpsEventsRow, error) {
	rows, err := q.db.Query(ctx, listOpsEvents,
		arg.FromTs,
		arg.ToTs,
		arg.Category,
		arg.Level,
		arg.RequestID,
		arg.ClientID,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpsEventsRow
	for rows.Next() {
		var i ListOpsEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Category,
			&i.Level,
			&i.RequestID,
			&i.ActorType,
			&i.ActorID,
			&i.ClientID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.HttpMethod,
			&i.HttpPath,
			&i.HttpStatus,
			&i.LatencyMs,
			&i.Summary,
			&i.Error,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
