// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimSendJobsFair = `-- name: ClaimSendJobsFair :many
UPDATE send_jobs AS s
SET
    status = 'processing',
    locked_at = now(),
    locked_by = $1,
    updated_at = now()
WHERE s.id IN (
    SELECT j.id
    FROM (
        SELECT client_id
        FROM send_jobs
        WHERE status IN ('pending', 'retry', 'uncertain')
          AND available_at <= now()
          AND (
              client_id IS NULL
              OR EXISTS (
                  SELECT 1 FROM clients cl
                  WHERE cl.id = send_jobs.client_id AND cl.status = 'active'
              )
          )
        GROUP BY client_id
        ORDER BY MIN(available_at)
        LIMIT $2
    ) c
    CROSS JOIN LATERAL (
        SELECT id
        FROM send_jobs
        WHERE client_id IS NOT DISTINCT FROM c.client_id
          AND status IN ('pending', 'retry', 'uncertain')
          AND available_at <= now()
          AND (
              client_id IS NULL
              OR EXISTS (
                  SELECT 1 FROM clients cl
                  WHERE cl.id = send_jobs.client_id AND cl.status = 'active'
              )
          )
        ORDER BY
            CASE status
                WHEN 'uncertain' THEN 0
                WHEN 'retry' THEN 1
                ELSE 2
            END,
            available_at,
            id
        LIMIT 1
        FOR UPDATE SKIP LOCKED
    ) j
)
RETURNING id, sms_message_id, client_id, status, attempt, available_at, locked_at, locked_by, last_error, created_at, updated_at
`

type ClaimSendJobsFairParams struct {
	WorkerID   *string `json:"worker_id"`
	BatchLimit int32   `json:"batch_limit"`
}

func (q *Queries) ClaimSendJobsFair(ctx context.Context, arg ClaimSendJobsFairParams) ([]SendJob, error) {
	rows, err := q.db.Query(ctx, claimSendJobsFair, arg.WorkerID, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SendJob
	for rows.Next() {
		var i SendJob
		if err := rows.Scan(
			&i.ID,
			&i.SmsMessageID,
			&i.ClientID,
			&i.Status,
			&i.Attempt,
			&i.AvailableAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeSendJob = `-- name: CompleteSendJob :execrows
UPDATE send_jobs
SET status = 'done',
    locked_at = NULL,
    locked_by = NULL,
    last_error = NULL,
    updated_at = now()
WHERE id = $1
  AND status = 'processing'
  AND locked_by = $2
`

type CompleteSendJobParams struct {
	ID       uuid.UUID `json:"id"`
	WorkerID *string   `json:"worker_id"`
}

func (q *Queries) CompleteSendJob(ctx context.Context, arg CompleteSendJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeSendJob, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestSendAttempt = `-- name: GetLatestSendAttempt :one
SELECT id, send_job_id, attempt, request_meta, http_status, response_body, latency_ms, error_kind, created_at FROM provider_send_attempts
WHERE send_job_id = $1
ORDER BY attempt DESC, created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSendAttempt(ctx context.Context, sendJobID uuid.UUID) (ProviderSendAttempt, error) {
	row := q.db.QueryRow(ctx, getLatestSendAttempt, sendJobID)
	var i ProviderSendAttempt
	err := row.Scan(
		&i.ID,
		&i.SendJobID,
		&i.Attempt,
		&i.RequestMeta,
		&i.HttpStatus,
		&i.ResponseBody,
		&i.LatencyMs,
		&i.ErrorKind,
		&i.CreatedAt,
	)
	return i, err
}

const insertSendAttempt = `-- name: InsertSendAttempt :exec
INSERT INTO provider_send_attempts (
    send_job_id, attempt, request_meta, http_status, response_body, latency_ms, error_kind
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type InsertSendAttemptParams struct {
	SendJobID    uuid.UUID           `json:"send_job_id"`
	Attempt      int32               `json:"attempt"`
	RequestMeta  []byte              `json:"request_meta"`
	HttpStatus   *int32              `json:"http_status"`
	ResponseBody *string             `json:"response_body"`
	LatencyMs    *int32              `json:"latency_ms"`
	ErrorKind    NullSendAttemptKind `json:"error_kind"`
}

func (q *Queries) InsertSendAttempt(ctx context.Context, arg InsertSendAttemptParams) error {
	_, err := q.db.Exec(ctx, insertSendAttempt,
		arg.SendJobID,
		arg.Attempt,
		arg.RequestMeta,
		arg.HttpStatus,
		arg.ResponseBody,
		arg.LatencyMs,
		arg.ErrorKind,
	)
	return err
}

const insertSendJob = `-- name: InsertSendJob :one
INSERT INTO send_jobs (sms_message_id, client_id, status)
VALUES ($1, $2, 'pending')
RETURNING id, sms_message_id, client_id, status, attempt, available_at, locked_at, locked_by, last_error, created_at, updated_at
`

type InsertSendJobParams struct {
	SmsMessageID uuid.UUID  `json:"sms_message_id"`
	ClientID     *uuid.UUID `json:"client_id"`
}

func (q *Queries) InsertSendJob(ctx context.Context, arg InsertSendJobParams) (SendJob, error) {
	row := q.db.QueryRow(ctx, insertSendJob, arg.SmsMessageID, arg.ClientID)
	var i SendJob
	err := row.Scan(
		&i.ID,
		&i.SmsMessageID,
		&i.ClientID,
		&i.Status,
		&i.Attempt,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const parkSendJob = `-- name: ParkSendJob :execrows
UPDATE send_jobs
SET status = $1,
    attempt = $2,
    available_at = $3,
    locked_at = NULL,
    locked_by = NULL,
    last_error = $4,
    updated_at = now()
WHERE id = $5
  AND status = 'processing'
  AND locked_by = $6
`

type ParkSendJobParams struct {
	Status      SendJobStatus `json:"status"`
	Attempt     int32         `json:"attempt"`
	AvailableAt time.Time     `json:"available_at"`
	LastError   *string       `json:"last_error"`
	ID          uuid.UUID     `json:"id"`
	WorkerID    *string       `json:"worker_id"`
}

func (q *Queries) ParkSendJob(ctx context.Context, arg ParkSendJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, parkSendJob,
		arg.Status,
		arg.Attempt,
		arg.AvailableAt,
		arg.LastError,
		arg.ID,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reclaimStaleSendJobs = `-- name: ReclaimStaleSendJobs :execrows
UPDATE send_jobs
SET status = 'uncertain',
    last_error = 'uncertain:need_stat',
    attempt = GREATEST(attempt, 1),
    locked_at = NULL,
    locked_by = NULL,
    available_at = now(),
    updated_at = now()
WHERE status = 'processing'
  AND locked_at < $1
`

func (q *Queries) ReclaimStaleSendJobs(ctx context.Context, staleBefore *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimStaleSendJobs, staleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSendJobLock = `-- name: TouchSendJobLock :one
UPDATE send_jobs
SET locked_at = now(), updated_at = now()
WHERE id = $1
  AND status = 'processing'
  AND locked_by = $2
RETURNING id, sms_message_id, client_id, status, attempt, available_at, locked_at, locked_by, last_error, created_at, updated_at
`

type TouchSendJobLockParams struct {
	ID       uuid.UUID `json:"id"`
	WorkerID *string   `json:"worker_id"`
}

func (q *Queries) TouchSendJobLock(ctx context.Context, arg TouchSendJobLockParams) (SendJob, error) {
	row := q.db.QueryRow(ctx, touchSendJobLock, arg.ID, arg.WorkerID)
	var i SendJob
	err := row.Scan(
		&i.ID,
		&i.SmsMessageID,
		&i.ClientID,
		&i.Status,
		&i.Attempt,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
