// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: retention.sql

package sqlcdb

import (
	"context"
	"time"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at < now()
   OR (revoked_at IS NOT NULL AND revoked_at < now() - interval '7 days')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldAuditLog = `-- name: DeleteOldAuditLog :execrows
DELETE FROM audit_log
WHERE id IN (
    SELECT a.id FROM audit_log a
    WHERE a.created_at < $1
    ORDER BY a.created_at
    LIMIT 1000
)
`

func (q *Queries) DeleteOldAuditLog(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldAuditLog, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldCallbackEvents = `-- name: DeleteOldCallbackEvents :execrows
DELETE FROM provider_callback_events
WHERE id IN (
    SELECT e.id FROM provider_callback_events e
    WHERE e.created_at < $1
    ORDER BY e.created_at
    LIMIT 1000
)
`

func (q *Queries) DeleteOldCallbackEvents(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldCallbackEvents, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldCampaigns = `-- name: DeleteOldCampaigns :execrows
DELETE FROM sms_campaigns
WHERE created_at < $1
  AND status IN ('completed', 'failed', 'cancelled', 'draft')
`

func (q *Queries) DeleteOldCampaigns(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldCampaigns, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldOpsEvents = `-- name: DeleteOldOpsEvents :execrows
DELETE FROM ops_events
WHERE id IN (
    SELECT e.id FROM ops_events e
    WHERE e.created_at < $1
    ORDER BY e.created_at
    LIMIT 5000
)
`

func (q *Queries) DeleteOldOpsEvents(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldOpsEvents, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldSmsMessages = `-- name: DeleteOldSmsMessages :execrows
WITH doomed AS (
    SELECT m.id
    FROM sms_messages m
    WHERE m.created_at < $1
      AND NOT (m.unit_sell_price IS NOT NULL AND m.billing_action IS NULL)
    ORDER BY m.created_at
    LIMIT 200
),
unlinked_rec AS (
    UPDATE campaign_recipients
    SET sms_message_id = NULL
    WHERE sms_message_id IN (SELECT id FROM doomed)
),
unlinked_cb AS (
    UPDATE provider_callback_events
    SET sms_message_id = NULL
    WHERE sms_message_id IN (SELECT id FROM doomed)
),
del_attempts AS (
    DELETE FROM provider_send_attempts
    WHERE send_job_id IN (
        SELECT id FROM send_jobs WHERE sms_message_id IN (SELECT id FROM doomed)
    )
),
del_jobs AS (
    DELETE FROM send_jobs
    WHERE sms_message_id IN (SELECT id FROM doomed)
)
DELETE FROM sms_messages
WHERE id IN (SELECT id FROM doomed)
`

func (q *Queries) DeleteOldSmsMessages(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldSmsMessages, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
