// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlcdb

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, audience, admin_user_id, client_user_id, expires_at, revoked_at, ip, user_agent, created_at, last_seen_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Audience,
		&i.AdminUserID,
		&i.ClientUserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (audience, admin_user_id, client_user_id, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, audience, admin_user_id, client_user_id, expires_at, revoked_at, ip, user_agent, created_at, last_seen_at
`

type InsertSessionParams struct {
	Audience     SessionAudience `json:"audience"`
	AdminUserID  *uuid.UUID      `json:"admin_user_id"`
	ClientUserID *uuid.UUID      `json:"client_user_id"`
	ExpiresAt    time.Time       `json:"expires_at"`
	Ip           *netip.Addr     `json:"ip"`
	UserAgent    *string         `json:"user_agent"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.Audience,
		arg.AdminUserID,
		arg.ClientUserID,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Audience,
		&i.AdminUserID,
		&i.ClientUserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionsForClient = `-- name: RevokeSessionsForClient :exec
UPDATE sessions s
SET revoked_at = now()
FROM client_users u
WHERE s.client_user_id = u.id
  AND u.client_id = $1
  AND s.revoked_at IS NULL
`

func (q *Queries) RevokeSessionsForClient(ctx context.Context, clientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionsForClient, clientID)
	return err
}

const revokeSessionsForClientUser = `-- name: RevokeSessionsForClientUser :exec
UPDATE sessions
SET revoked_at = now()
WHERE client_user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionsForClientUser(ctx context.Context, clientUserID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionsForClientUser, clientUserID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = now(), expires_at = $1
WHERE id = $2 AND revoked_at IS NULL AND expires_at > now()
`

type TouchSessionParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ExpiresAt, arg.ID)
	return err
}
