// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getSystemSettings = `-- name: GetSystemSettings :one
SELECT id, runexis_email, runexis_password_ciphertext, dek_key_id, callback_base_url, sms_dir_in, sms_dir_dom_out, sms_dir_int_out, sms_dir_in_mass, provider_rps, client_rps_default, retention_days, audit_retention_days, ingress_token_hash, updated_at, updated_by, ops_retention_days, billing_enforced, low_balance_threshold, lookup_enabled, lookup_check_timeout_sec, lookup_poll_interval_sec, lookup_max_csv_rows, lookup_max_csv_bytes, lookup_max_batch_phones, lookup_webhook_max_attempts, lookup_webhook_timeout_ms, lookup_retention_days, smsc_base_url, smsc_login, smsc_password_ciphertext, smsc_apikey_ciphertext, smsc_callback_secret_ciphertext, smsc_currency FROM system_settings WHERE id = 1
`

func (q *Queries) GetSystemSettings(ctx context.Context) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSettings)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.RunexisEmail,
		&i.RunexisPasswordCiphertext,
		&i.DekKeyID,
		&i.CallbackBaseUrl,
		&i.SmsDirIn,
		&i.SmsDirDomOut,
		&i.SmsDirIntOut,
		&i.SmsDirInMass,
		&i.ProviderRps,
		&i.ClientRpsDefault,
		&i.RetentionDays,
		&i.AuditRetentionDays,
		&i.IngressTokenHash,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.OpsRetentionDays,
		&i.BillingEnforced,
		&i.LowBalanceThreshold,
		&i.LookupEnabled,
		&i.LookupCheckTimeoutSec,
		&i.LookupPollIntervalSec,
		&i.LookupMaxCsvRows,
		&i.LookupMaxCsvBytes,
		&i.LookupMaxBatchPhones,
		&i.LookupWebhookMaxAttempts,
		&i.LookupWebhookTimeoutMs,
		&i.LookupRetentionDays,
		&i.SmscBaseUrl,
		&i.SmscLogin,
		&i.SmscPasswordCiphertext,
		&i.SmscApikeyCiphertext,
		&i.SmscCallbackSecretCiphertext,
		&i.SmscCurrency,
	)
	return i, err
}

const updateSystemSettings = `-- name: UpdateSystemSettings :one
UPDATE system_settings
SET
    runexis_email = $1,
    runexis_password_ciphertext = $2,
    dek_key_id = $3,
    callback_base_url = $4,
    sms_dir_in = $5,
    sms_dir_dom_out = $6,
    sms_dir_int_out = $7,
    sms_dir_in_mass = $8,
    provider_rps = $9,
    client_rps_default = $10,
    retention_days = $11,
    audit_retention_days = $12,
    ops_retention_days = $13,
    ingress_token_hash = $14,
    billing_enforced = $15,
    low_balance_threshold = $16,
    lookup_enabled = $17,
    lookup_check_timeout_sec = $18,
    lookup_poll_interval_sec = $19,
    lookup_max_csv_rows = $20,
    lookup_max_csv_bytes = $21,
    lookup_max_batch_phones = $22,
    lookup_webhook_max_attempts = $23,
    lookup_webhook_timeout_ms = $24,
    lookup_retention_days = $25,
    smsc_base_url = $26,
    smsc_login = $27,
    smsc_password_ciphertext = $28,
    smsc_apikey_ciphertext = $29,
    smsc_callback_secret_ciphertext = $30,
    smsc_currency = $31,
    updated_by = $32,
    updated_at = now()
WHERE id = 1
RETURNING id, runexis_email, runexis_password_ciphertext, dek_key_id, callback_base_url, sms_dir_in, sms_dir_dom_out, sms_dir_int_out, sms_dir_in_mass, provider_rps, client_rps_default, retention_days, audit_retention_days, ingress_token_hash, updated_at, updated_by, ops_retention_days, billing_enforced, low_balance_threshold, lookup_enabled, lookup_check_timeout_sec, lookup_poll_interval_sec, lookup_max_csv_rows, lookup_max_csv_bytes, lookup_max_batch_phones, lookup_webhook_max_attempts, lookup_webhook_timeout_ms, lookup_retention_days, smsc_base_url, smsc_login, smsc_password_ciphertext, smsc_apikey_ciphertext, smsc_callback_secret_ciphertext, smsc_currency
`

type UpdateSystemSettingsParams struct {
	RunexisEmail                 *string         `json:"runexis_email"`
	RunexisPasswordCiphertext    []byte          `json:"runexis_password_ciphertext"`
	DekKeyID                     *string         `json:"dek_key_id"`
	CallbackBaseUrl              *string         `json:"callback_base_url"`
	SmsDirIn                     bool            `json:"sms_dir_in"`
	SmsDirDomOut                 bool            `json:"sms_dir_dom_out"`
	SmsDirIntOut                 bool            `json:"sms_dir_int_out"`
	SmsDirInMass                 bool            `json:"sms_dir_in_mass"`
	ProviderRps                  pgtype.Numeric  `json:"provider_rps"`
	ClientRpsDefault             pgtype.Numeric  `json:"client_rps_default"`
	RetentionDays                int32           `json:"retention_days"`
	AuditRetentionDays           int32           `json:"audit_retention_days"`
	OpsRetentionDays             int32           `json:"ops_retention_days"`
	IngressTokenHash             *string         `json:"ingress_token_hash"`
	BillingEnforced              bool            `json:"billing_enforced"`
	LowBalanceThreshold          decimal.Decimal `json:"low_balance_threshold"`
	LookupEnabled                bool            `json:"lookup_enabled"`
	LookupCheckTimeoutSec        int32           `json:"lookup_check_timeout_sec"`
	LookupPollIntervalSec        int32           `json:"lookup_poll_interval_sec"`
	LookupMaxCsvRows             int32           `json:"lookup_max_csv_rows"`
	LookupMaxCsvBytes            int32           `json:"lookup_max_csv_bytes"`
	LookupMaxBatchPhones         int32           `json:"lookup_max_batch_phones"`
	LookupWebhookMaxAttempts     int32           `json:"lookup_webhook_max_attempts"`
	LookupWebhookTimeoutMs       int32           `json:"lookup_webhook_timeout_ms"`
	LookupRetentionDays          int32           `json:"lookup_retention_days"`
	SmscBaseUrl                  *string         `json:"smsc_base_url"`
	SmscLogin                    *string         `json:"smsc_login"`
	SmscPasswordCiphertext       []byte          `json:"smsc_password_ciphertext"`
	SmscApikeyCiphertext         []byte          `json:"smsc_apikey_ciphertext"`
	SmscCallbackSecretCiphertext []byte          `json:"smsc_callback_secret_ciphertext"`
	SmscCurrency                 string          `json:"smsc_currency"`
	UpdatedBy                    *uuid.UUID      `json:"updated_by"`
}

func (q *Queries) UpdateSystemSettings(ctx context.Context, arg UpdateSystemSettingsParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, updateSystemSettings,
		arg.RunexisEmail,
		arg.RunexisPasswordCiphertext,
		arg.DekKeyID,
		arg.CallbackBaseUrl,
		arg.SmsDirIn,
		arg.SmsDirDomOut,
		arg.SmsDirIntOut,
		arg.SmsDirInMass,
		arg.ProviderRps,
		arg.ClientRpsDefault,
		arg.RetentionDays,
		arg.AuditRetentionDays,
		arg.OpsRetentionDays,
		arg.IngressTokenHash,
		arg.BillingEnforced,
		arg.LowBalanceThreshold,
		arg.LookupEnabled,
		arg.LookupCheckTimeoutSec,
		arg.LookupPollIntervalSec,
		arg.LookupMaxCsvRows,
		arg.LookupMaxCsvBytes,
		arg.LookupMaxBatchPhones,
		arg.LookupWebhookMaxAttempts,
		arg.LookupWebhookTimeoutMs,
		arg.LookupRetentionDays,
		arg.SmscBaseUrl,
		arg.SmscLogin,
		arg.SmscPasswordCiphertext,
		arg.SmscApikeyCiphertext,
		arg.SmscCallbackSecretCiphertext,
		arg.SmscCurrency,
		arg.UpdatedBy,
	)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.RunexisEmail,
		&i.RunexisPasswordCiphertext,
		&i.DekKeyID,
		&i.CallbackBaseUrl,
		&i.SmsDirIn,
		&i.SmsDirDomOut,
		&i.SmsDirIntOut,
		&i.SmsDirInMass,
		&i.ProviderRps,
		&i.ClientRpsDefault,
		&i.RetentionDays,
		&i.AuditRetentionDays,
		&i.IngressTokenHash,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.OpsRetentionDays,
		&i.BillingEnforced,
		&i.LowBalanceThreshold,
		&i.LookupEnabled,
		&i.LookupCheckTimeoutSec,
		&i.LookupPollIntervalSec,
		&i.LookupMaxCsvRows,
		&i.LookupMaxCsvBytes,
		&i.LookupMaxBatchPhones,
		&i.LookupWebhookMaxAttempts,
		&i.LookupWebhookTimeoutMs,
		&i.LookupRetentionDays,
		&i.SmscBaseUrl,
		&i.SmscLogin,
		&i.SmscPasswordCiphertext,
		&i.SmscApikeyCiphertext,
		&i.SmscCallbackSecretCiphertext,
		&i.SmscCurrency,
	)
	return i, err
}
