// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimWebhookDeliveries = `-- name: ClaimWebhookDeliveries :many
UPDATE webhook_deliveries AS d
SET next_attempt_at = now() + interval '120 seconds',
    updated_at = now()
WHERE d.id IN (
    SELECT d.id
    FROM webhook_deliveries d
    JOIN clients c ON c.id = d.client_id AND c.status = 'active'
    WHERE d.status IN ('pending', 'failed')
      AND d.next_attempt_at IS NOT NULL
      AND d.next_attempt_at <= now()
    ORDER BY d.next_attempt_at, d.id
    FOR UPDATE OF d SKIP LOCKED
    LIMIT $1
)
RETURNING id, client_id, endpoint_id, job_id, job_item_id, event_type, payload, status, attempt_count, max_attempts, next_attempt_at, last_response_code, last_error, delivered_at, created_at, updated_at
`

func (q *Queries) ClaimWebhookDeliveries(ctx context.Context, pageLimit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, claimWebhookDeliveries, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.EndpointID,
			&i.JobID,
			&i.JobItemID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LastResponseCode,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWebhookDeliveriesForClient = `-- name: CountWebhookDeliveriesForClient :one
SELECT count(*)::bigint AS n
FROM webhook_deliveries
WHERE client_id = $1
  AND ($2::uuid IS NULL OR endpoint_id = $2)
  AND ($3::webhook_delivery_status IS NULL OR status = $3)
`

type CountWebhookDeliveriesForClientParams struct {
	ClientID     uuid.UUID                 `json:"client_id"`
	EndpointID   *uuid.UUID                `json:"endpoint_id"`
	FilterStatus NullWebhookDeliveryStatus `json:"filter_status"`
}

func (q *Queries) CountWebhookDeliveriesForClient(ctx context.Context, arg CountWebhookDeliveriesForClientParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveriesForClient, arg.ClientID, arg.EndpointID, arg.FilterStatus)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countWebhookDeliveriesSince = `-- name: CountWebhookDeliveriesSince :one
SELECT count(*)::bigint AS n
FROM webhook_deliveries
WHERE created_at >= $1
`

func (q *Queries) CountWebhookDeliveriesSince(ctx context.Context, since time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveriesSince, since)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countWebhookEndpointsForClient = `-- name: CountWebhookEndpointsForClient :one
SELECT count(*)::bigint AS n
FROM webhook_endpoints
WHERE client_id = $1
`

func (q *Queries) CountWebhookEndpointsForClient(ctx context.Context, clientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookEndpointsForClient, clientID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :execrows
DELETE FROM webhook_endpoints
WHERE id = $1
  AND client_id = $2
`

type DeleteWebhookEndpointParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookEndpoint, arg.ID, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, client_id, url, secret_ciphertext, dek_key_id, description, enabled, events, consecutive_failures, created_at, updated_at
FROM webhook_endpoints
WHERE id = $1
`

func (q *Queries) GetWebhookEndpoint(ctx context.Context, id uuid.UUID) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpoint, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Url,
		&i.SecretCiphertext,
		&i.DekKeyID,
		&i.Description,
		&i.Enabled,
		&i.Events,
		&i.ConsecutiveFailures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEndpointForClient = `-- name: GetWebhookEndpointForClient :one
SELECT id, client_id, url, secret_ciphertext, dek_key_id, description, enabled, events, consecutive_failures, created_at, updated_at
FROM webhook_endpoints
WHERE id = $1
  AND client_id = $2
`

type GetWebhookEndpointForClientParams struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) GetWebhookEndpointForClient(ctx context.Context, arg GetWebhookEndpointForClientParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointForClient, arg.ID, arg.ClientID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Url,
		&i.SecretCiphertext,
		&i.DekKeyID,
		&i.Description,
		&i.Enabled,
		&i.Events,
		&i.ConsecutiveFailures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementWebhookEndpointFailures = `-- name: IncrementWebhookEndpointFailures :one
UPDATE webhook_endpoints
SET consecutive_failures = consecutive_failures + 1,
    enabled = CASE
        WHEN consecutive_failures + 1 >= $1 THEN false
        ELSE enabled
    END,
    updated_at = now()
WHERE id = $2
RETURNING id, client_id, url, secret_ciphertext, dek_key_id, description, enabled, events, consecutive_failures, created_at, updated_at
`

type IncrementWebhookEndpointFailuresParams struct {
	DisableAfter int32     `json:"disable_after"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) IncrementWebhookEndpointFailures(ctx context.Context, arg IncrementWebhookEndpointFailuresParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, incrementWebhookEndpointFailures, arg.DisableAfter, arg.ID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Url,
		&i.SecretCiphertext,
		&i.DekKeyID,
		&i.Description,
		&i.Enabled,
		&i.Events,
		&i.ConsecutiveFailures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :one
INSERT INTO webhook_deliveries (
    id,
    client_id,
    endpoint_id,
    job_id,
    job_item_id,
    event_type,
    payload,
    status,
    max_attempts,
    next_attempt_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, client_id, endpoint_id, job_id, job_item_id, event_type, payload, status, attempt_count, max_attempts, next_attempt_at, last_response_code, last_error, delivered_at, created_at, updated_at
`

type InsertWebhookDeliveryParams struct {
	ID            uuid.UUID             `json:"id"`
	ClientID      uuid.UUID             `json:"client_id"`
	EndpointID    uuid.UUID             `json:"endpoint_id"`
	JobID         *uuid.UUID            `json:"job_id"`
	JobItemID     *uuid.UUID            `json:"job_item_id"`
	EventType     string                `json:"event_type"`
	Payload       []byte                `json:"payload"`
	Status        WebhookDeliveryStatus `json:"status"`
	MaxAttempts   int32                 `json:"max_attempts"`
	NextAttemptAt *time.Time            `json:"next_attempt_at"`
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, insertWebhookDelivery,
		arg.ID,
		arg.ClientID,
		arg.EndpointID,
		arg.JobID,
		arg.JobItemID,
		arg.EventType,
		arg.Payload,
		arg.Status,
		arg.MaxAttempts,
		arg.NextAttemptAt,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.EndpointID,
		&i.JobID,
		&i.JobItemID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastResponseCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhookEndpoint = `-- name: InsertWebhookEndpoint :one
INSERT INTO webhook_endpoints (
    client_id,
    url,
    secret_ciphertext,
    dek_key_id,
    description,
    enabled,
    events
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, client_id, url, secret_ciphertext, dek_key_id, description, enabled, events, consecutive_failures, created_at, updated_at
`

type InsertWebhookEndpointParams struct {
	ClientID         uuid.UUID `json:"client_id"`
	Url              string    `json:"url"`
	SecretCiphertext []byte    `json:"secret_ciphertext"`
	DekKeyID         string    `json:"dek_key_id"`
	Description      *string   `json:"description"`
	Enabled          bool      `json:"enabled"`
	Events           []string  `json:"events"`
}

func (q *Queries) InsertWebhookEndpoint(ctx context.Context, arg InsertWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, insertWebhookEndpoint,
		arg.ClientID,
		arg.Url,
		arg.SecretCiphertext,
		arg.DekKeyID,
		arg.Description,
		arg.Enabled,
		arg.Events,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Url,
		&i.SecretCiphertext,
		&i.DekKeyID,
		&i.Description,
		&i.Enabled,
		&i.Events,
		&i.ConsecutiveFailures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledWebhookEndpoints = `-- name: ListEnabledWebhookEndpoints :many
SELECT id, client_id, url, secret_ciphertext, dek_key_id, description, enabled, events, consecutive_failures, created_at, updated_at
FROM webhook_endpoints
WHERE client_id = $1
  AND enabled = true
`

func (q *Queries) ListEnabledWebhookEndpoints(ctx context.Context, clientID uuid.UUID) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listEnabledWebhookEndpoints, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Url,
			&i.SecretCiphertext,
			&i.DekKeyID,
			&i.Description,
			&i.Enabled,
			&i.Events,
			&i.ConsecutiveFailures,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesForClient = `-- name: ListWebhookDeliveriesForClient :many
SELECT id, client_id, endpoint_id, job_id, job_item_id, event_type, payload, status, attempt_count, max_attempts, next_attempt_at, last_response_code, last_error, delivered_at, created_at, updated_at
FROM webhook_deliveries
WHERE client_id = $1
  AND ($2::uuid IS NULL OR endpoint_id = $2)
  AND ($3::webhook_delivery_status IS NULL OR status = $3)
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListWebhookDeliveriesForClientParams struct {
	ClientID     uuid.UUID                 `json:"client_id"`
	EndpointID   *uuid.UUID                `json:"endpoint_id"`
	FilterStatus NullWebhookDeliveryStatus `json:"filter_status"`
	PageOffset   int32                     `json:"page_offset"`
	PageLimit    int32                     `json:"page_limit"`
}

func (q *Queries) ListWebhookDeliveriesForClient(ctx context.Context, arg ListWebhookDeliveriesForClientParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesForClient,
		arg.ClientID,
		arg.EndpointID,
		arg.FilterStatus,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.EndpointID,
			&i.JobID,
			&i.JobItemID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LastResponseCode,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpointsForClient = `-- name: ListWebhookEndpointsForClient :many
SELECT id, client_id, url, secret_ciphertext, dek_key_id, description, enabled, events, consecutive_failures, created_at, updated_at
FROM webhook_endpoints
WHERE client_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListWebhookEndpointsForClientParams struct {
	ClientID   uuid.UUID `json:"client_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListWebhookEndpointsForClient(ctx context.Context, arg ListWebhookEndpointsForClientParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpointsForClient, arg.ClientID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Url,
			&i.SecretCiphertext,
			&i.DekKeyID,
			&i.Description,
			&i.Enabled,
			&i.Events,
			&i.ConsecutiveFailures,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeliveryAttempt = `-- name: MarkWebhookDeliveryAttempt :one
UPDATE webhook_deliveries
SET status = $1,
    attempt_count = $2,
    last_response_code = $3,
    last_error = $4,
    next_attempt_at = $5,
    updated_at = now()
WHERE id = $6
RETURNING id, client_id, endpoint_id, job_id, job_item_id, event_type, payload, status, attempt_count, max_attempts, next_attempt_at, last_response_code, last_error, delivered_at, created_at, updated_at
`

type MarkWebhookDeliveryAttemptParams struct {
	Status           WebhookDeliveryStatus `json:"status"`
	AttemptCount     int32                 `json:"attempt_count"`
	LastResponseCode *int32                `json:"last_response_code"`
	LastError        *string               `json:"last_error"`
	NextAttemptAt    *time.Time            `json:"next_attempt_at"`
	ID               uuid.UUID             `json:"id"`
}

func (q *Queries) MarkWebhookDeliveryAttempt(ctx context.Context, arg MarkWebhookDeliveryAttemptParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliveryAttempt,
		arg.Status,
		arg.AttemptCount,
		arg.LastResponseCode,
		arg.LastError,
		arg.NextAttemptAt,
		arg.ID,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.EndpointID,
		&i.JobID,
		&i.JobItemID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastResponseCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWebhookDeliveryDelivered = `-- name: MarkWebhookDeliveryDelivered :one
UPDATE webhook_deliveries
SET status = 'delivered',
    attempt_count = $1,
    last_response_code = $2,
    last_error = NULL,
    delivered_at = now(),
    next_attempt_at = NULL,
    updated_at = now()
WHERE id = $3
RETURNING id, client_id, endpoint_id, job_id, job_item_id, event_type, payload, status, attempt_count, max_attempts, next_attempt_at, last_response_code, last_error, delivered_at, created_at, updated_at
`

type MarkWebhookDeliveryDeliveredParams struct {
	AttemptCount     int32     `json:"attempt_count"`
	LastResponseCode *int32    `json:"last_response_code"`
	ID               uuid.UUID `json:"id"`
}

func (q *Queries) MarkWebhookDeliveryDelivered(ctx context.Context, arg MarkWebhookDeliveryDeliveredParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliveryDelivered, arg.AttemptCount, arg.LastResponseCode, arg.ID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.EndpointID,
		&i.JobID,
		&i.JobItemID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastResponseCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetWebhookEndpointFailures = `-- name: ResetWebhookEndpointFailures :exec
UPDATE webhook_endpoints
SET consecutive_failures = 0,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ResetWebhookEndpointFailures(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetWebhookEndpointFailures, id)
	return err
}

const updateWebhookEndpoint = `-- name: UpdateWebhookEndpoint :one
UPDATE webhook_endpoints
SET url = COALESCE($1, url),
    description = COALESCE($2, description),
    enabled = COALESCE($3, enabled),
    events = COALESCE($4, events),
    consecutive_failures = COALESCE($5, consecutive_failures),
    secret_ciphertext = COALESCE($6, secret_ciphertext),
    dek_key_id = COALESCE($7, dek_key_id),
    updated_at = now()
WHERE id = $8
  AND client_id = $9
RETURNING id, client_id, url, secret_ciphertext, dek_key_id, description, enabled, events, consecutive_failures, created_at, updated_at
`

type UpdateWebhookEndpointParams struct {
	Url                 *string   `json:"url"`
	Description         *string   `json:"description"`
	Enabled             *bool     `json:"enabled"`
	Events              []string  `json:"events"`
	ConsecutiveFailures *int32    `json:"consecutive_failures"`
	SecretCiphertext    []byte    `json:"secret_ciphertext"`
	DekKeyID            *string   `json:"dek_key_id"`
	ID                  uuid.UUID `json:"id"`
	ClientID            uuid.UUID `json:"client_id"`
}

func (q *Queries) UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, updateWebhookEndpoint,
		arg.Url,
		arg.Description,
		arg.Enabled,
		arg.Events,
		arg.ConsecutiveFailures,
		arg.SecretCiphertext,
		arg.DekKeyID,
		arg.ID,
		arg.ClientID,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Url,
		&i.SecretCiphertext,
		&i.DekKeyID,
		&i.Description,
		&i.Enabled,
		&i.Events,
		&i.ConsecutiveFailures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
